#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$(cd -- "$SCRIPT_DIR/.." && pwd)"
SRC_DIR="$BACKEND_DIR/src/main/resources/db/first_version_four_table"
OUT="${1:-$SRC_DIR/V1__init.sql}"

required=(
  sys_common_record.sql
  app_paipai_record.sql
  app_saving_record.sql
  app_fitmystery_record.sql
)

for file in "${required[@]}"; do
  test -s "$SRC_DIR/$file" || { echo "missing required init file: $SRC_DIR/$file" >&2; exit 1; }
done

{
  echo "-- First-version four-table schema draft."
  echo "-- Generated by scripts/compose-db-four-table-init.sh from four initialization files."
  echo "-- IMPORTANT: keep outside db/migration until Java persistence has been migrated and verified."
  echo
  for file in "${required[@]}"; do
    echo "-- ============================================================================"
    echo "-- source: $file"
    echo "-- ============================================================================"
    cat "$SRC_DIR/$file"
    echo
  done
} > "$OUT"

echo "wrote $OUT"
