#!/usr/bin/env python3
"""Split current Flyway DB initialization SQL into four app/common init files.

This is a source-organization helper: it does not change src/main/resources/db/migration.
The generated files are intended as first-version initialization inputs grouped by owner:
  - sys_common_record.sql: sys_* tables/sequences/indexes/seeds
  - app_paipai_record.sql: reading_* tables/sequences/indexes/seeds
  - app_saving_record.sql: saving_* tables/sequences/indexes/seeds
  - app_fitmystery_record.sql: fit_* tables/sequences/indexes/seeds
"""
from pathlib import Path
import re
import sys
from collections import Counter

BACKEND = Path(__file__).resolve().parents[1]
MIGRATION_DIR = BACKEND / "src/main/resources/db/migration"
OUT_DIR = BACKEND / "src/main/resources/db/first_version_four_table"

OUTPUTS = {
    "common": "sys_common_record.sql",
    "paipai": "app_paipai_record.sql",
    "saving": "app_saving_record.sql",
    "fitmystery": "app_fitmystery_record.sql",
}
PREFIX_TO_AREA = {
    "sys_": "common",
    "reading_": "paipai",
    "saving_": "saving",
    "fit_": "fitmystery",
}

HEADER = """-- Generated first-version initialization SQL grouped by ownership area.
-- Source: src/main/resources/db/migration/V*.sql
-- Generated by: scripts/split-db-migrations-into-four-init-files.py
-- IMPORTANT: this directory is not the active Flyway migration path unless explicitly wired later.
""".rstrip()


def migration_sort_key(path):
    m = re.match(r"V(\d+)__", path.name)
    return (int(m.group(1)) if m else 10**9, path.name)


def split_sql_statements(sql):
    statements = []
    buf = []
    in_single = False
    in_double = False
    in_line_comment = False
    in_block_comment = False
    dollar_tag = None
    i = 0
    n = len(sql)
    while i < n:
        ch = sql[i]
        nxt = sql[i + 1] if i + 1 < n else ""
        if in_line_comment:
            buf.append(ch)
            if ch == "\n":
                in_line_comment = False
            i += 1
            continue
        if in_block_comment:
            buf.append(ch)
            if ch == "*" and nxt == "/":
                buf.append(nxt)
                i += 2
                in_block_comment = False
                continue
            i += 1
            continue
        if dollar_tag:
            if sql.startswith(dollar_tag, i):
                buf.append(dollar_tag)
                i += len(dollar_tag)
                dollar_tag = None
                continue
            buf.append(ch)
            i += 1
            continue
        if in_single:
            buf.append(ch)
            if ch == "'":
                if nxt == "'":
                    buf.append(nxt)
                    i += 2
                    continue
                in_single = False
            i += 1
            continue
        if in_double:
            buf.append(ch)
            if ch == '"':
                in_double = False
            i += 1
            continue
        if ch == "-" and nxt == "-":
            in_line_comment = True
            buf.append(ch)
            buf.append(nxt)
            i += 2
            continue
        if ch == "/" and nxt == "*":
            in_block_comment = True
            buf.append(ch)
            buf.append(nxt)
            i += 2
            continue
        if ch == "'":
            in_single = True
            buf.append(ch)
            i += 1
            continue
        if ch == '"':
            in_double = True
            buf.append(ch)
            i += 1
            continue
        if ch == "$":
            m = re.match(r"\$[A-Za-z_][A-Za-z0-9_]*\$|\$\$", sql[i:])
            if m:
                dollar_tag = m.group(0)
                buf.append(dollar_tag)
                i += len(dollar_tag)
                continue
        if ch == ";":
            buf.append(ch)
            statement = "".join(buf).strip()
            if statement:
                statements.append(statement)
            buf = []
            i += 1
            continue
        buf.append(ch)
        i += 1
    tail = "".join(buf).strip()
    if tail:
        statements.append(tail)
    return statements

def strip_comments(stmt):
    # Good enough for target detection; statement splitting already preserved quoted semicolons.
    lines = []
    for line in stmt.splitlines():
        if line.strip().startswith("--"):
            continue
        lines.append(line)
    return "\n".join(lines)


def normalize_name(name):
    name = name.strip().strip('"')
    if "." in name:
        name = name.split(".")[-1].strip('"')
    return name


def area_for_name(name):
    simple = normalize_name(name)
    for prefix, area in PREFIX_TO_AREA.items():
        if simple.startswith(prefix):
            return area
    return None


def target_name(stmt):
    body = strip_comments(stmt)
    patterns = [
        r"\bSELECT\s+pg_catalog\.setval\(\'((?:public\.)?[A-Za-z0-9_\"]+)\'",
        r"\bCREATE\s+TABLE(?:\s+IF\s+NOT\s+EXISTS)?\s+((?:public\.)?[A-Za-z0-9_\"]+)",
        r"\bCREATE\s+SEQUENCE(?:\s+IF\s+NOT\s+EXISTS)?\s+((?:public\.)?[A-Za-z0-9_\"]+)",
        r"\bALTER\s+SEQUENCE\s+((?:public\.)?[A-Za-z0-9_\"]+)",
        r"\bCREATE\s+(?:UNIQUE\s+)?INDEX(?:\s+IF\s+NOT\s+EXISTS)?\s+[A-Za-z0-9_\"]+\s+ON\s+((?:public\.)?[A-Za-z0-9_\"]+)",
        r"\bALTER\s+TABLE(?:\s+ONLY)?\s+((?:public\.)?[A-Za-z0-9_\"]+)",
        r"\bINSERT\s+INTO\s+((?:public\.)?[A-Za-z0-9_\"]+)",
        r"\bUPDATE\s+((?:public\.)?[A-Za-z0-9_\"]+)",
        r"\bDELETE\s+FROM\s+((?:public\.)?[A-Za-z0-9_\"]+)",
        r"\bCOMMENT\s+ON\s+TABLE\s+((?:public\.)?[A-Za-z0-9_\"]+)",
        r"\bCOMMENT\s+ON\s+COLUMN\s+((?:public\.)?[A-Za-z0-9_\"]+)",
    ]
    for pat in patterns:
        m = re.search(pat, body, flags=re.I)
        if m:
            return normalize_name(m.group(1))
    # SELECT set_config / SET / comments are bootstrap-common.
    if re.match(r"\s*(SET|SELECT\s+pg_catalog\.set_config)\b", body, flags=re.I):
        return "sys__bootstrap"
    return None


def classify(stmt):
    target = target_name(stmt)
    if target is None:
        return "common"
    if target == "sys__bootstrap":
        return "common"
    area = area_for_name(target)
    if area:
        return area
    # App-code policy/config updates with no app-owned target still belong to common if they hit sys tables.
    if "sys_" in strip_comments(stmt):
        return "common"
    raise ValueError(f"Unable to classify statement target={target!r}: {stmt[:240]}")


def create_table_names(sql):
    return re.findall(r"CREATE\s+TABLE(?:\s+IF\s+NOT\s+EXISTS)?\s+(?:public\.)?([A-Za-z0-9_\"]+)", sql, flags=re.I)


def main():
    migrations = sorted(MIGRATION_DIR.glob("V*.sql"), key=migration_sort_key)
    if not migrations:
        print(f"No migrations found under {MIGRATION_DIR}", file=sys.stderr)
        return 1
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    buckets = {area: [] for area in OUTPUTS}
    source_counts = Counter()
    for path in migrations:
        text = path.read_text(encoding="utf-8", errors="ignore")
        for stmt in split_sql_statements(text):
            if re.search(r"SELECT\s+pg_catalog\.set_config\(\s*'search_path'\s*,\s*''\s*,\s*false\s*\)", stmt, flags=re.I):
                stmt = "SET search_path = public;"
            area = classify(stmt)
            source_counts[(area, path.name)] += 1
            buckets[area].append(f"-- source: {path.name}\n{stmt}")

    for area, filename in OUTPUTS.items():
        path = OUT_DIR / filename
        parts = [HEADER, f"-- Area: {area}", ""]
        parts.extend(buckets[area])
        path.write_text("\n\n".join(parts).rstrip() + "\n", encoding="utf-8")
        print(f"wrote {path} ({len(buckets[area])} statements, {len(create_table_names(path.read_text(encoding='utf-8')))} tables)")

    # Convenience combined file in execution order, still outside active migration path.
    combined = OUT_DIR / "V1__init.sql"
    combined.write_text(
        "\n\n".join([
            "-- Generated combined initialization SQL from the four area files.",
            "-- Source files are authoritative for organization; this is convenience output.",
            *(f"-- ============================================================================\n-- source file: {filename}\n-- ============================================================================\n" + (OUT_DIR / filename).read_text(encoding="utf-8") for filename in OUTPUTS.values()),
        ]).rstrip() + "\n",
        encoding="utf-8",
    )
    print(f"wrote {combined}")
    print("statement distribution:")
    for area in OUTPUTS:
        print(f"  {area}: {len(buckets[area])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
