-- saving App Store 字段映射、Paywall AB 策略与本机历史报告 Pro 增强。
-- 中文说明：本迁移只配置审核材料、转化文案与本机报告历史展示策略；不新增用户数据服务端存储，不开启云同步。

UPDATE public.sys_remote_config
SET status = 'inactive', updated_at = now()
WHERE app_code = 'saving'
  AND namespace_code IN (
    'saving_app_store_connect_field_mapping',
    'saving_paywall_ab_policy',
    'saving_report_history_pro_policy'
  );

INSERT INTO public.sys_remote_config (app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at)
VALUES
('saving', 'saving_app_store_connect_field_mapping', 'ios_submission_v1', '{"value":{"version":1,"bundleId":"com.savingsplanet.app","fields":[{"section":"App Information","field":"Name","value":"省省星球","source":"app metadata","manualVerify":true},{"section":"App Information","field":"Subtitle","value":"本机记账与省钱复盘","source":"metadata draft","manualVerify":true},{"section":"Privacy","field":"Tracking","value":"No","source":"saving_app_store_privacy_labels.tracking","manualVerify":true},{"section":"Privacy","field":"Data Linked to You","value":"Purchases, User ID","source":"saving_app_store_privacy_labels.dataLinkedToUser","manualVerify":true},{"section":"Privacy","field":"Financial Information","value":"Not Collected by backend; user records remain on device","source":"saving_app_store_privacy_labels.localOnlyData","manualVerify":true},{"section":"In-App Purchases","field":"Product ID","value":"com.savingsplanet.app.pro.monthly","source":"saving_entitlement_matrix / app-definition","manualVerify":true},{"section":"Review Notes","field":"Local-only explanation","value":"首发版本不上传记账明细，报告快照仅保存在本机。","source":"saving_app_review_materials.localOnly","manualVerify":false},{"section":"Review Notes","field":"Disclaimer","value":"报告仅用于个人记账复盘，不构成财务、投资、税务或法律建议。","source":"saving_app_review_materials.requiredPhrases","manualVerify":false}],"manualChecklist":["Apple Team ID 已填入 Xcode project 或 CI 配置","隐私政策 URL、服务条款 URL、支持 URL 均可访问","IAP 商品已在 App Store Connect 审核页关联","Sandbox 恢复购买路径已人工验证"],"opsNote":"该映射用于生成提交前核对表，不自动写入 App Store Connect。"}}', 'active', now(), now()),
('saving', 'saving_paywall_ab_policy', 'ios_v1', '{"value":{"version":1,"enabled":true,"assignment":"deterministic_local","legalNote":"价格与扣款以 Apple 系统弹窗为准；权益以后端校验为准。","triggers":{"default":{"defaultVariant":"balanced","variants":[{"code":"balanced","weight":70,"templateCode":"saving_default_v1","trustBullets":["免费版可继续记录基础数据。","Pro 解锁完整报告、趋势复盘与导出。","账号删除、恢复购买和法务入口对所有用户开放。"],"conversionCards":[{"code":"local_history","title":"本机历史报告","body":"周报/月报会保存在本机，方便之后回看。"},{"code":"advanced_review","title":"更完整复盘","body":"Pro 解锁分类结构、趋势复盘和 Top 省钱行为。"}]},{"code":"report_value","weight":30,"templateCode":"saving_report_value_v1","trustBullets":["先记录，后复盘，不承诺收益。","报告基于本机记录生成，不上传记账明细。"],"conversionCards":[{"code":"trend","title":"看见趋势","body":"用周报/月报发现更值得优化的消费习惯。"}]}]},"membership_center":{"defaultVariant":"balanced","variants":[{"code":"balanced","weight":100,"templateCode":"saving_member_center_v1","trustBullets":["订阅由 Apple 处理，可随时在系统中管理。","免费版仍可继续使用基础记录。"],"conversionCards":[{"code":"restore","title":"恢复购买清晰","body":"换机或重装后可在 App 内恢复购买。"}]}]},"report_locked":{"defaultVariant":"report_unlock","variants":[{"code":"report_unlock","weight":100,"templateCode":"saving_report_locked_v1","trustBullets":["免费版保留核心指标。","Pro 解锁完整报告模块。","报告仅用于个人记账复盘。"],"conversionCards":[{"code":"unlock_modules","title":"解锁高级模块","body":"分类结构、趋势复盘、高消费时段和 Top 省钱行为。"}]}]}}}}', 'active', now(), now()),
('saving', 'saving_report_history_pro_policy', 'ios_v1', '{"value":{"version":1,"enabled":true,"freePreviewLimit":3,"proTrendEnabled":true,"upgradeTrigger":"report_locked","localOnlyNotice":"高级历史趋势仍基于本机报告快照生成，不上传到后端。","proCards":[{"code":"history_trend","title":"历史趋势复盘","body":"基于本机周报/月报快照，查看总花费、总省下和净结果变化。","requiresPro":true},{"code":"category_memory","title":"分类记忆","body":"保留本机历史报告中的分类结构，帮助回顾长期习惯。","requiresPro":true}],"lockedTitle":"历史趋势已预留","lockedDescription":"免费版可查看最近报告快照；Pro 解锁更完整的本机历史趋势复盘。","opsNote":"该策略只控制 App 本机 UI，不开启云同步。"}}', 'active', now(), now());
