-- saving 提审清单、文档一致性门禁、细分 Paywall 触发点与本机历史趋势配置。
-- 中文说明：本迁移继续坚持首发 local-only：只配置 App Store 提审材料、法务口径、Paywall 转化策略和本机 UI 展示；不保存用户记账明细、不保存报告快照、不开启云同步。
-- 个人开发者低运维原则：所有提交材料都可由脚本从 DB seed 生成；外部 Apple/法务字段仍保留 manualVerify，避免脚本伪自动化造成审核风险。

UPDATE public.sys_remote_config
SET status = 'inactive', updated_at = now()
WHERE app_code = 'saving'
  AND namespace_code IN (
    'saving_app_store_submission_checklist',
    'saving_legal_document_consistency_policy',
    'saving_paywall_ab_policy',
    'saving_report_history_pro_policy'
  );

INSERT INTO public.sys_remote_config (app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at)
VALUES
('saving', 'saving_app_store_submission_checklist', 'ios_submission_v1', '{"value":{"version":1,"generatedDocumentTitle":"省省星球 App Store 提交清单","sections":[{"code":"metadata","title":"App Store Connect 元数据","items":["App 名称：省省星球","Subtitle：本机记账与省钱复盘","Description 需说明本机记账、周/月报和 Pro 权益，但不得承诺收益","Keywords 提交前人工确认，不堆砌竞品或金融高风险词"]},{"code":"privacy","title":"隐私与法务","items":["隐私政策 URL、服务条款 URL、支持 URL 均可访问","说明首发版本不上传记账明细","说明报告快照仅保存在本机","说明不构成财务、投资、税务或法律建议"]},{"code":"iap","title":"订阅与恢复购买","items":["IAP 商品 com.savingsplanet.app.pro.monthly 已创建并关联审核","App 内恢复购买入口可用","价格和扣款以 Apple 系统弹窗为准","Sandbox 购买、恢复、失败路径已人工验证"]},{"code":"reviewer","title":"审核员测试路径","items":["使用 Sign in with Apple 登录","新增一条花费和一条省钱记录","打开周报/月报，确认报告由本机记录生成","进入历史报告，确认本机历史和 Pro 锁定入口","进入设置删除账号，确认清理本机数据说明"]}],"requiredPhrases":["Sign in with Apple","Apple In-App Purchase","不上传记账明细","报告快照仅保存在本机","不构成财务、投资、税务或法律建议","删除账号"],"manualBlockers":["Apple Team ID / DEVELOPMENT_TEAM","App Store Connect IAP 审核关联","Sandbox 真机购买恢复验证","Xcode archive 与 TestFlight 上传"],"opsNote":"提交清单由 DB 配置生成，目的是减少漏项；Apple 后台字段仍需人工最终核对。"}}', 'active', now(), now()),
('saving', 'saving_legal_document_consistency_policy', 'ios_submission_v1', '{"value":{"version":1,"documentGlobs":["docs/app-store-*.md","docs/*subscription*.md","docs/*release*.md","qa/evidence/app-store/*.md"],"requiredPhrases":["不上传记账明细","Apple In-App Purchase","恢复购买","删除账号","不构成财务、投资、税务或法律建议"],"forbiddenPhrases":["稳赚","强制云同步","信用评分"],"localOnlyPhrases":["本机","不上传","后端不存储用户记账明细"],"opsNote":"文档一致性门禁只检查提审/说明文档口径，不读取用户数据。云同步未来如启用必须新增显式开关和隐私标签更新。"}}', 'active', now(), now()),
('saving', 'saving_paywall_ab_policy', 'ios_v1', '{"value":{"version":2,"enabled":true,"assignment":"deterministic_local","legalNote":"价格与扣款以 Apple 系统弹窗为准；权益以后端校验为准。","triggers":{"default":{"defaultVariant":"balanced","variants":[{"code":"balanced","weight":70,"templateCode":"saving_default_v1","trustBullets":["免费版可继续记录基础数据。","Pro 解锁完整报告、趋势复盘与导出。","账号删除、恢复购买和法务入口对所有用户开放。"],"conversionCards":[{"code":"local_history","title":"本机历史报告","body":"周报/月报会保存在本机，方便之后回看。"},{"code":"advanced_review","title":"更完整复盘","body":"Pro 解锁分类结构、趋势复盘和 Top 省钱行为。"}]},{"code":"report_value","weight":30,"templateCode":"saving_report_value_v1","trustBullets":["先记录，后复盘，不承诺收益。","报告基于本机记录生成，不上传记账明细。"],"conversionCards":[{"code":"trend","title":"看见趋势","body":"用周报/月报发现更值得优化的消费习惯。"}]}]},"membership_center":{"defaultVariant":"balanced","variants":[{"code":"balanced","weight":100,"templateCode":"saving_member_center_v1","trustBullets":["订阅由 Apple 处理，可随时在系统中管理。","免费版仍可继续使用基础记录。"],"conversionCards":[{"code":"restore","title":"恢复购买清晰","body":"换机或重装后可在 App 内恢复购买。"}]}]},"report_locked":{"defaultVariant":"report_unlock","variants":[{"code":"report_unlock","weight":100,"templateCode":"saving_report_locked_v1","trustBullets":["免费版保留核心指标。","Pro 解锁完整报告模块。","报告仅用于个人记账复盘。"],"conversionCards":[{"code":"unlock_modules","title":"解锁高级模块","body":"分类结构、趋势复盘、高消费时段和 Top 省钱行为。"}]}]},"history_trend_locked":{"defaultVariant":"history_value","variants":[{"code":"history_value","weight":100,"templateCode":"saving_history_trend_locked_v1","trustBullets":["历史趋势仅基于本机报告快照。","免费版可预览最近 3 份，Pro 查看完整本机历史。","不上传记账明细，不承诺收益。"],"conversionCards":[{"code":"long_term_review","title":"长期复盘更直观","body":"把周报/月报串起来，看总花费、总省下和净结果变化。"}]}]},"csv_export_locked":{"defaultVariant":"local_export","variants":[{"code":"local_export","weight":100,"templateCode":"saving_csv_export_locked_v1","trustBullets":["CSV 在设备端生成。","适合备份或自己做表格分析。","导出文件由用户主动分享或保存。"],"conversionCards":[{"code":"portable_records","title":"本机导出更自由","body":"Pro 解锁 CSV 导出，便于个人复盘和备份。"}]}]},"record_limit_reached":{"defaultVariant":"unlimited_records","variants":[{"code":"unlimited_records","weight":100,"templateCode":"saving_record_limit_v1","trustBullets":["免费版适合轻量记录。","Pro 解锁更高记录额度和完整报告。","记录仍优先保存在本机。"],"conversionCards":[{"code":"keep_tracking","title":"继续记录不断档","body":"当记录习惯养成后，Pro 帮你保留更完整的复盘链路。"}]}]}}}}', 'active', now(), now()),
('saving', 'saving_report_history_pro_policy', 'ios_v1', '{"value":{"version":2,"enabled":true,"freePreviewLimit":3,"proTrendEnabled":true,"upgradeTrigger":"history_trend_locked","trendMetricCodes":["expense","saved","net"],"localOnlyNotice":"高级历史趋势仍基于本机报告快照生成，不上传到后端。","freePreviewNotice":"免费版可预览最近 3 份本机报告快照；Pro 可查看完整本机历史趋势。","proCards":[{"code":"history_trend","title":"历史趋势复盘","body":"基于本机周报/月报快照，查看总花费、总省下和净结果变化。","requiresPro":true},{"code":"category_memory","title":"分类记忆","body":"保留本机历史报告中的分类结构，帮助回顾长期习惯。","requiresPro":true}],"lockedTitle":"历史趋势已预留","lockedDescription":"免费版可查看最近 3 份报告快照；Pro 解锁更完整的本机历史趋势复盘。","opsNote":"该策略只控制 App 本机 UI，不开启云同步。"}}', 'active', now(), now());

INSERT INTO public.sys_remote_config (app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at)
VALUES
('saving', 'saving_paywall', 'history_trend_locked', '{"value":{"trigger":"history_trend_locked","templateCode":"saving_history_trend_locked_v1","title":"解锁本机历史趋势","subtitle":"把周报/月报串起来，查看长期花费、省下和净结果变化。所有趋势仍基于本机快照生成。","recommendedPlanCode":"pro_monthly","ctaText":"解锁历史趋势","secondaryCtaText":"继续预览最近报告","plans":[{"planCode":"pro_monthly","storeProductId":"com.savingsplanet.app.pro.monthly","recommended":true,"trialEnabled":false,"benefitKeys":["advanced_report","trend_review","history_trend"]}]}}', 'active', now(), now()),
('saving', 'saving_paywall', 'csv_export_locked', '{"value":{"trigger":"csv_export_locked","templateCode":"saving_csv_export_locked_v1","title":"解锁本机 CSV 导出","subtitle":"导出文件在设备端生成，由你决定保存或分享；后端不存储导出内容。","recommendedPlanCode":"pro_monthly","ctaText":"解锁 CSV 导出","secondaryCtaText":"稍后再说","plans":[{"planCode":"pro_monthly","storeProductId":"com.savingsplanet.app.pro.monthly","recommended":true,"trialEnabled":false,"benefitKeys":["csv_export","unlimited_records","advanced_report"]}]}}', 'active', now(), now()),
('saving', 'saving_paywall', 'record_limit_reached', '{"value":{"trigger":"record_limit_reached","templateCode":"saving_record_limit_v1","title":"继续记录不断档","subtitle":"当记录习惯养成后，Pro 帮你保留更完整的本机复盘链路。","recommendedPlanCode":"pro_monthly","ctaText":"升级继续记录","secondaryCtaText":"先整理现有记录","plans":[{"planCode":"pro_monthly","storeProductId":"com.savingsplanet.app.pro.monthly","recommended":true,"trialEnabled":false,"benefitKeys":["unlimited_records","advanced_report","trend_review"]}]}}', 'active', now(), now());
