-- 统一后台式权益中心（模式三：老用户权益保护版）。
-- 中文说明：统一后端同时承载拍拍伴读、saving、FitMystery 等多个 App，权益配置必须按 app_code 隔离。
-- 设计目标：
-- 1) 免费权益按当前后台配置动态调整；
-- 2) 付费权益在有效期内保留购买时快照，后台降配不能影响已付款承诺；
-- 3) 新增/提升权益自动给有效期内老用户补齐；
-- 4) 人工赠送和用户级覆盖不要写 sys_entitlement_snapshot，避免被 App Store 刷新覆盖。

CREATE TABLE IF NOT EXISTS public.sys_membership_plan (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    plan_code varchar(64) NOT NULL,
    display_name varchar(128) NOT NULL,
    description varchar(512),
    plan_level integer DEFAULT 0 NOT NULL,
    entitlement_code varchar(64),
    status varchar(32) DEFAULT 'active' NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    metadata_json jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_membership_plan_app_plan ON public.sys_membership_plan(app_code, plan_code);
CREATE INDEX IF NOT EXISTS idx_sys_membership_plan_app_status ON public.sys_membership_plan(app_code, status);

CREATE TABLE IF NOT EXISTS public.sys_entitlement_feature (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    feature_code varchar(96) NOT NULL,
    feature_name varchar(128) NOT NULL,
    feature_type varchar(32) DEFAULT 'boolean' NOT NULL,
    description varchar(512),
    default_enabled boolean DEFAULT false NOT NULL,
    backend_enforced boolean DEFAULT false NOT NULL,
    frontend_visible boolean DEFAULT true NOT NULL,
    status varchar(32) DEFAULT 'active' NOT NULL,
    metadata_json jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_entitlement_feature_app_feature ON public.sys_entitlement_feature(app_code, feature_code);
CREATE INDEX IF NOT EXISTS idx_sys_entitlement_feature_app_status ON public.sys_entitlement_feature(app_code, status);

CREATE TABLE IF NOT EXISTS public.sys_plan_feature_rule (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    plan_code varchar(64) NOT NULL,
    feature_code varchar(96) NOT NULL,
    enabled boolean DEFAULT false NOT NULL,
    access_level varchar(32) DEFAULT 'none' NOT NULL,
    limit_value integer,
    limit_unit varchar(32),
    scope_code varchar(64),
    priority integer DEFAULT 0 NOT NULL,
    effective_start_at timestamp with time zone,
    effective_end_at timestamp with time zone,
    status varchar(32) DEFAULT 'active' NOT NULL,
    rule_json jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_plan_feature_rule_app_plan_feature ON public.sys_plan_feature_rule(app_code, plan_code, feature_code);
CREATE INDEX IF NOT EXISTS idx_sys_plan_feature_rule_app_plan ON public.sys_plan_feature_rule(app_code, plan_code, status);
CREATE INDEX IF NOT EXISTS idx_sys_plan_feature_rule_app_feature ON public.sys_plan_feature_rule(app_code, feature_code, status);

CREATE TABLE IF NOT EXISTS public.sys_product_entitlement_mapping (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    store_code varchar(32) DEFAULT 'appstore' NOT NULL,
    product_id varchar(128) NOT NULL,
    plan_code varchar(64),
    entitlement_code varchar(64) NOT NULL,
    product_type varchar(32) DEFAULT 'subscription' NOT NULL,
    status varchar(32) DEFAULT 'active' NOT NULL,
    metadata_json jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_product_entitlement_mapping_app_store_product ON public.sys_product_entitlement_mapping(app_code, store_code, product_id);
CREATE INDEX IF NOT EXISTS idx_sys_product_entitlement_mapping_app_entitlement ON public.sys_product_entitlement_mapping(app_code, entitlement_code, status);

CREATE TABLE IF NOT EXISTS public.sys_user_plan_snapshot (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    user_id bigint NOT NULL,
    plan_code varchar(64) NOT NULL,
    entitlement_code varchar(64),
    policy_version varchar(64) NOT NULL,
    source_type varchar(32) NOT NULL,
    source_ref varchar(128),
    status varchar(32) DEFAULT 'active' NOT NULL,
    starts_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expires_at timestamp with time zone,
    feature_snapshot_json jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sys_user_plan_snapshot_user ON public.sys_user_plan_snapshot(app_code, user_id, status);
CREATE INDEX IF NOT EXISTS idx_sys_user_plan_snapshot_entitlement ON public.sys_user_plan_snapshot(app_code, entitlement_code, status);
CREATE INDEX IF NOT EXISTS idx_sys_user_plan_snapshot_plan ON public.sys_user_plan_snapshot(app_code, plan_code, status);

CREATE TABLE IF NOT EXISTS public.sys_user_entitlement_grant (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    user_id bigint NOT NULL,
    grant_code varchar(96) NOT NULL,
    plan_code varchar(64),
    entitlement_code varchar(64),
    source_type varchar(32) DEFAULT 'manual' NOT NULL,
    source_ref varchar(128),
    status varchar(32) DEFAULT 'active' NOT NULL,
    starts_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expires_at timestamp with time zone,
    reason varchar(512),
    operator_user_id bigint,
    metadata_json jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sys_user_entitlement_grant_user ON public.sys_user_entitlement_grant(app_code, user_id, status);
CREATE INDEX IF NOT EXISTS idx_sys_user_entitlement_grant_entitlement ON public.sys_user_entitlement_grant(app_code, entitlement_code, status);

CREATE TABLE IF NOT EXISTS public.sys_user_feature_override (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    user_id bigint NOT NULL,
    feature_code varchar(96) NOT NULL,
    enabled boolean,
    access_level varchar(32),
    limit_value integer,
    limit_unit varchar(32),
    scope_code varchar(64),
    status varchar(32) DEFAULT 'active' NOT NULL,
    starts_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expires_at timestamp with time zone,
    reason varchar(512),
    operator_user_id bigint,
    metadata_json jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sys_user_feature_override_user ON public.sys_user_feature_override(app_code, user_id, status);
CREATE INDEX IF NOT EXISTS idx_sys_user_feature_override_feature ON public.sys_user_feature_override(app_code, feature_code, status);

CREATE TABLE IF NOT EXISTS public.sys_entitlement_policy_audit_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    operator_user_id bigint,
    operator_name varchar(128),
    action_type varchar(64) NOT NULL,
    target_type varchar(64) NOT NULL,
    target_key varchar(256) NOT NULL,
    before_json jsonb,
    after_json jsonb,
    request_id varchar(128),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sys_entitlement_policy_audit_app_created ON public.sys_entitlement_policy_audit_log(app_code, created_at DESC);

-- 会员等级：plan_code 是 App 内语义；entitlement_code 是统一计费内核投影出的可校验码。
INSERT INTO public.sys_membership_plan(app_code, plan_code, display_name, description, plan_level, entitlement_code, status, sort_order, metadata_json, created_at, updated_at)
VALUES
('paipai_readingcompanion','free','免费版','拍拍伴读免费基础权益',0,'free','active',0,'{}',now(),now()),
('paipai_readingcompanion','standard_single_child','标准版','单孩子订阅权益；有效期内购买快照保护历史承诺',10,'family_access','active',10,'{"badgeText":"标准版","mode3":"purchase_snapshot_protection"}',now(),now()),
('paipai_readingcompanion','family_multi_child_lifetime','家庭多孩子终身版','家庭多孩子终身权益',20,'family_multi_child','active',20,'{"badgeText":"家庭版","mode3":"purchase_snapshot_protection"}',now(),now()),
('saving','free','免费版','省钱项目免费基础权益',0,'free','active',0,'{}',now(),now()),
('saving','pro_monthly','Pro 月度版','省钱项目 Pro 订阅权益',10,'pro_access','active',10,'{"mode3":"purchase_snapshot_protection"}',now(),now()),
('fitmystery','free','免费版','FitMystery 免费基础权益',0,'free','active',0,'{}',now(),now()),
('fitmystery','pro_monthly','Pro 月度版','FitMystery Pro 报告和高级权益',10,'pro_access','active',10,'{"mode3":"purchase_snapshot_protection"}',now(),now())
ON CONFLICT (app_code, plan_code) DO UPDATE SET display_name=excluded.display_name, description=excluded.description, plan_level=excluded.plan_level, entitlement_code=excluded.entitlement_code, status=excluded.status, sort_order=excluded.sort_order, metadata_json=excluded.metadata_json, updated_at=now();

INSERT INTO public.sys_entitlement_feature(app_code, feature_code, feature_name, feature_type, default_enabled, backend_enforced, frontend_visible, status, metadata_json, created_at, updated_at)
VALUES
('paipai_readingcompanion','child_profile','孩子档案','quota',true,true,true,'active','{}',now(),now()),
('paipai_readingcompanion','daily_capture','每日拍读额度','quota',true,true,true,'active','{}',now(),now()),
('paipai_readingcompanion','local_card','本地句卡','quota',true,true,true,'active','{}',now(),now()),
('paipai_readingcompanion','cloud_sync','云同步','boolean',false,true,true,'active','{}',now(),now()),
('paipai_readingcompanion','advanced_voice','高级语音','boolean',false,true,true,'active','{}',now(),now()),
('paipai_readingcompanion','multi_child','多孩子','boolean',false,true,true,'active','{}',now(),now()),
('paipai_readingcompanion','weekly_report','周报模块','module',true,true,true,'active','{}',now(),now()),
('paipai_readingcompanion','weekly_report_history','历史周报','duration',false,true,true,'active','{}',now(),now()),
('paipai_readingcompanion','custom_reminder','自定义提醒','boolean',false,true,true,'active','{}',now(),now()),
('saving','monthly_records','每月记录数','quota',true,true,true,'active','{}',now(),now()),
('saving','advanced_report','高级报告','module',false,true,true,'active','{}',now(),now()),
('saving','trend_review','趋势复盘','module',false,true,true,'active','{}',now(),now()),
('saving','csv_export','CSV 导出','boolean',false,true,true,'active','{}',now(),now()),
('saving','history_trend','历史趋势','duration',false,true,true,'active','{}',now(),now()),
('fitmystery','report_access','报告生成','module',true,true,true,'active','{}',now(),now()),
('fitmystery','report_history','报告历史','duration',false,true,true,'active','{}',now(),now()),
('fitmystery','advanced_trend','高级趋势','module',false,true,true,'active','{}',now(),now()),
('fitmystery','export_report','报告导出','boolean',false,true,true,'active','{}',now(),now()),
('fitmystery','member_daily_bonus_chance','会员每日开盒奖励','quota',false,true,true,'active','{}',now(),now())
ON CONFLICT (app_code, feature_code) DO UPDATE SET feature_name=excluded.feature_name, feature_type=excluded.feature_type, default_enabled=excluded.default_enabled, backend_enforced=excluded.backend_enforced, frontend_visible=excluded.frontend_visible, status=excluded.status, metadata_json=excluded.metadata_json, updated_at=now();

INSERT INTO public.sys_plan_feature_rule(app_code, plan_code, feature_code, enabled, access_level, limit_value, limit_unit, scope_code, priority, status, rule_json, created_at, updated_at)
VALUES
-- Paipai free
('paipai_readingcompanion','free','child_profile',true,'limited',1,'count','account',10,'active','{}',now(),now()),
('paipai_readingcompanion','free','daily_capture',true,'limited',3,'day','single_child',20,'active','{}',now(),now()),
('paipai_readingcompanion','free','local_card',true,'limited',20,'count','account',30,'active','{}',now(),now()),
('paipai_readingcompanion','free','cloud_sync',false,'none',null,null,'account',40,'active','{}',now(),now()),
('paipai_readingcompanion','free','advanced_voice',false,'none',null,null,'account',50,'active','{}',now(),now()),
('paipai_readingcompanion','free','multi_child',false,'none',null,null,'account',60,'active','{}',now(),now()),
('paipai_readingcompanion','free','weekly_report',true,'limited',null,null,'child',70,'active','{}',now(),now()),
('paipai_readingcompanion','free','weekly_report_history',false,'none',0,'week_count','child',80,'active','{}',now(),now()),
('paipai_readingcompanion','free','custom_reminder',false,'none',null,null,'account',90,'active','{}',now(),now()),
-- Paipai standard
('paipai_readingcompanion','standard_single_child','child_profile',true,'limited',1,'count','account',10,'active','{}',now(),now()),
('paipai_readingcompanion','standard_single_child','daily_capture',true,'limited',20,'day','single_child',20,'active','{}',now(),now()),
('paipai_readingcompanion','standard_single_child','local_card',true,'limited',300,'count','account',30,'active','{}',now(),now()),
('paipai_readingcompanion','standard_single_child','cloud_sync',true,'full',null,null,'account',40,'active','{}',now(),now()),
('paipai_readingcompanion','standard_single_child','advanced_voice',true,'full',null,null,'account',50,'active','{}',now(),now()),
('paipai_readingcompanion','standard_single_child','multi_child',false,'none',null,null,'account',60,'active','{}',now(),now()),
('paipai_readingcompanion','standard_single_child','weekly_report',true,'full',null,null,'child',70,'active','{}',now(),now()),
('paipai_readingcompanion','standard_single_child','weekly_report_history',true,'full',4,'week_count','child',80,'active','{}',now(),now()),
('paipai_readingcompanion','standard_single_child','custom_reminder',false,'none',null,null,'account',90,'active','{}',now(),now()),
-- Paipai family lifetime
('paipai_readingcompanion','family_multi_child_lifetime','child_profile',true,'limited',5,'count','family',10,'active','{}',now(),now()),
('paipai_readingcompanion','family_multi_child_lifetime','daily_capture',true,'limited',50,'day','per_child',20,'active','{}',now(),now()),
('paipai_readingcompanion','family_multi_child_lifetime','local_card',true,'limited',800,'count','account',30,'active','{}',now(),now()),
('paipai_readingcompanion','family_multi_child_lifetime','cloud_sync',true,'full',null,null,'account',40,'active','{}',now(),now()),
('paipai_readingcompanion','family_multi_child_lifetime','advanced_voice',true,'full',null,null,'account',50,'active','{}',now(),now()),
('paipai_readingcompanion','family_multi_child_lifetime','multi_child',true,'full',null,null,'family',60,'active','{}',now(),now()),
('paipai_readingcompanion','family_multi_child_lifetime','weekly_report',true,'full',null,null,'family',70,'active','{}',now(),now()),
('paipai_readingcompanion','family_multi_child_lifetime','weekly_report_history',true,'full',12,'week_count','family',80,'active','{}',now(),now()),
('paipai_readingcompanion','family_multi_child_lifetime','custom_reminder',false,'none',null,null,'account',90,'active','{}',now(),now()),
-- Saving
('saving','free','monthly_records',true,'limited',100,'month','account',10,'active','{}',now(),now()),
('saving','free','advanced_report',false,'none',null,null,'account',20,'active','{}',now(),now()),
('saving','free','trend_review',false,'none',null,null,'account',30,'active','{}',now(),now()),
('saving','free','csv_export',false,'none',null,null,'account',40,'active','{}',now(),now()),
('saving','free','history_trend',false,'none',0,'month_count','account',50,'active','{}',now(),now()),
('saving','pro_monthly','monthly_records',true,'full',null,'month','account',10,'active','{}',now(),now()),
('saving','pro_monthly','advanced_report',true,'full',null,null,'account',20,'active','{}',now(),now()),
('saving','pro_monthly','trend_review',true,'full',null,null,'account',30,'active','{}',now(),now()),
('saving','pro_monthly','csv_export',true,'full',null,null,'account',40,'active','{}',now(),now()),
('saving','pro_monthly','history_trend',true,'full',24,'month_count','account',50,'active','{}',now(),now()),
-- FitMystery
('fitmystery','free','report_access',true,'limited',1,'initial_quota','account',10,'active','{}',now(),now()),
('fitmystery','free','report_history',false,'limited',1,'report_count','account',20,'active','{}',now(),now()),
('fitmystery','free','advanced_trend',false,'none',null,null,'account',30,'active','{}',now(),now()),
('fitmystery','free','export_report',false,'none',null,null,'account',40,'active','{}',now(),now()),
('fitmystery','free','member_daily_bonus_chance',false,'none',0,'day','account',50,'active','{}',now(),now()),
('fitmystery','pro_monthly','report_access',true,'full',null,'unlimited','account',10,'active','{}',now(),now()),
('fitmystery','pro_monthly','report_history',true,'full',24,'month_count','account',20,'active','{}',now(),now()),
('fitmystery','pro_monthly','advanced_trend',true,'full',null,null,'account',30,'active','{}',now(),now()),
('fitmystery','pro_monthly','export_report',true,'full',null,null,'account',40,'active','{}',now(),now()),
('fitmystery','pro_monthly','member_daily_bonus_chance',true,'limited',1,'day','account',50,'active','{}',now(),now())
ON CONFLICT (app_code, plan_code, feature_code) DO UPDATE SET enabled=excluded.enabled, access_level=excluded.access_level, limit_value=excluded.limit_value, limit_unit=excluded.limit_unit, scope_code=excluded.scope_code, priority=excluded.priority, status=excluded.status, rule_json=excluded.rule_json, updated_at=now();

INSERT INTO public.sys_product_entitlement_mapping(app_code, store_code, product_id, plan_code, entitlement_code, product_type, status, metadata_json, created_at, updated_at)
VALUES
('paipai_readingcompanion','appstore','com.paipai.readalong.family.monthly','standard_single_child','family_access','subscription','active','{}',now(),now()),
('paipai_readingcompanion','appstore','com.paipai.readalong.family.yearly','standard_single_child','family_access','subscription','active','{}',now(),now()),
('paipai_readingcompanion','appstore','com.paipai.readalong.family.multi_child.lifetime','family_multi_child_lifetime','family_multi_child','non_consumable','active','{}',now(),now()),
('saving','appstore','com.savingsplanet.app.pro.monthly','pro_monthly','pro_access','subscription','active','{}',now(),now()),
('fitmystery','appstore','com.fitmystery.pro.monthly','pro_monthly','pro_access','subscription','active','{}',now(),now()),
('fitmystery','appstore','com.fitmystery.pro.yearly','pro_monthly','pro_access','subscription','active','{}',now(),now()),
('fitmystery','appstore','com.fitmystery.box5',null,'box_chance_pack_5','consumable','active','{"grantChance":5}',now(),now()),
('fitmystery','appstore','com.fitmystery.box10',null,'box_chance_pack_10','consumable','active','{"grantChance":10}',now(),now()),
('fitmystery','appstore','com.fitmystery.box25',null,'box_chance_pack_25','consumable','active','{"grantChance":25}',now(),now())
ON CONFLICT (app_code, store_code, product_id) DO UPDATE SET plan_code=excluded.plan_code, entitlement_code=excluded.entitlement_code, product_type=excluded.product_type, status=excluded.status, metadata_json=excluded.metadata_json, updated_at=now();

-- 老用户补购买时快照：只补仍 active 且未过期的付费权益；过期记录不参与权益保护。
INSERT INTO public.sys_user_plan_snapshot(app_code, user_id, plan_code, entitlement_code, policy_version, source_type, source_ref, status, starts_at, expires_at, feature_snapshot_json, created_at, updated_at)
SELECT
    s.app_code,
    s.user_id,
    p.plan_code,
    s.entitlement_code,
    s.app_code || ':' || p.plan_code || ':mode3_backfill_20260428',
    'legacy_backfill',
    'sys_entitlement_snapshot:' || s.id,
    'active',
    COALESCE(s.created_at, now()),
    s.expires_at,
    jsonb_build_object(
        'version', s.app_code || ':' || p.plan_code || ':mode3_backfill_20260428',
        'planCode', p.plan_code,
        'entitlementCode', s.entitlement_code,
        'features', COALESCE((
            SELECT jsonb_object_agg(r.feature_code, jsonb_build_object(
                'enabled', r.enabled,
                'accessLevel', r.access_level,
                'limitValue', r.limit_value,
                'limitUnit', r.limit_unit,
                'scopeCode', r.scope_code,
                'source', 'legacy_backfill_current_rule'
            ))
            FROM public.sys_plan_feature_rule r
            WHERE r.app_code = p.app_code AND r.plan_code = p.plan_code AND r.status = 'active'
        ), '{}'::jsonb)
    ),
    now(),
    now()
FROM public.sys_entitlement_snapshot s
JOIN public.sys_membership_plan p
  ON p.app_code = s.app_code
 AND p.entitlement_code = s.entitlement_code
 AND p.status = 'active'
WHERE s.status = 'active'
  AND COALESCE(s.entitlement_code, '') <> 'free'
  AND (s.expires_at IS NULL OR s.expires_at > now())
  AND NOT EXISTS (
      SELECT 1 FROM public.sys_user_plan_snapshot existing
      WHERE existing.app_code = s.app_code
        AND existing.user_id = s.user_id
        AND existing.source_ref = 'sys_entitlement_snapshot:' || s.id
  );
