CREATE TABLE IF NOT EXISTS public.reading_cloud_service_usage_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code character varying(64) DEFAULT 'paipai_readingcompanion'::character varying NOT NULL,
    user_id bigint NOT NULL,
    service_type character varying(64) NOT NULL,
    delta integer NOT NULL,
    before_remaining integer NOT NULL,
    after_remaining integer NOT NULL,
    before_trial_used integer NOT NULL,
    after_trial_used integer NOT NULL,
    before_purchased_credits integer NOT NULL,
    after_purchased_credits integer NOT NULL,
    before_purchased_used integer NOT NULL,
    after_purchased_used integer NOT NULL,
    reason character varying(255) NOT NULL,
    operator_type character varying(32) NOT NULL,
    operator_id character varying(128),
    idempotency_key character varying(128),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_reading_cloud_usage_log_idempotency
    ON public.reading_cloud_service_usage_log(app_code, user_id, service_type, idempotency_key)
    WHERE idempotency_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_reading_cloud_usage_log_user_service_created
    ON public.reading_cloud_service_usage_log(user_id, service_type, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_reading_cloud_usage_user_service
    ON public.reading_cloud_service_usage(user_id, service_type);
