-- Draft migration for the common App Store payment/refund architecture.
-- Target database: PostgreSQL 14+.
-- This file is intentionally placed in backend/files as an implementation draft.
-- Review naming and backfill strategy before converting it into a Flyway migration.

BEGIN;

-- 1. Extend the existing transaction ledger.
ALTER TABLE public.sys_purchase_transaction
    ADD COLUMN IF NOT EXISTS order_no varchar(64),
    ADD COLUMN IF NOT EXISTS web_order_line_item_id varchar(128),
    ADD COLUMN IF NOT EXISTS app_transaction_id varchar(128),
    ADD COLUMN IF NOT EXISTS purchase_at timestamptz,
    ADD COLUMN IF NOT EXISTS original_purchase_at timestamptz,
    ADD COLUMN IF NOT EXISTS expires_at timestamptz,
    ADD COLUMN IF NOT EXISTS revocation_at timestamptz,
    ADD COLUMN IF NOT EXISTS revocation_reason varchar(64),
    ADD COLUMN IF NOT EXISTS revocation_type varchar(64),
    ADD COLUMN IF NOT EXISTS revocation_percentage integer,
    ADD COLUMN IF NOT EXISTS refund_status varchar(32) DEFAULT 'none' NOT NULL,
    ADD COLUMN IF NOT EXISTS product_type varchar(32),
    ADD COLUMN IF NOT EXISTS quantity integer DEFAULT 1 NOT NULL,
    ADD COLUMN IF NOT EXISTS price_milli_amount bigint,
    ADD COLUMN IF NOT EXISTS currency char(3),
    ADD COLUMN IF NOT EXISTS transaction_reason varchar(64),
    ADD COLUMN IF NOT EXISTS in_app_ownership_type varchar(64),
    ADD COLUMN IF NOT EXISTS app_account_token_hash varchar(128),
    ADD COLUMN IF NOT EXISTS app_account_token_ciphertext text,
    ADD COLUMN IF NOT EXISTS signed_transaction_info_ciphertext text,
    ADD COLUMN IF NOT EXISTS signed_renewal_info_ciphertext text,
    ADD COLUMN IF NOT EXISTS server_api_response_hash varchar(128),
    ADD COLUMN IF NOT EXISTS server_api_response_ciphertext text,
    ADD COLUMN IF NOT EXISTS pii_key_version varchar(64),
    ADD COLUMN IF NOT EXISTS idempotency_key varchar(160);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_purchase_transaction_app_tx
    ON public.sys_purchase_transaction (app_code, transaction_id)
    WHERE transaction_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_purchase_transaction_app_idempotency
    ON public.sys_purchase_transaction (app_code, idempotency_key)
    WHERE idempotency_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_sys_purchase_transaction_app_refund
    ON public.sys_purchase_transaction (app_code, refund_status, revocation_at DESC);

CREATE INDEX IF NOT EXISTS idx_sys_purchase_transaction_app_user_product_time
    ON public.sys_purchase_transaction (app_code, user_id, product_id, purchase_at DESC);

CREATE INDEX IF NOT EXISTS idx_sys_purchase_transaction_app_order
    ON public.sys_purchase_transaction (app_code, order_no, created_at DESC)
    WHERE order_no IS NOT NULL;

-- 2. Optional encrypted Apple identity link. Apple purchase transactions do not expose real Apple ID;
-- populate this table only from legitimate account identity flows such as Sign in with Apple.
CREATE TABLE IF NOT EXISTS public.sys_apple_identity_link (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    user_id bigint NOT NULL REFERENCES public.sys_user(id),
    apple_user_id_blind_index varchar(128),
    apple_user_id_ciphertext text,
    apple_email_blind_index varchar(128),
    apple_email_ciphertext text,
    apple_email_mask varchar(256),
    app_account_token_hash varchar(128),
    app_account_token_ciphertext text,
    consent_status varchar(32) DEFAULT 'unknown' NOT NULL,
    consent_policy_version varchar(64),
    pii_key_version varchar(64) NOT NULL,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_apple_identity_user
    ON public.sys_apple_identity_link (app_code, user_id)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_sys_apple_identity_apple_user
    ON public.sys_apple_identity_link (app_code, apple_user_id_blind_index)
    WHERE apple_user_id_blind_index IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_sys_apple_identity_email
    ON public.sys_apple_identity_link (app_code, apple_email_blind_index)
    WHERE apple_email_blind_index IS NOT NULL AND deleted_at IS NULL;

-- 3. Refund case lifecycle.
CREATE TABLE IF NOT EXISTS public.sys_appstore_refund_case (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    user_id bigint REFERENCES public.sys_user(id),
    order_no varchar(64),
    transaction_id varchar(128),
    original_transaction_id varchar(128) NOT NULL,
    product_id varchar(128),
    product_type varchar(32),
    notification_uuid varchar(128),
    refund_case_status varchar(32) DEFAULT 'requested' NOT NULL,
    consumption_request_id bigint,
    apple_refund_notification_uuid varchar(128),
    refund_requested_at timestamptz,
    refund_resolved_at timestamptz,
    revocation_at timestamptz,
    revocation_reason varchar(64),
    revocation_type varchar(64),
    revocation_percentage integer,
    purchase_price_milli_amount bigint,
    refund_amount_milli_estimated bigint,
    currency char(3),
    reason_code varchar(128),
    risk_label varchar(64),
    decision_code varchar(64),
    decision_message varchar(256),
    usage_count_used integer,
    usage_count_total integer,
    usage_ratio_milli integer,
    usage_ratio_threshold_milli integer,
    apple_refund_preference varchar(64),
    decision_context_json jsonb,
    metadata_json jsonb,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sys_appstore_refund_case_app_user
    ON public.sys_appstore_refund_case (app_code, user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_sys_appstore_refund_case_original_tx
    ON public.sys_appstore_refund_case (app_code, original_transaction_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_sys_appstore_refund_case_status
    ON public.sys_appstore_refund_case (app_code, refund_case_status, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_sys_appstore_refund_case_order
    ON public.sys_appstore_refund_case (app_code, order_no, created_at DESC)
    WHERE order_no IS NOT NULL;

-- 4. Consumption request response tasks.
CREATE TABLE IF NOT EXISTS public.sys_appstore_consumption_request (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    user_id bigint REFERENCES public.sys_user(id),
    notification_uuid varchar(128) NOT NULL,
    transaction_id varchar(128) NOT NULL,
    original_transaction_id varchar(128),
    product_id varchar(128),
    product_type varchar(32),
    apple_signed_date timestamptz,
    received_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deadline_at timestamptz NOT NULL,
    consent_status varchar(32) DEFAULT 'unknown' NOT NULL,
    reply_status varchar(32) DEFAULT 'pending' NOT NULL,
    delivery_status varchar(64),
    consumption_percentage integer,
    sample_content_provided boolean,
    refund_preference varchar(64),
    apple_request_payload_json jsonb,
    reply_context_json jsonb,
    attempt_count integer DEFAULT 0 NOT NULL,
    next_retry_at timestamptz,
    last_attempt_at timestamptz,
    last_http_status integer,
    last_error_code varchar(128),
    last_error_message varchar(1024),
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_appstore_consumption_notification
    ON public.sys_appstore_consumption_request (app_code, notification_uuid);

CREATE INDEX IF NOT EXISTS idx_sys_appstore_consumption_due
    ON public.sys_appstore_consumption_request (reply_status, next_retry_at, deadline_at);

-- 5. Refund decision audit log.
CREATE TABLE IF NOT EXISTS public.sys_refund_decision_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    user_id bigint REFERENCES public.sys_user(id),
    refund_case_id bigint,
    consumption_request_id bigint,
    order_no varchar(64),
    transaction_id varchar(128),
    original_transaction_id varchar(128),
    product_id varchar(128),
    lookup_input_json jsonb,
    ticket_snapshot_json jsonb,
    usage_count_used integer,
    usage_count_total integer,
    usage_ratio_milli integer,
    usage_ratio_threshold_milli integer,
    usage_snapshot_json jsonb,
    policy_snapshot_json jsonb,
    comparison_result_json jsonb,
    decision_code varchar(64) NOT NULL,
    display_message varchar(256),
    apple_refund_preference varchar(64),
    apple_payload_hash varchar(128),
    apple_payload_ciphertext text,
    apple_http_status integer,
    apple_response_ciphertext text,
    pii_key_version varchar(64),
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sys_refund_decision_log_case
    ON public.sys_refund_decision_log (app_code, refund_case_id, created_at DESC)
    WHERE refund_case_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_sys_refund_decision_log_tx
    ON public.sys_refund_decision_log (app_code, transaction_id, created_at DESC)
    WHERE transaction_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_sys_refund_decision_log_user
    ON public.sys_refund_decision_log (app_code, user_id, created_at DESC)
    WHERE user_id IS NOT NULL;

-- 6. Immutable entitlement ledger events.
CREATE TABLE IF NOT EXISTS public.sys_entitlement_ledger_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    user_id bigint NOT NULL REFERENCES public.sys_user(id),
    event_id uuid NOT NULL,
    event_type varchar(32) NOT NULL,
    entitlement_code varchar(96) NOT NULL,
    entitlement_token_id varchar(128),
    transaction_id varchar(128),
    original_transaction_id varchar(128),
    refund_case_id bigint,
    refund_status varchar(32) DEFAULT 'none' NOT NULL,
    refund_effect_type varchar(64),
    refunded_quantity integer DEFAULT 0 NOT NULL,
    refunded_at timestamptz,
    quantity_delta integer DEFAULT 0 NOT NULL,
    balance_before integer,
    balance_after integer,
    entitlement_version bigint NOT NULL,
    reason_code varchar(128),
    source_type varchar(64) NOT NULL,
    source_ref varchar(160),
    metadata_json jsonb,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_entitlement_ledger_event
    ON public.sys_entitlement_ledger_event (app_code, event_id);

CREATE INDEX IF NOT EXISTS idx_sys_entitlement_ledger_user
    ON public.sys_entitlement_ledger_event (app_code, user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_sys_entitlement_ledger_tx
    ON public.sys_entitlement_ledger_event (app_code, transaction_id)
    WHERE transaction_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_sys_entitlement_ledger_refund
    ON public.sys_entitlement_ledger_event (app_code, refund_status, refunded_at DESC)
    WHERE refund_status <> 'none';

-- 7. Client entitlement consumption reports.
CREATE TABLE IF NOT EXISTS public.sys_entitlement_consumption_report (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    user_id bigint NOT NULL REFERENCES public.sys_user(id),
    device_id_hash varchar(128),
    app_instance_id_hash varchar(128),
    event_id uuid NOT NULL,
    idempotency_key varchar(180) NOT NULL,
    event_type varchar(32) NOT NULL,
    entitlement_code varchar(96) NOT NULL,
    entitlement_token_id varchar(128),
    transaction_id varchar(128),
    original_transaction_id varchar(128),
    refund_case_id bigint,
    refund_status varchar(32) DEFAULT 'none' NOT NULL,
    refund_effect_type varchar(64),
    refunded_at timestamptz,
    counted_in_refund_decision boolean DEFAULT true NOT NULL,
    quantity integer DEFAULT 1 NOT NULL,
    client_entitlement_version bigint,
    server_entitlement_version bigint,
    local_created_at timestamptz,
    report_status varchar(32) DEFAULT 'accepted' NOT NULL,
    reject_code varchar(128),
    payload_json jsonb,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_entitlement_report_event
    ON public.sys_entitlement_consumption_report (app_code, user_id, event_id);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_entitlement_report_idempotency
    ON public.sys_entitlement_consumption_report (app_code, user_id, idempotency_key);

CREATE INDEX IF NOT EXISTS idx_sys_entitlement_report_user
    ON public.sys_entitlement_consumption_report (app_code, user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_sys_entitlement_report_refund
    ON public.sys_entitlement_consumption_report (app_code, refund_status, refunded_at DESC)
    WHERE refund_status <> 'none';

CREATE INDEX IF NOT EXISTS idx_sys_entitlement_report_tx
    ON public.sys_entitlement_consumption_report (app_code, transaction_id, created_at DESC)
    WHERE transaction_id IS NOT NULL;

-- 8. Monotonic entitlement version per user/app.
CREATE TABLE IF NOT EXISTS public.sys_entitlement_version_counter (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    user_id bigint NOT NULL REFERENCES public.sys_user(id),
    entitlement_version bigint DEFAULT 0 NOT NULL,
    last_reason_code varchar(128),
    last_source_type varchar(64),
    last_source_ref varchar(160),
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_entitlement_version_counter_user
    ON public.sys_entitlement_version_counter (app_code, user_id);

-- 9. APNs device token registry for entitlement refresh pushes.
CREATE TABLE IF NOT EXISTS public.sys_user_push_device (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    user_id bigint NOT NULL REFERENCES public.sys_user(id),
    device_id_hash varchar(128) NOT NULL,
    app_instance_id_hash varchar(128),
    platform varchar(32) DEFAULT 'ios' NOT NULL,
    push_provider varchar(32) DEFAULT 'apns' NOT NULL,
    push_environment varchar(32) NOT NULL,
    token_hash varchar(128) NOT NULL,
    token_ciphertext text NOT NULL,
    token_key_version varchar(64),
    locale varchar(32),
    app_version varchar(64),
    os_version varchar(64),
    status varchar(32) DEFAULT 'active' NOT NULL,
    last_registered_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_push_at timestamptz,
    last_push_status varchar(32),
    last_error_code varchar(128),
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_user_push_device
    ON public.sys_user_push_device (app_code, user_id, device_id_hash, push_environment);

CREATE INDEX IF NOT EXISTS idx_sys_user_push_device_user_status
    ON public.sys_user_push_device (app_code, user_id, status, updated_at DESC);

-- 10. Purchase limit policies and counters.
CREATE TABLE IF NOT EXISTS public.sys_purchase_limit_policy (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    product_id varchar(128),
    policy_scope varchar(32) DEFAULT 'user_product' NOT NULL,
    window_iso_duration varchar(32) DEFAULT 'P1D' NOT NULL,
    max_purchase_count integer,
    max_refund_count integer,
    max_refund_rate numeric(8,4),
    cooldown_minutes integer DEFAULT 0 NOT NULL,
    status varchar(32) DEFAULT 'active' NOT NULL,
    priority integer DEFAULT 0 NOT NULL,
    message_json jsonb,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sys_purchase_limit_policy_effective
    ON public.sys_purchase_limit_policy (app_code, product_id, status, priority DESC);

CREATE TABLE IF NOT EXISTS public.sys_purchase_limit_counter (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    user_id bigint NOT NULL REFERENCES public.sys_user(id),
    product_id varchar(128),
    window_start_at timestamptz NOT NULL,
    window_end_at timestamptz NOT NULL,
    purchase_count integer DEFAULT 0 NOT NULL,
    refund_count integer DEFAULT 0 NOT NULL,
    consumed_refund_count integer DEFAULT 0 NOT NULL,
    last_purchase_at timestamptz,
    last_refund_at timestamptz,
    cooldown_until_at timestamptz,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_purchase_limit_counter_window
    ON public.sys_purchase_limit_counter (app_code, user_id, product_id, window_start_at, window_end_at);

-- 11. Encrypted App Store interaction log.
CREATE TABLE IF NOT EXISTS public.sys_appstore_interaction_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    correlation_id varchar(128),
    direction varchar(16) NOT NULL,
    interaction_type varchar(64) NOT NULL,
    environment varchar(32),
    endpoint varchar(512),
    http_method varchar(16),
    http_status integer,
    notification_uuid varchar(128),
    transaction_id varchar(128),
    original_transaction_id varchar(128),
    user_id bigint,
    request_hash varchar(128),
    response_hash varchar(128),
    request_ciphertext text,
    response_ciphertext text,
    redacted_summary_json jsonb,
    pii_key_version varchar(64),
    error_code varchar(128),
    error_message varchar(1024),
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sys_appstore_interaction_app_time
    ON public.sys_appstore_interaction_log (app_code, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_sys_appstore_interaction_tx
    ON public.sys_appstore_interaction_log (app_code, transaction_id, created_at DESC)
    WHERE transaction_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_sys_appstore_interaction_notification
    ON public.sys_appstore_interaction_log (app_code, notification_uuid, created_at DESC)
    WHERE notification_uuid IS NOT NULL;

-- 12. Finance and risk daily metrics.
CREATE TABLE IF NOT EXISTS public.sys_finance_risk_daily (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    metric_date date NOT NULL,
    product_id varchar(128),
    storefront varchar(32),
    currency char(3),
    purchase_count integer DEFAULT 0 NOT NULL,
    refund_count integer DEFAULT 0 NOT NULL,
    gross_milli_amount bigint DEFAULT 0 NOT NULL,
    refund_milli_amount bigint DEFAULT 0 NOT NULL,
    net_milli_amount bigint DEFAULT 0 NOT NULL,
    refund_rate numeric(8,4),
    refund_amount_rate numeric(8,4),
    crash_free_session_rate numeric(8,4),
    avg_rating numeric(4,2),
    alert_level varchar(32),
    metadata_json jsonb,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_finance_risk_daily_dim
    ON public.sys_finance_risk_daily (app_code, metric_date, product_id, storefront, currency);

-- 13. Refund-friendly usage summary view for operations, finance, and support.
CREATE OR REPLACE VIEW public.v_sys_purchase_refund_usage_summary AS
SELECT
    t.app_code,
    t.user_id,
    t.order_no,
    t.product_id,
    t.product_type,
    t.transaction_id,
    t.original_transaction_id,
    t.purchase_at,
    t.refund_status AS purchase_refund_status,
    t.revocation_at,
    t.revocation_reason,
    t.revocation_percentage,
    COALESCE(SUM(CASE
        WHEN e.event_type IN ('grant', 'purchase_grant') THEN GREATEST(e.quantity_delta, 0)
        ELSE 0
    END), 0) AS total_entitlement_count,
    COALESCE(SUM(CASE
        WHEN e.event_type = 'consume' AND e.refund_status = 'none' THEN ABS(e.quantity_delta)
        ELSE 0
    END), 0) AS used_entitlement_count,
    COALESCE(SUM(CASE
        WHEN e.event_type = 'consume' AND e.refund_status <> 'none' THEN ABS(e.quantity_delta)
        ELSE 0
    END), 0) AS refunded_used_entitlement_count,
    COALESCE(BOOL_OR(COALESCE(e.refund_status, 'none') <> 'none'), false) AS has_refund_related_usage,
    MAX(e.refunded_at) AS last_usage_refunded_at
FROM public.sys_purchase_transaction t
LEFT JOIN public.sys_entitlement_ledger_event e
    ON e.app_code = t.app_code
   AND (
        (t.transaction_id IS NOT NULL AND e.transaction_id = t.transaction_id)
        OR (t.original_transaction_id IS NOT NULL AND e.original_transaction_id = t.original_transaction_id)
   )
GROUP BY
    t.app_code,
    t.user_id,
    t.order_no,
    t.product_id,
    t.product_type,
    t.transaction_id,
    t.original_transaction_id,
    t.purchase_at,
    t.refund_status,
    t.revocation_at,
    t.revocation_reason,
    t.revocation_percentage;

-- 14. Default dynamic refund policy. 10000 means 10.000%.
INSERT INTO public.sys_remote_config (
    app_code,
    namespace_code,
    config_key,
    config_value_json,
    status,
    created_at,
    updated_at
)
SELECT
    'paipai_readingcompanion',
    'billing_refund_policy',
    'usage_ratio_limit_milli',
    '{"value": 10000}'::jsonb,
    'active',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1
    FROM public.sys_remote_config
    WHERE app_code = 'paipai_readingcompanion'
      AND namespace_code = 'billing_refund_policy'
      AND config_key = 'usage_ratio_limit_milli'
      AND status = 'active'
);

COMMIT;
