-- Generated first-version initialization SQL grouped by ownership area.
-- Source: src/main/resources/db/migration/V*.sql
-- Generated by: scripts/split-db-migrations-into-four-init-files.py
-- IMPORTANT: this directory is not the active Flyway migration path unless explicitly wired later.

-- Area: fitmystery



-- source: V31__fitmystery_v1_core.sql
CREATE TABLE IF NOT EXISTS public.fit_activity_event (
    id UUID PRIMARY KEY,
    app_code VARCHAR(64) NOT NULL DEFAULT 'fitmystery',
    user_id BIGINT NOT NULL REFERENCES public.sys_user(id),
    idempotency_key VARCHAR(128) NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    source VARCHAR(32) NOT NULL,
    quantity NUMERIC(14,2) NOT NULL,
    unit VARCHAR(16) NOT NULL,
    event_date DATE NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    client_recorded_at TIMESTAMP WITH TIME ZONE,
    trust_level VARCHAR(32) NOT NULL DEFAULT 'normal',
    raw_payload_json TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'accepted',
    reject_reason VARCHAR(256),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_fit_activity_event_idem UNIQUE (app_code, user_id, idempotency_key),
    CONSTRAINT chk_fit_activity_event_type CHECK (event_type IN ('water','steps','exercise','weight')),
    CONSTRAINT chk_fit_activity_event_source CHECK (source IN ('manual','healthkit','system')),
    CONSTRAINT chk_fit_activity_event_quantity CHECK (quantity >= 0)
);

-- source: V31__fitmystery_v1_core.sql
CREATE INDEX IF NOT EXISTS idx_fit_activity_user_date ON public.fit_activity_event(app_code, user_id, event_date DESC);

-- source: V31__fitmystery_v1_core.sql
CREATE INDEX IF NOT EXISTS idx_fit_activity_user_type_date ON public.fit_activity_event(app_code, user_id, event_type, event_date DESC);

-- source: V31__fitmystery_v1_core.sql
CREATE TABLE IF NOT EXISTS public.fit_points_ledger (
    id UUID PRIMARY KEY,
    app_code VARCHAR(64) NOT NULL DEFAULT 'fitmystery',
    user_id BIGINT NOT NULL REFERENCES public.sys_user(id),
    ledger_type VARCHAR(32) NOT NULL,
    points_delta INTEGER NOT NULL,
    balance_after INTEGER NOT NULL,
    related_event_id UUID,
    related_draw_id UUID,
    idempotency_key VARCHAR(128) NOT NULL,
    reason_code VARCHAR(64) NOT NULL,
    note VARCHAR(256),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_fit_points_ledger_idem UNIQUE (app_code, user_id, idempotency_key),
    CONSTRAINT chk_fit_points_ledger_type CHECK (ledger_type IN ('earn','spend','adjust','expire'))
);

-- source: V31__fitmystery_v1_core.sql
CREATE INDEX IF NOT EXISTS idx_fit_points_user_created ON public.fit_points_ledger(app_code, user_id, created_at DESC);

-- source: V31__fitmystery_v1_core.sql
CREATE TABLE IF NOT EXISTS public.fit_daily_score_snapshot (
    id UUID PRIMARY KEY,
    app_code VARCHAR(64) NOT NULL DEFAULT 'fitmystery',
    user_id BIGINT NOT NULL REFERENCES public.sys_user(id),
    score_date DATE NOT NULL,
    water_ml NUMERIC(14,2) NOT NULL DEFAULT 0,
    steps INTEGER NOT NULL DEFAULT 0,
    exercise_minutes INTEGER NOT NULL DEFAULT 0,
    points_earned INTEGER NOT NULL DEFAULT 0,
    points_spent INTEGER NOT NULL DEFAULT 0,
    points_balance INTEGER NOT NULL DEFAULT 0,
    box_chance_balance INTEGER NOT NULL DEFAULT 0,
    calculated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_fit_daily_score UNIQUE (app_code, user_id, score_date)
);

-- source: V31__fitmystery_v1_core.sql
CREATE INDEX IF NOT EXISTS idx_fit_daily_score_user_date ON public.fit_daily_score_snapshot(app_code, user_id, score_date DESC);

-- source: V31__fitmystery_v1_core.sql
CREATE TABLE IF NOT EXISTS public.fit_draw_chance_ledger (
    id UUID PRIMARY KEY,
    app_code VARCHAR(64) NOT NULL DEFAULT 'fitmystery',
    user_id BIGINT NOT NULL REFERENCES public.sys_user(id),
    ledger_type VARCHAR(32) NOT NULL,
    chance_delta INTEGER NOT NULL,
    balance_after INTEGER NOT NULL,
    source_type VARCHAR(64) NOT NULL,
    source_id VARCHAR(128),
    idempotency_key VARCHAR(128) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_fit_draw_chance_idem UNIQUE (app_code, user_id, idempotency_key),
    CONSTRAINT chk_fit_draw_chance_type CHECK (ledger_type IN ('grant','consume','adjust','expire'))
);

-- source: V31__fitmystery_v1_core.sql
CREATE INDEX IF NOT EXISTS idx_fit_draw_chance_user_created ON public.fit_draw_chance_ledger(app_code, user_id, created_at DESC);

-- source: V31__fitmystery_v1_core.sql
CREATE TABLE IF NOT EXISTS public.fit_blind_box_pool (
    id UUID PRIMARY KEY,
    app_code VARCHAR(64) NOT NULL DEFAULT 'fitmystery',
    pool_code VARCHAR(64) NOT NULL,
    display_name VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    access_rule_json TEXT NOT NULL,
    probability_rule_json TEXT NOT NULL,
    odds_version VARCHAR(64) NOT NULL,
    odds_disclosure_json TEXT NOT NULL,
    no_cash_value_notice VARCHAR(256) NOT NULL DEFAULT 'Virtual collectible items only. No cash value. Not transferable or redeemable.',
    starts_at TIMESTAMP WITH TIME ZONE,
    ends_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_fit_pool_code UNIQUE (app_code, pool_code)
);

-- source: V31__fitmystery_v1_core.sql
CREATE TABLE IF NOT EXISTS public.fit_blind_box_item (
    id UUID PRIMARY KEY,
    app_code VARCHAR(64) NOT NULL DEFAULT 'fitmystery',
    item_code VARCHAR(64) NOT NULL,
    pool_code VARCHAR(64) NOT NULL,
    rarity VARCHAR(32) NOT NULL,
    display_name VARCHAR(128) NOT NULL,
    description TEXT,
    image_key VARCHAR(256),
    weight INTEGER NOT NULL DEFAULT 1,
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_fit_item_code UNIQUE (app_code, item_code),
    CONSTRAINT chk_fit_item_rarity CHECK (rarity IN ('common','rare','epic','legendary')),
    CONSTRAINT chk_fit_item_weight CHECK (weight >= 0)
);

-- source: V31__fitmystery_v1_core.sql
CREATE INDEX IF NOT EXISTS idx_fit_item_pool ON public.fit_blind_box_item(app_code, pool_code, status);

-- source: V31__fitmystery_v1_core.sql
CREATE TABLE IF NOT EXISTS public.fit_blind_box_draw (
    id UUID PRIMARY KEY,
    app_code VARCHAR(64) NOT NULL DEFAULT 'fitmystery',
    user_id BIGINT NOT NULL REFERENCES public.sys_user(id),
    pool_code VARCHAR(64) NOT NULL,
    item_code VARCHAR(64) NOT NULL,
    rarity VARCHAR(32) NOT NULL,
    consume_type VARCHAR(32) NOT NULL,
    points_spent INTEGER NOT NULL DEFAULT 0,
    chances_spent INTEGER NOT NULL DEFAULT 0,
    rng_version VARCHAR(64) NOT NULL,
    odds_version VARCHAR(64) NOT NULL,
    server_seed_hash VARCHAR(128),
    idempotency_key VARCHAR(128) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_fit_draw_idem UNIQUE (app_code, user_id, idempotency_key),
    CONSTRAINT chk_fit_draw_consume_type CHECK (consume_type IN ('points','chance','free'))
);

-- source: V31__fitmystery_v1_core.sql
CREATE INDEX IF NOT EXISTS idx_fit_draw_user_created ON public.fit_blind_box_draw(app_code, user_id, created_at DESC);

-- source: V31__fitmystery_v1_core.sql
CREATE TABLE IF NOT EXISTS public.fit_user_collection (
    id UUID PRIMARY KEY,
    app_code VARCHAR(64) NOT NULL DEFAULT 'fitmystery',
    user_id BIGINT NOT NULL REFERENCES public.sys_user(id),
    item_code VARCHAR(64) NOT NULL,
    first_draw_id UUID NOT NULL,
    first_obtained_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_obtained_at TIMESTAMP WITH TIME ZONE NOT NULL,
    obtain_count INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_fit_collection_user_item UNIQUE (app_code, user_id, item_code)
);

-- source: V31__fitmystery_v1_core.sql
CREATE INDEX IF NOT EXISTS idx_fit_collection_user ON public.fit_user_collection(app_code, user_id, updated_at DESC);

-- source: V31__fitmystery_v1_core.sql
CREATE TABLE IF NOT EXISTS public.fit_report_generation_ledger (
    id UUID PRIMARY KEY,
    app_code VARCHAR(64) NOT NULL DEFAULT 'fitmystery',
    user_id BIGINT NOT NULL REFERENCES public.sys_user(id),
    ledger_type VARCHAR(32) NOT NULL,
    report_type VARCHAR(32) NOT NULL,
    quota_delta INTEGER NOT NULL,
    balance_after INTEGER NOT NULL,
    source_type VARCHAR(64) NOT NULL,
    period_key VARCHAR(64),
    local_data_hash VARCHAR(128),
    idempotency_key VARCHAR(128) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_fit_report_generation_idem UNIQUE (app_code, user_id, idempotency_key),
    CONSTRAINT chk_fit_report_generation_type CHECK (ledger_type IN ('grant','consume','adjust','expire')),
    CONSTRAINT chk_fit_report_generation_report_type CHECK (report_type IN ('weekly','monthly','all'))
);

-- source: V31__fitmystery_v1_core.sql
CREATE INDEX IF NOT EXISTS idx_fit_report_generation_user_created ON public.fit_report_generation_ledger(app_code, user_id, created_at DESC);

-- source: V31__fitmystery_v1_core.sql
CREATE TABLE IF NOT EXISTS public.fit_account_deletion_request (
    id UUID PRIMARY KEY,
    app_code VARCHAR(64) NOT NULL DEFAULT 'fitmystery',
    user_id BIGINT NOT NULL REFERENCES public.sys_user(id),
    request_status VARCHAR(32) NOT NULL DEFAULT 'completed',
    deletion_scope VARCHAR(64) NOT NULL DEFAULT 'fitmystery_app_data',
    requested_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    note VARCHAR(256)
);

-- source: V31__fitmystery_v1_core.sql
CREATE INDEX IF NOT EXISTS idx_fit_account_deletion_user ON public.fit_account_deletion_request(app_code, user_id, requested_at DESC);

-- source: V31__fitmystery_v1_core.sql
INSERT INTO public.fit_blind_box_pool (id, app_code, pool_code, display_name, status, access_rule_json, probability_rule_json, odds_version, odds_disclosure_json, no_cash_value_notice, created_at, updated_at)
VALUES (
  gen_random_uuid(), 'fitmystery', 'starter_pool', '健康初心者', 'active',
  '{"requiredEntitlements":[]}',
  '{"version":"server_weighted_v1","note":"Server-side weighted RNG. Client never provides item or rarity."}',
  'starter_pool_odds_v1',
  '{"version":"starter_pool_odds_v1","poolCode":"starter_pool","noCashValueNotice":"仅获得 App 内虚拟收藏卡，无现金价值，不可交易、转让、提现或兑换实物。","rarityOdds":[{"rarity":"common","displayName":"普通","probability":"78.00%"},{"rarity":"rare","displayName":"稀有","probability":"17.00%"},{"rarity":"epic","displayName":"史诗","probability":"4.50%"},{"rarity":"legendary","displayName":"传说","probability":"0.50%"}],"pityRule":"首版不启用保底；后续如启用，需在本页展示触发条件。"}',
  '仅获得 App 内虚拟收藏卡，无现金价值，不可交易、转让、提现或兑换实物。', now(), now()
)
ON CONFLICT (app_code, pool_code) DO NOTHING;

-- source: V31__fitmystery_v1_core.sql
INSERT INTO public.fit_blind_box_item (id, app_code, item_code, pool_code, rarity, display_name, description, image_key, weight, status, created_at, updated_at)
VALUES
(gen_random_uuid(), 'fitmystery', 'card_water_001', 'starter_pool', 'common', '补水小星', '完成一次认真补水。', 'cards/water_001', 7800, 'active', now(), now()),
(gen_random_uuid(), 'fitmystery', 'card_steps_001', 'starter_pool', 'rare', '步履闪光', '今天也向前多走了一点。', 'cards/steps_001', 1700, 'active', now(), now()),
(gen_random_uuid(), 'fitmystery', 'card_exercise_001', 'starter_pool', 'epic', '燃动徽章', '运动让今日能量满格。', 'cards/exercise_001', 450, 'active', now(), now()),
(gen_random_uuid(), 'fitmystery', 'card_balance_001', 'starter_pool', 'legendary', '自律星环', '连续记录的高光时刻。', 'cards/balance_001', 50, 'active', now(), now())
ON CONFLICT (app_code, item_code) DO NOTHING;
