-- Generated first-version initialization SQL grouped by ownership area.
-- Source: src/main/resources/db/migration/V*.sql
-- Generated by: scripts/split-db-migrations-into-four-init-files.py
-- IMPORTANT: this directory is not the active Flyway migration path unless explicitly wired later.

-- Area: paipai



-- source: V1__init.sql
--
-- Name: reading_announcement; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reading_announcement (
    id bigint NOT NULL,
    app_code character varying(64) DEFAULT 'paipai_readingcompanion'::character varying NOT NULL,
    announcement_uuid character varying(64) NOT NULL,
    title character varying(256) NOT NULL,
    content text NOT NULL,
    status character varying(32) DEFAULT 'published'::character varying NOT NULL,
    visible_start_at timestamp with time zone NOT NULL,
    visible_end_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    announcement_type character varying(32),
    priority integer DEFAULT 0 NOT NULL,
    action_url character varying(512),
    action_text character varying(128),
    dismissible boolean DEFAULT true NOT NULL,
    max_display_count integer DEFAULT 1 NOT NULL,
    min_interval_seconds integer DEFAULT 86400 NOT NULL,
    trigger_scene character varying(64) DEFAULT 'app_launch'::character varying NOT NULL,
    target_locale character varying(32),
    target_plan_code character varying(64),
    target_min_app_version character varying(64),
    target_max_app_version character varying(64)
);

-- source: V1__init.sql
--
-- Name: reading_announcement_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.reading_announcement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- source: V1__init.sql
--
-- Name: reading_announcement_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.reading_announcement_id_seq OWNED BY public.reading_announcement.id;

-- source: V1__init.sql
--
-- Name: reading_child_profile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reading_child_profile (
    id character varying(64) NOT NULL,
    app_code character varying(64) DEFAULT 'paipai_readingcompanion'::character varying NOT NULL,
    user_id bigint NOT NULL,
    nickname character varying(128) NOT NULL,
    age_band character varying(32) NOT NULL,
    learning_track_code character varying(64) NOT NULL,
    avatar_emoji character varying(16) DEFAULT '🧸'::character varying NOT NULL,
    profile_status character varying(32) DEFAULT 'active'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp with time zone,
    last_modified_by_installation_id character varying(64),
    record_version integer DEFAULT 1 NOT NULL
);

-- source: V1__init.sql
--
-- Name: reading_child_usage_daily; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reading_child_usage_daily (
    id bigint NOT NULL,
    app_code character varying(64) DEFAULT 'paipai_readingcompanion'::character varying NOT NULL,
    user_id bigint NOT NULL,
    child_id character varying(64) NOT NULL,
    usage_date date NOT NULL,
    duration_seconds integer DEFAULT 0 NOT NULL,
    session_count integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V1__init.sql
--
-- Name: reading_child_usage_daily_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.reading_child_usage_daily_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- source: V1__init.sql
--
-- Name: reading_child_usage_daily_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.reading_child_usage_daily_id_seq OWNED BY public.reading_child_usage_daily.id;

-- source: V1__init.sql
--
-- Name: reading_cloud_service_usage; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reading_cloud_service_usage (
    id bigint NOT NULL,
    app_code character varying(64) DEFAULT 'paipai_readingcompanion'::character varying NOT NULL,
    user_id bigint NOT NULL,
    service_type character varying(64) NOT NULL,
    trial_limit integer NOT NULL,
    trial_used integer DEFAULT 0 NOT NULL,
    purchased_credits integer DEFAULT 0 NOT NULL,
    purchased_used integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V1__init.sql
--
-- Name: reading_cloud_service_usage_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.reading_cloud_service_usage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- source: V1__init.sql
--
-- Name: reading_cloud_service_usage_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.reading_cloud_service_usage_id_seq OWNED BY public.reading_cloud_service_usage.id;

-- source: V38__reading_cloud_usage_authoritative_log.sql

CREATE TABLE public.reading_cloud_service_usage_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code character varying(64) DEFAULT 'paipai_readingcompanion'::character varying NOT NULL,
    user_id bigint NOT NULL,
    service_type character varying(64) NOT NULL,
    delta integer NOT NULL,
    before_remaining integer NOT NULL,
    after_remaining integer NOT NULL,
    before_trial_used integer NOT NULL,
    after_trial_used integer NOT NULL,
    before_purchased_credits integer NOT NULL,
    after_purchased_credits integer NOT NULL,
    before_purchased_used integer NOT NULL,
    after_purchased_used integer NOT NULL,
    reason character varying(255) NOT NULL,
    operator_type character varying(32) NOT NULL,
    operator_id character varying(128),
    idempotency_key character varying(128),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V40__reading_internal_credit_products.sql

CREATE TABLE public.reading_cloud_service_credit_grant (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code character varying(64) DEFAULT 'paipai_readingcompanion'::character varying NOT NULL,
    user_id bigint NOT NULL,
    service_type character varying(64) NOT NULL,
    grant_type character varying(32) NOT NULL,
    total_count integer NOT NULL,
    used_count integer DEFAULT 0 NOT NULL,
    source_type character varying(64) NOT NULL,
    source_ref character varying(128),
    product_code character varying(128),
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_reading_credit_grant_count CHECK (total_count > 0 AND used_count >= 0 AND used_count <= total_count)
);

-- source: V39__reading_daily_quota_config.sql

CREATE TABLE public.reading_daily_quota_config (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code character varying(64) DEFAULT 'paipai_readingcompanion'::character varying NOT NULL,
    plan_code character varying(64) NOT NULL,
    feature_code character varying(64) NOT NULL,
    daily_limit integer NOT NULL,
    status character varying(32) DEFAULT 'active'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

INSERT INTO public.reading_daily_quota_config (app_code, plan_code, feature_code, daily_limit, status)
VALUES
    ('paipai_readingcompanion', 'free', 'capture', 5, 'active'),
    ('paipai_readingcompanion', 'free', 'speech', 10, 'active'),
    ('paipai_readingcompanion', 'free', 'cloud_ocr', 0, 'active'),
    ('paipai_readingcompanion', 'free', 'cloud_tts', 0, 'active'),
    ('paipai_readingcompanion', 'standard_single_child', 'capture', 50, 'active'),
    ('paipai_readingcompanion', 'standard_single_child', 'speech', 100, 'active'),
    ('paipai_readingcompanion', 'standard_single_child', 'cloud_ocr', 0, 'active'),
    ('paipai_readingcompanion', 'standard_single_child', 'cloud_tts', 0, 'active'),
    ('paipai_readingcompanion', 'family_multi_child_lifetime', 'capture', 50, 'active'),
    ('paipai_readingcompanion', 'family_multi_child_lifetime', 'speech', 100, 'active'),
    ('paipai_readingcompanion', 'family_multi_child_lifetime', 'cloud_ocr', 0, 'active'),
    ('paipai_readingcompanion', 'family_multi_child_lifetime', 'cloud_tts', 0, 'active');

-- source: V1__init.sql
--
-- Name: reading_daily_task_completion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reading_daily_task_completion (
    id bigint NOT NULL,
    app_code character varying(64) DEFAULT 'paipai_readingcompanion'::character varying NOT NULL,
    user_id bigint NOT NULL,
    child_id character varying(64),
    task_id character varying(128) NOT NULL,
    completion_type character varying(64) NOT NULL,
    task_date date NOT NULL,
    completed_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V1__init.sql
--
-- Name: reading_daily_task_completion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.reading_daily_task_completion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- source: V1__init.sql
--
-- Name: reading_daily_task_completion_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.reading_daily_task_completion_id_seq OWNED BY public.reading_daily_task_completion.id;

-- source: V1__init.sql
--
-- Name: reading_feedback_ticket; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reading_feedback_ticket (
    id bigint NOT NULL,
    app_code character varying(64) DEFAULT 'paipai_readingcompanion'::character varying NOT NULL,
    user_id bigint,
    ticket_no character varying(64) NOT NULL,
    category character varying(64) NOT NULL,
    content text NOT NULL,
    contact_email character varying(256),
    auth_mode character varying(64),
    trace_id character varying(128),
    status character varying(32) DEFAULT 'open'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V1__init.sql
--
-- Name: reading_feedback_ticket_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.reading_feedback_ticket_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- source: V1__init.sql
--
-- Name: reading_feedback_ticket_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.reading_feedback_ticket_id_seq OWNED BY public.reading_feedback_ticket.id;

-- source: V1__init.sql
--
-- Name: reading_ocr_audit; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reading_ocr_audit (
    id bigint NOT NULL,
    app_code character varying(64) DEFAULT 'paipai_readingcompanion'::character varying NOT NULL,
    user_id bigint,
    trace_id character varying(128) NOT NULL,
    provider character varying(64) NOT NULL,
    model character varying(64) NOT NULL,
    status character varying(64) NOT NULL,
    note character varying(512),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V1__init.sql
--
-- Name: reading_ocr_audit_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.reading_ocr_audit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- source: V1__init.sql
--
-- Name: reading_ocr_audit_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.reading_ocr_audit_id_seq OWNED BY public.reading_ocr_audit.id;

-- source: V1__init.sql
--
-- Name: reading_review_card; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reading_review_card (
    id character varying(64) NOT NULL,
    app_code character varying(64) DEFAULT 'paipai_readingcompanion'::character varying NOT NULL,
    user_id bigint NOT NULL,
    child_id character varying(64) NOT NULL,
    learning_track_code character varying(64) NOT NULL,
    encrypted_text text NOT NULL,
    text_preview character varying(256),
    support_hint character varying(512),
    proficiency integer DEFAULT 0 NOT NULL,
    next_review_at timestamp with time zone,
    sync_enabled boolean DEFAULT false NOT NULL,
    storage_mode character varying(32) DEFAULT 'server_authoritative'::character varying NOT NULL,
    card_status character varying(32) DEFAULT 'active'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    source_text text,
    translated_text text,
    source_language_code character varying(32),
    target_language_code character varying(32),
    source_type character varying(32),
    last_reviewed_at timestamp with time zone,
    deleted_at timestamp with time zone,
    last_modified_by_installation_id character varying(64),
    record_version integer DEFAULT 1 NOT NULL
);

-- source: V1__init.sql
--
-- Name: reading_review_event; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reading_review_event (
    id character varying(64) NOT NULL,
    app_code character varying(64) NOT NULL,
    user_id bigint NOT NULL,
    child_id character varying(64) NOT NULL,
    card_id character varying(64) NOT NULL,
    event_type character varying(32) NOT NULL,
    result_level character varying(32) NOT NULL,
    event_at timestamp with time zone NOT NULL,
    last_modified_by_installation_id character varying(64),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V1__init.sql
--
-- Name: reading_usage_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reading_usage_session (
    id character varying(64) NOT NULL,
    app_code character varying(64) NOT NULL,
    user_id bigint NOT NULL,
    child_id character varying(64) NOT NULL,
    source_page character varying(64) NOT NULL,
    started_at timestamp with time zone NOT NULL,
    ended_at timestamp with time zone,
    duration_seconds integer,
    client_platform character varying(32),
    device_model character varying(128),
    last_modified_by_installation_id character varying(64),
    deleted_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V1__init.sql
--
-- Name: reading_user_preference; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reading_user_preference (
    user_id bigint NOT NULL,
    app_code character varying(64) DEFAULT 'paipai_readingcompanion'::character varying NOT NULL,
    ui_locale character varying(32),
    source_language_code character varying(32),
    target_language_code character varying(32),
    reading_track_code character varying(64),
    tts_voice_code character varying(64),
    translation_mode character varying(32),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    cloud_sync_enabled boolean DEFAULT false NOT NULL,
    last_modified_by_installation_id character varying(64),
    record_version integer DEFAULT 1 NOT NULL
);

-- source: V1__init.sql
--
-- Name: reading_announcement id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_announcement ALTER COLUMN id SET DEFAULT nextval('public.reading_announcement_id_seq'::regclass);

-- source: V1__init.sql
--
-- Name: reading_child_usage_daily id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_child_usage_daily ALTER COLUMN id SET DEFAULT nextval('public.reading_child_usage_daily_id_seq'::regclass);

-- source: V1__init.sql
--
-- Name: reading_cloud_service_usage id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_cloud_service_usage ALTER COLUMN id SET DEFAULT nextval('public.reading_cloud_service_usage_id_seq'::regclass);

-- source: V1__init.sql
--
-- Name: reading_daily_task_completion id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_daily_task_completion ALTER COLUMN id SET DEFAULT nextval('public.reading_daily_task_completion_id_seq'::regclass);

-- source: V1__init.sql
--
-- Name: reading_feedback_ticket id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_feedback_ticket ALTER COLUMN id SET DEFAULT nextval('public.reading_feedback_ticket_id_seq'::regclass);

-- source: V1__init.sql
--
-- Name: reading_ocr_audit id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_ocr_audit ALTER COLUMN id SET DEFAULT nextval('public.reading_ocr_audit_id_seq'::regclass);

-- source: V1__init.sql
--
-- Name: reading_announcement reading_announcement_announcement_uuid_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_announcement
    ADD CONSTRAINT reading_announcement_announcement_uuid_key UNIQUE (announcement_uuid);

-- source: V1__init.sql
--
-- Name: reading_announcement reading_announcement_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_announcement
    ADD CONSTRAINT reading_announcement_pkey PRIMARY KEY (id);

-- source: V1__init.sql
--
-- Name: reading_child_profile reading_child_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_child_profile
    ADD CONSTRAINT reading_child_profile_pkey PRIMARY KEY (id);

-- source: V1__init.sql
--
-- Name: reading_child_usage_daily reading_child_usage_daily_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_child_usage_daily
    ADD CONSTRAINT reading_child_usage_daily_pkey PRIMARY KEY (id);

-- source: V1__init.sql
--
-- Name: reading_child_usage_daily reading_child_usage_daily_user_id_child_id_usage_date_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_child_usage_daily
    ADD CONSTRAINT reading_child_usage_daily_user_id_child_id_usage_date_key UNIQUE (user_id, child_id, usage_date);

-- source: V1__init.sql
--
-- Name: reading_cloud_service_usage reading_cloud_service_usage_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_cloud_service_usage
    ADD CONSTRAINT reading_cloud_service_usage_pkey PRIMARY KEY (id);

-- source: V1__init.sql
--
-- Name: reading_cloud_service_usage reading_cloud_service_usage_user_id_service_type_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_cloud_service_usage
    ADD CONSTRAINT reading_cloud_service_usage_user_id_service_type_key UNIQUE (user_id, service_type);

-- source: V39__reading_daily_quota_config.sql

ALTER TABLE ONLY public.reading_daily_quota_config
    ADD CONSTRAINT reading_daily_quota_config_plan_feature_key UNIQUE (app_code, plan_code, feature_code);

-- source: V1__init.sql
--
-- Name: reading_daily_task_completion reading_daily_task_completion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_daily_task_completion
    ADD CONSTRAINT reading_daily_task_completion_pkey PRIMARY KEY (id);

-- source: V1__init.sql
--
-- Name: reading_daily_task_completion reading_daily_task_completion_user_id_task_id_task_date_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_daily_task_completion
    ADD CONSTRAINT reading_daily_task_completion_user_id_task_id_task_date_key UNIQUE (user_id, task_id, task_date);

-- source: V1__init.sql
--
-- Name: reading_feedback_ticket reading_feedback_ticket_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_feedback_ticket
    ADD CONSTRAINT reading_feedback_ticket_pkey PRIMARY KEY (id);

-- source: V1__init.sql
--
-- Name: reading_feedback_ticket reading_feedback_ticket_ticket_no_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_feedback_ticket
    ADD CONSTRAINT reading_feedback_ticket_ticket_no_key UNIQUE (ticket_no);

-- source: V1__init.sql
--
-- Name: reading_ocr_audit reading_ocr_audit_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_ocr_audit
    ADD CONSTRAINT reading_ocr_audit_pkey PRIMARY KEY (id);

-- source: V1__init.sql
--
-- Name: reading_ocr_audit reading_ocr_audit_trace_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_ocr_audit
    ADD CONSTRAINT reading_ocr_audit_trace_id_key UNIQUE (trace_id);

-- source: V1__init.sql
--
-- Name: reading_review_card reading_review_card_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_review_card
    ADD CONSTRAINT reading_review_card_pkey PRIMARY KEY (id);

-- source: V1__init.sql
--
-- Name: reading_review_event reading_review_event_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_review_event
    ADD CONSTRAINT reading_review_event_pkey PRIMARY KEY (id);

-- source: V1__init.sql
--
-- Name: reading_usage_session reading_usage_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_usage_session
    ADD CONSTRAINT reading_usage_session_pkey PRIMARY KEY (id);

-- source: V1__init.sql
--
-- Name: reading_user_preference reading_user_preference_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_user_preference
    ADD CONSTRAINT reading_user_preference_pkey PRIMARY KEY (user_id);

-- source: V1__init.sql
--
-- Name: idx_reading_announcement_status_window; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reading_announcement_status_window ON public.reading_announcement USING btree (status, visible_start_at DESC, visible_end_at DESC);

-- source: V1__init.sql
--
-- Name: idx_reading_child_profile_user_deleted; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reading_child_profile_user_deleted ON public.reading_child_profile USING btree (user_id, deleted_at);

-- source: V1__init.sql
--
-- Name: idx_reading_child_profile_user_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reading_child_profile_user_status ON public.reading_child_profile USING btree (user_id, profile_status, updated_at DESC);

-- source: V1__init.sql
--
-- Name: idx_reading_child_profile_user_updated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reading_child_profile_user_updated ON public.reading_child_profile USING btree (user_id, updated_at DESC);

-- source: V1__init.sql
--
-- Name: idx_reading_child_usage_daily_app_user_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reading_child_usage_daily_app_user_date ON public.reading_child_usage_daily USING btree (app_code, user_id, usage_date);

-- source: V1__init.sql
--
-- Name: idx_reading_child_usage_daily_user_child_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reading_child_usage_daily_user_child_date ON public.reading_child_usage_daily USING btree (user_id, child_id, usage_date DESC);

-- source: V1__init.sql
--
-- Name: idx_reading_daily_task_completion_user_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reading_daily_task_completion_user_date ON public.reading_daily_task_completion USING btree (user_id, task_date DESC);

-- source: V1__init.sql
--
-- Name: idx_reading_feedback_ticket_user_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reading_feedback_ticket_user_created ON public.reading_feedback_ticket USING btree (user_id, created_at DESC);

-- source: V1__init.sql
--
-- Name: idx_reading_ocr_audit_user_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reading_ocr_audit_user_created ON public.reading_ocr_audit USING btree (user_id, created_at DESC);

-- source: V1__init.sql
--
-- Name: idx_reading_review_card_child_status_next_review; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reading_review_card_child_status_next_review ON public.reading_review_card USING btree (child_id, card_status, next_review_at);

-- source: V1__init.sql
--
-- Name: idx_reading_review_card_child_updated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reading_review_card_child_updated ON public.reading_review_card USING btree (child_id, updated_at DESC);

-- source: V1__init.sql
--
-- Name: idx_reading_review_card_user_deleted; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reading_review_card_user_deleted ON public.reading_review_card USING btree (user_id, deleted_at);

-- source: V1__init.sql
--
-- Name: idx_reading_review_card_user_next_review; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reading_review_card_user_next_review ON public.reading_review_card USING btree (user_id, next_review_at);

-- source: V1__init.sql
--
-- Name: idx_reading_review_card_user_status_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reading_review_card_user_status_created ON public.reading_review_card USING btree (user_id, card_status, created_at DESC);

-- source: V1__init.sql
--
-- Name: idx_reading_review_card_user_updated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reading_review_card_user_updated ON public.reading_review_card USING btree (user_id, updated_at DESC);

-- source: V1__init.sql
--
-- Name: idx_reading_review_event_card_event_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reading_review_event_card_event_at ON public.reading_review_event USING btree (card_id, event_at DESC);

-- source: V1__init.sql
--
-- Name: idx_reading_review_event_child_event_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reading_review_event_child_event_at ON public.reading_review_event USING btree (child_id, event_at DESC);

-- source: V1__init.sql
--
-- Name: idx_reading_review_event_user_event_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reading_review_event_user_event_at ON public.reading_review_event USING btree (user_id, event_at DESC);

-- source: V1__init.sql
--
-- Name: idx_reading_usage_session_app_user_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reading_usage_session_app_user_time ON public.reading_usage_session USING btree (app_code, user_id, COALESCE(ended_at, updated_at, started_at));

-- source: V1__init.sql
--
-- Name: idx_reading_usage_session_child_started; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reading_usage_session_child_started ON public.reading_usage_session USING btree (child_id, started_at DESC);

-- source: V1__init.sql
--
-- Name: idx_reading_usage_session_user_deleted; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reading_usage_session_user_deleted ON public.reading_usage_session USING btree (user_id, deleted_at);

-- source: V1__init.sql
--
-- Name: idx_reading_usage_session_user_started; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reading_usage_session_user_started ON public.reading_usage_session USING btree (user_id, started_at DESC);

-- source: V1__init.sql
--
-- Name: uk_reading_cloud_service_usage_user_service; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_reading_cloud_service_usage_user_service ON public.reading_cloud_service_usage USING btree (user_id, service_type);

-- source: V38__reading_cloud_usage_authoritative_log.sql

CREATE UNIQUE INDEX ux_reading_cloud_usage_log_idempotency ON public.reading_cloud_service_usage_log USING btree (app_code, user_id, service_type, idempotency_key) WHERE (idempotency_key IS NOT NULL);

-- source: V38__reading_cloud_usage_authoritative_log.sql

CREATE INDEX idx_reading_cloud_usage_log_user_service_created ON public.reading_cloud_service_usage_log USING btree (user_id, service_type, created_at DESC);

-- source: V38__reading_cloud_usage_authoritative_log.sql

CREATE INDEX idx_reading_cloud_usage_user_service ON public.reading_cloud_service_usage USING btree (user_id, service_type);

-- source: V40__reading_internal_credit_products.sql

CREATE UNIQUE INDEX ux_reading_credit_grant_source_ref
    ON public.reading_cloud_service_credit_grant(app_code, user_id, service_type, source_type, source_ref)
    WHERE source_ref IS NOT NULL;

CREATE INDEX idx_reading_credit_grant_user_service_active
    ON public.reading_cloud_service_credit_grant(app_code, user_id, service_type, expires_at, grant_type);

-- source: V39__reading_daily_quota_config.sql

CREATE INDEX idx_reading_daily_quota_config_status ON public.reading_daily_quota_config USING btree (app_code, status);

DELETE FROM public.reading_daily_quota_config
WHERE app_code = 'paipai_readingcompanion'
  AND plan_code = 'default';

-- source: V1__init.sql
--
-- Name: uq_reading_user_preference_app_user; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_reading_user_preference_app_user ON public.reading_user_preference USING btree (app_code, user_id);

-- source: V1__init.sql
--
-- Name: reading_child_profile reading_child_profile_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_child_profile
    ADD CONSTRAINT reading_child_profile_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.sys_user(id);

-- source: V1__init.sql
--
-- Name: reading_child_usage_daily reading_child_usage_daily_child_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_child_usage_daily
    ADD CONSTRAINT reading_child_usage_daily_child_id_fkey FOREIGN KEY (child_id) REFERENCES public.reading_child_profile(id);

-- source: V1__init.sql
--
-- Name: reading_child_usage_daily reading_child_usage_daily_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_child_usage_daily
    ADD CONSTRAINT reading_child_usage_daily_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.sys_user(id);

-- source: V1__init.sql
--
-- Name: reading_cloud_service_usage reading_cloud_service_usage_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_cloud_service_usage
    ADD CONSTRAINT reading_cloud_service_usage_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.sys_user(id);

-- source: V1__init.sql
--
-- Name: reading_daily_task_completion reading_daily_task_completion_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_daily_task_completion
    ADD CONSTRAINT reading_daily_task_completion_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.sys_user(id);

-- source: V1__init.sql
--
-- Name: reading_feedback_ticket reading_feedback_ticket_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_feedback_ticket
    ADD CONSTRAINT reading_feedback_ticket_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.sys_user(id);

-- source: V1__init.sql
--
-- Name: reading_ocr_audit reading_ocr_audit_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_ocr_audit
    ADD CONSTRAINT reading_ocr_audit_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.sys_user(id);

-- source: V1__init.sql
--
-- Name: reading_review_card reading_review_card_child_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_review_card
    ADD CONSTRAINT reading_review_card_child_id_fkey FOREIGN KEY (child_id) REFERENCES public.reading_child_profile(id);

-- source: V1__init.sql
--
-- Name: reading_review_card reading_review_card_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_review_card
    ADD CONSTRAINT reading_review_card_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.sys_user(id);

-- source: V1__init.sql
--
-- Name: reading_review_event reading_review_event_card_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_review_event
    ADD CONSTRAINT reading_review_event_card_id_fkey FOREIGN KEY (card_id) REFERENCES public.reading_review_card(id);

-- source: V1__init.sql
--
-- Name: reading_review_event reading_review_event_child_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_review_event
    ADD CONSTRAINT reading_review_event_child_id_fkey FOREIGN KEY (child_id) REFERENCES public.reading_child_profile(id);

-- source: V1__init.sql
--
-- Name: reading_review_event reading_review_event_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_review_event
    ADD CONSTRAINT reading_review_event_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.sys_user(id);

-- source: V1__init.sql
--
-- Name: reading_usage_session reading_usage_session_child_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_usage_session
    ADD CONSTRAINT reading_usage_session_child_id_fkey FOREIGN KEY (child_id) REFERENCES public.reading_child_profile(id);

-- source: V1__init.sql
--
-- Name: reading_usage_session reading_usage_session_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_usage_session
    ADD CONSTRAINT reading_usage_session_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.sys_user(id);

-- source: V1__init.sql
--
-- Name: reading_user_preference reading_user_preference_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reading_user_preference
    ADD CONSTRAINT reading_user_preference_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.sys_user(id);

-- source: V1__init.sql
--
-- Data for Name: reading_announcement; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.reading_announcement (id, app_code, announcement_uuid, title, content, status, visible_start_at, visible_end_at, created_at, updated_at, announcement_type, priority, action_url, action_text, dismissible, max_display_count, min_interval_seconds, trigger_scene, target_locale, target_plan_code, target_min_app_version, target_max_app_version) VALUES (1, 'paipai_readingcompanion', 'support-center-sample-20260422', '支持中心联调公告', '这是一条用于联调的支持中心公告，只会在支持与隐私页按场景、语言、版本和套餐命中后展示。', 'published', '2026-04-22 00:00:00+00', '2026-06-30 23:59:59+00', '2026-04-24 10:48:46.24271+00', '2026-04-24 10:48:46.254931+00', 'info', 5, 'https://www.paipai.app/help', '查看帮助', true, 1, 0, 'support_center', 'zh-Hans', 'family_multi_child_lifetime', '1.0.0', NULL);

-- source: V1__init.sql
INSERT INTO public.reading_announcement (id, app_code, announcement_uuid, title, content, status, visible_start_at, visible_end_at, created_at, updated_at, announcement_type, priority, action_url, action_text, dismissible, max_display_count, min_interval_seconds, trigger_scene, target_locale, target_plan_code, target_min_app_version, target_max_app_version) VALUES (2, 'paipai_readingcompanion', 'paipai-p1-launch-safe-start-20260424', '首发使用小提示', '拍拍伴读首发推荐每天从一句开始：拍一句、听一听、保存成句卡，明天回来复习。学习内容默认优先保存在本机；云同步由家长主动开启；家庭版权益与扣款金额以 App 内展示和 Apple 确认弹窗为准。', 'published', '2026-04-24 00:00:00+00', '2026-07-31 23:59:59+00', '2026-04-24 10:48:46.322486+00', '2026-04-24 10:48:46.322486+00', 'info', 20, NULL, NULL, true, 1, 86400, 'app_launch', 'zh-Hans', NULL, '1.0.0', NULL);

-- source: V1__init.sql
INSERT INTO public.reading_announcement (id, app_code, announcement_uuid, title, content, status, visible_start_at, visible_end_at, created_at, updated_at, announcement_type, priority, action_url, action_text, dismissible, max_display_count, min_interval_seconds, trigger_scene, target_locale, target_plan_code, target_min_app_version, target_max_app_version) VALUES (3, 'paipai_readingcompanion', 'paipai-p1-support-privacy-boundary-20260424', '家长安心说明', '相机和相册仅用于拍摄或选择绘本内容；账号删除、隐私政策、服务条款和儿童数据说明都可在 App 内查看。若遇到识别、朗读或购买恢复问题，请先保留当前 Apple 账号与订单状态，再联系 support@paipai.app。', 'published', '2026-04-24 00:00:00+00', '2026-07-31 23:59:59+00', '2026-04-24 10:48:46.326806+00', '2026-04-24 10:48:46.326806+00', 'info', 10, NULL, NULL, true, 2, 604800, 'support_center', 'zh-Hans', NULL, '1.0.0', NULL);

-- source: V1__init.sql
INSERT INTO public.reading_announcement (id, app_code, announcement_uuid, title, content, status, visible_start_at, visible_end_at, created_at, updated_at, announcement_type, priority, action_url, action_text, dismissible, max_display_count, min_interval_seconds, trigger_scene, target_locale, target_plan_code, target_min_app_version, target_max_app_version) VALUES (4, 'paipai_readingcompanion', 'paipai-p1-launch-reading-habit-20260504', '今日打卡提醒', '今天打开 App 后先完成一次拍句打卡：拍一句、听一句、存成句卡，连续记录会让复习更稳定。', 'published', '2026-05-04 00:00:00+08', '2026-08-31 23:59:59+08', '2026-05-04 09:00:00+08', '2026-05-04 09:00:00+08', 'activity', 30, NULL, NULL, true, 1, 86400, 'app_launch', 'zh-Hans', NULL, '1.0.0', NULL);

-- source: V1__init.sql
INSERT INTO public.reading_announcement (id, app_code, announcement_uuid, title, content, status, visible_start_at, visible_end_at, created_at, updated_at, announcement_type, priority, action_url, action_text, dismissible, max_display_count, min_interval_seconds, trigger_scene, target_locale, target_plan_code, target_min_app_version, target_max_app_version) VALUES (5, 'paipai_readingcompanion', 'paipai-p1-launch-parent-notice-20260504', '家长温馨提示', '相机、朗读、同步和购买恢复功能的使用说明都可以在支持与隐私页查看；如遇问题，先确认当前账号和网络状态，再联系官方支持。', 'published', '2026-05-04 00:00:00+08', '2026-08-31 23:59:59+08', '2026-05-04 09:00:00+08', '2026-05-04 09:00:00+08', 'info', 25, 'https://www.paipai.app/help', '查看帮助', true, 1, 86400, 'app_launch', 'zh-Hans', NULL, '1.0.0', NULL);

-- source: V1__init.sql
INSERT INTO public.reading_announcement (id, app_code, announcement_uuid, title, content, status, visible_start_at, visible_end_at, created_at, updated_at, announcement_type, priority, action_url, action_text, dismissible, max_display_count, min_interval_seconds, trigger_scene, target_locale, target_plan_code, target_min_app_version, target_max_app_version) VALUES (6, 'paipai_readingcompanion', 'paipai-notice-launch-usage-center-20260504', '通知公告已上线', '拍拍伴读现在会在家长中心集中展示当前有效的通知公告。启动弹窗按账号每天最多展示一次，错过弹窗也可以进入家长中心的“通知公告”栏目查看。', 'published', '2026-05-04 00:00:00+08', '2026-12-31 23:59:59+08', '2026-05-04 00:00:00+08', '2026-05-04 00:00:00+08', 'update', 30, NULL, NULL, true, 365, 86400, 'app_launch', 'zh-Hans', NULL, '1.0.0', NULL);

-- source: V1__init.sql
--
-- Data for Name: sys_sync_audit_log; Type: TABLE DATA; Schema: public; Owner: -
--


--
-- Data for Name: sys_sync_installation; Type: TABLE DATA; Schema: public; Owner: -
--


--
-- Data for Name: sys_user_device_event; Type: TABLE DATA; Schema: public; Owner: -
--


--
-- Data for Name: sys_user_identity; Type: TABLE DATA; Schema: public; Owner: -
--


--
-- Name: reading_announcement_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.reading_announcement_id_seq', 6, true);

-- source: V1__init.sql
--
-- Name: reading_child_usage_daily_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.reading_child_usage_daily_id_seq', 1, false);

-- source: V1__init.sql
--
-- Name: reading_cloud_service_usage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.reading_cloud_service_usage_id_seq', 1, false);

-- source: V1__init.sql
--
-- Name: reading_daily_task_completion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.reading_daily_task_completion_id_seq', 1, false);

-- source: V1__init.sql
--
-- Name: reading_feedback_ticket_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.reading_feedback_ticket_id_seq', 1, false);

-- source: V1__init.sql
--
-- Name: reading_ocr_audit_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.reading_ocr_audit_id_seq', 1, false);

-- source: V19__paipai_p1_privacy_and_weekly_snapshot.sql
-- paipai P1 隐私与周报历史升级。
-- 目标：降低儿童原文内容在云端明文留存风险；把历史周报升级为首次生成后复用的低运维快照。
-- 多 App 说明：所有新增数据仍带 app_code，后续其他 App 接入统一后端时必须独立 app_code 隔离。

ALTER TABLE reading_review_card
  ADD COLUMN IF NOT EXISTS content_encryption_version varchar(64),
  ADD COLUMN IF NOT EXISTS content_key_id varchar(128);

-- source: V19__paipai_p1_privacy_and_weekly_snapshot.sql
COMMENT ON COLUMN reading_review_card.encrypted_text IS '句卡正文密文或旧版编码值。P1 后 iOS 首选 enc:v1:aesgcm:keychain:*；后端不保存可解密密钥。';

-- source: V19__paipai_p1_privacy_and_weekly_snapshot.sql
COMMENT ON COLUMN reading_review_card.content_encryption_version IS '正文加密版本，例如 aesgcm_keychain_v1；用于后续密钥迁移或多设备加密方案演进。';

-- source: V19__paipai_p1_privacy_and_weekly_snapshot.sql
COMMENT ON COLUMN reading_review_card.content_key_id IS '客户端密钥标识。首发为本机 Keychain key id，不上传真实密钥，降低个人开发者密钥托管运维成本。';

-- source: V19__paipai_p1_privacy_and_weekly_snapshot.sql
CREATE TABLE IF NOT EXISTS reading_weekly_report_snapshot (
    id varchar(64) PRIMARY KEY,
    app_code varchar(64) DEFAULT 'paipai_readingcompanion' NOT NULL,
    user_id bigint NOT NULL,
    child_id varchar(64),
    scope varchar(32) NOT NULL,
    week_start date NOT NULL,
    week_end date NOT NULL,
    plan_code varchar(64) NOT NULL,
    tier varchar(32),
    payload_version integer DEFAULT 1 NOT NULL,
    report_payload_json text NOT NULL CHECK (report_payload_json::jsonb IS NOT NULL),
    report_status varchar(32) DEFAULT 'active' NOT NULL,
    generated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V19__paipai_p1_privacy_and_weekly_snapshot.sql
COMMENT ON TABLE reading_weekly_report_snapshot IS '拍拍伴读周报历史快照。首次访问历史周报时生成，后续复用，降低重复聚合成本并保持历史报告稳定。';

-- source: V19__paipai_p1_privacy_and_weekly_snapshot.sql
COMMENT ON COLUMN reading_weekly_report_snapshot.report_payload_json IS '聚合后的周报 JSON，只包含统计、建议、模块和免责声明，不存儿童原始句卡正文。字段用 text + JSON 校验，避免 MyBatis 字符串写入 jsonb 需要自定义类型处理，降低低运维成本。';

-- source: V19__paipai_p1_privacy_and_weekly_snapshot.sql
CREATE UNIQUE INDEX IF NOT EXISTS uk_reading_weekly_report_snapshot_scope
ON reading_weekly_report_snapshot (app_code, user_id, scope, COALESCE(child_id, '__family__'), week_start, plan_code)
WHERE report_status = 'active';

-- source: V19__paipai_p1_privacy_and_weekly_snapshot.sql
CREATE INDEX IF NOT EXISTS idx_reading_weekly_report_snapshot_user_week
ON reading_weekly_report_snapshot (app_code, user_id, week_start DESC, updated_at DESC);

-- source: V19__paipai_p1_privacy_and_weekly_snapshot.sql
CREATE INDEX IF NOT EXISTS idx_reading_review_card_user_child_created
ON reading_review_card (user_id, child_id, created_at DESC);

-- source: V19__paipai_p1_privacy_and_weekly_snapshot.sql
CREATE INDEX IF NOT EXISTS idx_reading_review_card_encryption_version
ON reading_review_card (app_code, content_encryption_version);

-- source: V42__reading_review_card_language_index.sql
CREATE INDEX IF NOT EXISTS idx_reading_review_card_user_language_created
ON reading_review_card (app_code, user_id, source_language_code, target_language_code, created_at DESC)
WHERE deleted_at IS NULL;


CREATE TABLE IF NOT EXISTS public.sys_compensation_code (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    compensation_code varchar(64) NOT NULL,
    code_hash varchar(128) NOT NULL,
    benefit_type varchar(32) NOT NULL,
    plan_code varchar(64),
    entitlement_code varchar(64),
    service_type varchar(64),
    grant_count integer DEFAULT 1 NOT NULL,
    grant_valid_days integer,
    expires_at timestamp with time zone,
    max_uses integer DEFAULT 1 NOT NULL,
    used_count integer DEFAULT 0 NOT NULL,
    status varchar(32) DEFAULT 'unused' NOT NULL,
    used_by_user_id bigint,
    used_at timestamp with time zone,
    void_reason varchar(512),
    metadata_json jsonb,
    created_by_user_id bigint,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_compensation_code_app_code ON public.sys_compensation_code(app_code, compensation_code);
CREATE INDEX IF NOT EXISTS idx_sys_compensation_code_app_status_expiry ON public.sys_compensation_code(app_code, status, expires_at DESC);
CREATE INDEX IF NOT EXISTS idx_sys_compensation_code_app_benefit ON public.sys_compensation_code(app_code, benefit_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sys_compensation_code_app_used_by ON public.sys_compensation_code(app_code, used_by_user_id, used_at DESC);

CREATE TABLE IF NOT EXISTS public.sys_user_compensation_record (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    user_id bigint NOT NULL,
    compensation_code_id bigint NOT NULL,
    compensation_code varchar(64) NOT NULL,
    benefit_type varchar(32) NOT NULL,
    benefit_summary varchar(512) NOT NULL,
    plan_code varchar(64),
    entitlement_code varchar(64),
    service_type varchar(64),
    grant_count integer DEFAULT 1 NOT NULL,
    redeem_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    valid_until_at timestamp with time zone,
    status varchar(32) DEFAULT 'applied' NOT NULL,
    result_message varchar(512),
    before_json jsonb,
    after_json jsonb,
    metadata_json jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_user_compensation_record_app_code ON public.sys_user_compensation_record(app_code, compensation_code);
CREATE INDEX IF NOT EXISTS idx_sys_user_compensation_record_user_created ON public.sys_user_compensation_record(app_code, user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sys_user_compensation_record_code_created ON public.sys_user_compensation_record(app_code, compensation_code_id, created_at DESC);

ALTER TABLE ONLY public.sys_compensation_code
    ADD CONSTRAINT sys_compensation_code_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.sys_user(id);

ALTER TABLE ONLY public.sys_compensation_code
    ADD CONSTRAINT sys_compensation_code_used_by_user_id_fkey FOREIGN KEY (used_by_user_id) REFERENCES public.sys_user(id);

ALTER TABLE ONLY public.sys_user_compensation_record
    ADD CONSTRAINT sys_user_compensation_record_compensation_code_id_fkey FOREIGN KEY (compensation_code_id) REFERENCES public.sys_compensation_code(id);

ALTER TABLE ONLY public.sys_user_compensation_record
    ADD CONSTRAINT sys_user_compensation_record_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.sys_user(id);
