-- Generated first-version initialization SQL grouped by ownership area.
-- Source: src/main/resources/db/migration/V*.sql
-- Generated by: scripts/split-db-migrations-into-four-init-files.py
-- IMPORTANT: this directory is not the active Flyway migration path unless explicitly wired later.

-- Area: saving



-- source: V20__saving_launch_compat.sql
-- Saving / SaveMoney first-release compatibility layer.
-- Tables are prefixed with saving_ and all rows are scoped by sys_user.id to avoid affecting other apps.

CREATE TABLE IF NOT EXISTS public.saving_expense_record (
    id UUID PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.sys_user(id),
    amount NUMERIC(14,2) NOT NULL,
    currency VARCHAR(8) NOT NULL DEFAULT 'CNY',
    category_code VARCHAR(64) NOT NULL,
    category_name VARCHAR(128),
    merchant_name VARCHAR(128),
    note TEXT,
    source VARCHAR(32) NOT NULL DEFAULT 'ios',
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_saving_expense_amount_positive CHECK (amount > 0)
);

-- source: V20__saving_launch_compat.sql
CREATE INDEX IF NOT EXISTS idx_saving_expense_user_occurred ON public.saving_expense_record(user_id, occurred_at DESC);

-- source: V20__saving_launch_compat.sql
CREATE INDEX IF NOT EXISTS idx_saving_expense_user_category ON public.saving_expense_record(user_id, category_code);

-- source: V20__saving_launch_compat.sql
CREATE TABLE IF NOT EXISTS public.saving_saving_record (
    id UUID PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.sys_user(id),
    amount NUMERIC(14,2) NOT NULL,
    currency VARCHAR(8) NOT NULL DEFAULT 'CNY',
    saving_type VARCHAR(32) NOT NULL,
    category_code VARCHAR(64) NOT NULL,
    category_name VARCHAR(128),
    scenario VARCHAR(128),
    note TEXT,
    source VARCHAR(32) NOT NULL DEFAULT 'ios',
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_saving_saving_amount_positive CHECK (amount > 0),
    CONSTRAINT chk_saving_saving_type CHECK (saving_type IN ('confirmed', 'avoided'))
);

-- source: V20__saving_launch_compat.sql
CREATE INDEX IF NOT EXISTS idx_saving_saving_user_occurred ON public.saving_saving_record(user_id, occurred_at DESC);

-- source: V20__saving_launch_compat.sql
CREATE INDEX IF NOT EXISTS idx_saving_saving_user_category ON public.saving_saving_record(user_id, category_code);

-- source: V20__saving_launch_compat.sql
CREATE INDEX IF NOT EXISTS idx_saving_saving_user_type ON public.saving_saving_record(user_id, saving_type);
