-- Generated first-version initialization SQL grouped by ownership area.
-- Source: src/main/resources/db/migration/V*.sql
-- Generated by: scripts/split-db-migrations-into-four-init-files.py
-- IMPORTANT: this directory is not the active Flyway migration path unless explicitly wired later.

-- Area: common



-- source: V1__init.sql
-- AppHub / Paipai unified database initialization.
--
-- This file intentionally squashes the former V1..V19 Flyway migrations into a
-- single fresh-database baseline. Paipai is currently the first shipping app, so
-- keeping one initialization script avoids migration drift while preserving the
-- final schema, indexes, constraints, default app_code values, and seed configs
-- required by the current backend code.
--
-- Important: use this baseline for new databases. Existing databases that have
-- already applied the old multi-file migration chain need an explicit reset or
-- Flyway repair strategy before switching to this squashed baseline.

SET TIME ZONE 'UTC';

-- source: V1__init.sql
--
--


SET statement_timeout = 0;

-- source: V1__init.sql
SET lock_timeout = 0;

-- source: V1__init.sql
SET idle_in_transaction_session_timeout = 0;

-- source: V1__init.sql
SET client_encoding = 'UTF8';

-- source: V1__init.sql
SET standard_conforming_strings = on;

-- source: V1__init.sql
SET search_path = public;

-- source: V1__init.sql
SET check_function_bodies = false;

-- source: V1__init.sql
SET xmloption = content;

-- source: V1__init.sql
SET client_min_messages = warning;

-- source: V1__init.sql
SET row_security = off;

-- source: V1__init.sql
SET default_tablespace = '';

-- source: V1__init.sql
SET default_table_access_method = heap;

-- source: V1__init.sql
--
-- Name: sys_app; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sys_app (
    app_code character varying(64) NOT NULL,
    app_name character varying(128) NOT NULL,
    status character varying(32) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V1__init.sql
--
-- Name: sys_app_store_notification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sys_app_store_notification (
    id bigint NOT NULL,
    app_code character varying(64) NOT NULL,
    notification_uuid character varying(128) NOT NULL,
    notification_type character varying(128),
    subtype character varying(128),
    signed_payload_hash character varying(128) NOT NULL,
    verification_status character varying(32) DEFAULT 'pending'::character varying NOT NULL,
    processing_status character varying(32) DEFAULT 'accepted'::character varying NOT NULL,
    raw_payload_json jsonb NOT NULL,
    received_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V1__init.sql
--
-- Name: sys_app_store_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sys_app_store_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- source: V1__init.sql
--
-- Name: sys_app_store_notification_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sys_app_store_notification_id_seq OWNED BY public.sys_app_store_notification.id;

-- source: V1__init.sql
--
-- Name: sys_audit_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sys_audit_log (
    id bigint NOT NULL,
    app_code character varying(64) NOT NULL,
    operator_type character varying(32) NOT NULL,
    operator_id character varying(128),
    action_code character varying(128) NOT NULL,
    trace_id character varying(128),
    payload_json jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V1__init.sql
--
-- Name: sys_audit_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sys_audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- source: V1__init.sql
--
-- Name: sys_audit_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sys_audit_log_id_seq OWNED BY public.sys_audit_log.id;

-- source: V1__init.sql
--
-- Name: sys_auth_provider_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sys_auth_provider_token (
    id bigint NOT NULL,
    app_code character varying(64) NOT NULL,
    user_id bigint NOT NULL,
    provider_code character varying(32) NOT NULL,
    provider_subject character varying(256) NOT NULL,
    refresh_token text,
    access_token text,
    token_type character varying(64),
    status character varying(32) DEFAULT 'active'::character varying NOT NULL,
    payload_json jsonb,
    refresh_token_key_id character varying(64),
    refresh_token_encryption_algorithm character varying(64),
    refresh_token_nonce_base64 text,
    refresh_token_ciphertext_base64 text,
    refresh_token_last_captured_at timestamp with time zone,
    refresh_token_last_used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V1__init.sql
--
-- Name: sys_auth_provider_token_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sys_auth_provider_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- source: V1__init.sql
--
-- Name: sys_auth_provider_token_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sys_auth_provider_token_id_seq OWNED BY public.sys_auth_provider_token.id;

-- source: V1__init.sql
--
-- Name: sys_auth_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sys_auth_session (
    id bigint NOT NULL,
    app_code character varying(64) NOT NULL,
    user_id bigint NOT NULL,
    session_token_hash character varying(128) NOT NULL,
    session_source character varying(32) NOT NULL,
    device_id character varying(128),
    client_platform character varying(32),
    client_version character varying(64),
    status character varying(32) DEFAULT 'active'::character varying NOT NULL,
    expires_at timestamp with time zone,
    revoked_at timestamp with time zone,
    last_seen_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V1__init.sql
--
-- Name: sys_auth_session_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sys_auth_session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- source: V1__init.sql
--
-- Name: sys_auth_session_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sys_auth_session_id_seq OWNED BY public.sys_auth_session.id;

-- source: V1__init.sql
--
-- Name: sys_email_verification_ticket; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sys_email_verification_ticket (
    id bigint NOT NULL,
    app_code character varying(64) NOT NULL,
    email character varying(256) NOT NULL,
    scene_code character varying(64) NOT NULL,
    code_hash character varying(128) NOT NULL,
    status character varying(32) DEFAULT 'pending'::character varying NOT NULL,
    attempt_count integer DEFAULT 0 NOT NULL,
    max_attempt_count integer DEFAULT 6 NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    verified_at timestamp with time zone,
    consumed_at timestamp with time zone,
    request_ip character varying(64),
    payload_json jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V1__init.sql
--
-- Name: sys_email_verification_ticket_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sys_email_verification_ticket_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- source: V1__init.sql
--
-- Name: sys_email_verification_ticket_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sys_email_verification_ticket_id_seq OWNED BY public.sys_email_verification_ticket.id;

-- source: V1__init.sql
--
-- Name: sys_entitlement_snapshot; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sys_entitlement_snapshot (
    id bigint NOT NULL,
    app_code character varying(64) NOT NULL,
    user_id bigint NOT NULL,
    entitlement_code character varying(64) NOT NULL,
    status character varying(32) DEFAULT 'active'::character varying NOT NULL,
    source_type character varying(32) NOT NULL,
    expires_at timestamp with time zone,
    payload_json jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V1__init.sql
--
-- Name: sys_entitlement_snapshot_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sys_entitlement_snapshot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- source: V1__init.sql
--
-- Name: sys_entitlement_snapshot_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sys_entitlement_snapshot_id_seq OWNED BY public.sys_entitlement_snapshot.id;

-- source: V1__init.sql
--
-- Name: sys_purchase_transaction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sys_purchase_transaction (
    id bigint NOT NULL,
    app_code character varying(64) NOT NULL,
    user_id bigint NOT NULL,
    source_type character varying(32) NOT NULL,
    product_id character varying(128),
    transaction_id character varying(128),
    original_transaction_id character varying(128) NOT NULL,
    store_environment character varying(32),
    storefront character varying(32),
    app_account_token character varying(128),
    signed_transaction_info_hash character varying(128) NOT NULL,
    signed_renewal_info_hash character varying(128),
    verification_status character varying(32) DEFAULT 'pending'::character varying NOT NULL,
    processing_status character varying(32) DEFAULT 'accepted'::character varying NOT NULL,
    payload_json jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V1__init.sql
--
-- Name: sys_purchase_transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sys_purchase_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- source: V1__init.sql
--
-- Name: sys_purchase_transaction_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sys_purchase_transaction_id_seq OWNED BY public.sys_purchase_transaction.id;

-- source: V1__init.sql
--
-- Name: sys_remote_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sys_remote_config (
    id bigint NOT NULL,
    app_code character varying(64) NOT NULL,
    namespace_code character varying(64) NOT NULL,
    config_key character varying(128) NOT NULL,
    config_value_json jsonb NOT NULL,
    status character varying(32) DEFAULT 'active'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V1__init.sql
--
-- Name: sys_remote_config_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sys_remote_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- source: V1__init.sql
--
-- Name: sys_remote_config_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sys_remote_config_id_seq OWNED BY public.sys_remote_config.id;

-- source: V1__init.sql
--
-- Name: sys_sync_audit_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sys_sync_audit_log (
    id bigint NOT NULL,
    app_code character varying(64) NOT NULL,
    user_id bigint NOT NULL,
    installation_id character varying(64),
    action_type character varying(64) NOT NULL,
    entity_type character varying(64),
    entity_id character varying(128),
    request_id character varying(128),
    result_status character varying(32) NOT NULL,
    detail_json jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V1__init.sql
--
-- Name: sys_sync_audit_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sys_sync_audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- source: V1__init.sql
--
-- Name: sys_sync_audit_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sys_sync_audit_log_id_seq OWNED BY public.sys_sync_audit_log.id;

-- source: V1__init.sql
--
-- Name: sys_sync_installation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sys_sync_installation (
    installation_id character varying(64) NOT NULL,
    app_code character varying(64) NOT NULL,
    user_id bigint NOT NULL,
    device_id character varying(128),
    client_platform character varying(32) NOT NULL,
    device_model character varying(128),
    app_version character varying(64),
    powersync_client_id character varying(128),
    cloud_sync_enabled boolean DEFAULT false NOT NULL,
    initial_sync_completed boolean DEFAULT false NOT NULL,
    last_sync_at timestamp with time zone,
    last_pull_at timestamp with time zone,
    last_push_at timestamp with time zone,
    last_error_code character varying(64),
    last_error_message text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V1__init.sql
--
-- Name: sys_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sys_user (
    id bigint NOT NULL,
    app_code character varying(64) NOT NULL,
    user_type character varying(32) NOT NULL,
    display_name character varying(128),
    status character varying(32) DEFAULT 'active'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V1__init.sql
--
-- Name: sys_user_device_event; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sys_user_device_event (
    id bigint NOT NULL,
    app_code character varying(64) NOT NULL,
    user_id bigint,
    session_id bigint,
    event_type character varying(64) NOT NULL,
    bundle_id character varying(128),
    client_platform character varying(32),
    device_model character varying(128),
    system_name character varying(64),
    system_version character varying(64),
    app_version character varying(64),
    build_number character varying(64),
    locale character varying(32),
    ip_country character varying(32),
    payload_json jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V1__init.sql
--
-- Name: sys_user_device_event_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sys_user_device_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- source: V1__init.sql
--
-- Name: sys_user_device_event_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sys_user_device_event_id_seq OWNED BY public.sys_user_device_event.id;

-- source: V1__init.sql
--
-- Name: sys_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sys_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- source: V1__init.sql
--
-- Name: sys_user_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sys_user_id_seq OWNED BY public.sys_user.id;

-- source: V1__init.sql
--
-- Name: sys_user_identity; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sys_user_identity (
    id bigint NOT NULL,
    app_code character varying(64) NOT NULL,
    user_id bigint NOT NULL,
    provider_code character varying(32) NOT NULL,
    provider_subject character varying(256) NOT NULL,
    email character varying(256),
    email_verified boolean,
    private_email boolean,
    status character varying(32) DEFAULT 'active'::character varying NOT NULL,
    payload_json jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V1__init.sql
--
-- Name: sys_user_identity_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sys_user_identity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- source: V1__init.sql
--
-- Name: sys_user_identity_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sys_user_identity_id_seq OWNED BY public.sys_user_identity.id;

-- source: V1__init.sql
--
-- Name: sys_app_store_notification id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_app_store_notification ALTER COLUMN id SET DEFAULT nextval('public.sys_app_store_notification_id_seq'::regclass);

-- source: V1__init.sql
--
-- Name: sys_audit_log id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_audit_log ALTER COLUMN id SET DEFAULT nextval('public.sys_audit_log_id_seq'::regclass);

-- source: V1__init.sql
--
-- Name: sys_auth_provider_token id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_auth_provider_token ALTER COLUMN id SET DEFAULT nextval('public.sys_auth_provider_token_id_seq'::regclass);

-- source: V1__init.sql
--
-- Name: sys_auth_session id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_auth_session ALTER COLUMN id SET DEFAULT nextval('public.sys_auth_session_id_seq'::regclass);

-- source: V1__init.sql
--
-- Name: sys_email_verification_ticket id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_email_verification_ticket ALTER COLUMN id SET DEFAULT nextval('public.sys_email_verification_ticket_id_seq'::regclass);

-- source: V1__init.sql
--
-- Name: sys_entitlement_snapshot id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_entitlement_snapshot ALTER COLUMN id SET DEFAULT nextval('public.sys_entitlement_snapshot_id_seq'::regclass);

-- source: V1__init.sql
--
-- Name: sys_purchase_transaction id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_purchase_transaction ALTER COLUMN id SET DEFAULT nextval('public.sys_purchase_transaction_id_seq'::regclass);

-- source: V1__init.sql
--
-- Name: sys_remote_config id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_remote_config ALTER COLUMN id SET DEFAULT nextval('public.sys_remote_config_id_seq'::regclass);

-- source: V1__init.sql
--
-- Name: sys_sync_audit_log id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_sync_audit_log ALTER COLUMN id SET DEFAULT nextval('public.sys_sync_audit_log_id_seq'::regclass);

-- source: V1__init.sql
--
-- Name: sys_user id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_user ALTER COLUMN id SET DEFAULT nextval('public.sys_user_id_seq'::regclass);

-- source: V1__init.sql
--
-- Name: sys_user_device_event id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_user_device_event ALTER COLUMN id SET DEFAULT nextval('public.sys_user_device_event_id_seq'::regclass);

-- source: V1__init.sql
--
-- Name: sys_user_identity id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_user_identity ALTER COLUMN id SET DEFAULT nextval('public.sys_user_identity_id_seq'::regclass);

-- source: V1__init.sql
--
-- Name: sys_app sys_app_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_app
    ADD CONSTRAINT sys_app_pkey PRIMARY KEY (app_code);

-- source: V1__init.sql
--
-- Name: sys_app_store_notification sys_app_store_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_app_store_notification
    ADD CONSTRAINT sys_app_store_notification_pkey PRIMARY KEY (id);

-- source: V1__init.sql
--
-- Name: sys_audit_log sys_audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_audit_log
    ADD CONSTRAINT sys_audit_log_pkey PRIMARY KEY (id);

-- source: V1__init.sql
--
-- Name: sys_auth_provider_token sys_auth_provider_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_auth_provider_token
    ADD CONSTRAINT sys_auth_provider_token_pkey PRIMARY KEY (id);

-- source: V1__init.sql
--
-- Name: sys_auth_session sys_auth_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_auth_session
    ADD CONSTRAINT sys_auth_session_pkey PRIMARY KEY (id);

-- source: V1__init.sql
--
-- Name: sys_auth_session sys_auth_session_session_token_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_auth_session
    ADD CONSTRAINT sys_auth_session_session_token_hash_key UNIQUE (session_token_hash);

-- source: V1__init.sql
--
-- Name: sys_email_verification_ticket sys_email_verification_ticket_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_email_verification_ticket
    ADD CONSTRAINT sys_email_verification_ticket_pkey PRIMARY KEY (id);

-- source: V1__init.sql
--
-- Name: sys_entitlement_snapshot sys_entitlement_snapshot_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_entitlement_snapshot
    ADD CONSTRAINT sys_entitlement_snapshot_pkey PRIMARY KEY (id);

-- source: V1__init.sql
--
-- Name: sys_purchase_transaction sys_purchase_transaction_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_purchase_transaction
    ADD CONSTRAINT sys_purchase_transaction_pkey PRIMARY KEY (id);

-- source: V1__init.sql
--
-- Name: sys_remote_config sys_remote_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_remote_config
    ADD CONSTRAINT sys_remote_config_pkey PRIMARY KEY (id);

-- source: V1__init.sql
--
-- Name: sys_sync_audit_log sys_sync_audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_sync_audit_log
    ADD CONSTRAINT sys_sync_audit_log_pkey PRIMARY KEY (id);

-- source: V1__init.sql
--
-- Name: sys_sync_installation sys_sync_installation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_sync_installation
    ADD CONSTRAINT sys_sync_installation_pkey PRIMARY KEY (installation_id);

-- source: V1__init.sql
--
-- Name: sys_user_device_event sys_user_device_event_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_user_device_event
    ADD CONSTRAINT sys_user_device_event_pkey PRIMARY KEY (id);

-- source: V1__init.sql
--
-- Name: sys_user_identity sys_user_identity_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_user_identity
    ADD CONSTRAINT sys_user_identity_pkey PRIMARY KEY (id);

-- source: V1__init.sql
--
-- Name: sys_user sys_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_user
    ADD CONSTRAINT sys_user_pkey PRIMARY KEY (id);

-- source: V1__init.sql
--
-- Name: idx_sys_app_store_notification_app_received; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sys_app_store_notification_app_received ON public.sys_app_store_notification USING btree (app_code, received_at DESC);

-- source: V1__init.sql
--
-- Name: idx_sys_audit_log_app_action_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sys_audit_log_app_action_created ON public.sys_audit_log USING btree (app_code, action_code, created_at DESC);

-- source: V1__init.sql
--
-- Name: idx_sys_auth_provider_token_user_provider; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sys_auth_provider_token_user_provider ON public.sys_auth_provider_token USING btree (user_id, provider_code, updated_at DESC);

-- source: V1__init.sql
--
-- Name: idx_sys_auth_session_app_status_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sys_auth_session_app_status_created ON public.sys_auth_session USING btree (app_code, status, created_at DESC);

-- source: V1__init.sql
--
-- Name: idx_sys_auth_session_user_status_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sys_auth_session_user_status_created ON public.sys_auth_session USING btree (user_id, status, created_at DESC);

-- source: V1__init.sql
--
-- Name: idx_sys_email_verification_ticket_app_email_scene_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sys_email_verification_ticket_app_email_scene_created ON public.sys_email_verification_ticket USING btree (app_code, email, scene_code, created_at DESC);

-- source: V1__init.sql
--
-- Name: idx_sys_email_verification_ticket_app_status_expires; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sys_email_verification_ticket_app_status_expires ON public.sys_email_verification_ticket USING btree (app_code, status, expires_at);

-- source: V1__init.sql
--
-- Name: idx_sys_entitlement_snapshot_user_status_updated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sys_entitlement_snapshot_user_status_updated ON public.sys_entitlement_snapshot USING btree (app_code, user_id, status, updated_at DESC);

-- source: V1__init.sql
--
-- Name: idx_sys_purchase_transaction_app_user_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sys_purchase_transaction_app_user_created ON public.sys_purchase_transaction USING btree (app_code, user_id, created_at DESC);

-- source: V1__init.sql
--
-- Name: idx_sys_purchase_transaction_original_tx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sys_purchase_transaction_original_tx ON public.sys_purchase_transaction USING btree (app_code, original_transaction_id, created_at DESC);

-- source: V1__init.sql
--
-- Name: idx_sys_remote_config_app_namespace_key; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sys_remote_config_app_namespace_key ON public.sys_remote_config USING btree (app_code, namespace_code, config_key);

-- source: V1__init.sql
--
-- Name: idx_sys_sync_audit_log_installation_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sys_sync_audit_log_installation_created ON public.sys_sync_audit_log USING btree (installation_id, created_at DESC);

-- source: V1__init.sql
--
-- Name: idx_sys_sync_audit_log_user_app_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sys_sync_audit_log_user_app_created ON public.sys_sync_audit_log USING btree (user_id, app_code, created_at DESC);

-- source: V1__init.sql
--
-- Name: idx_sys_sync_installation_app_sync; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sys_sync_installation_app_sync ON public.sys_sync_installation USING btree (app_code, cloud_sync_enabled, updated_at DESC);

-- source: V1__init.sql
--
-- Name: idx_sys_sync_installation_user_app; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sys_sync_installation_user_app ON public.sys_sync_installation USING btree (user_id, app_code);

-- source: V1__init.sql
--
-- Name: idx_sys_user_app_status_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sys_user_app_status_created ON public.sys_user USING btree (app_code, status, created_at DESC);

-- source: V1__init.sql
--
-- Name: idx_sys_user_device_event_app_event_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sys_user_device_event_app_event_created ON public.sys_user_device_event USING btree (app_code, event_type, created_at DESC);

-- source: V1__init.sql
--
-- Name: idx_sys_user_device_event_app_user_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sys_user_device_event_app_user_created ON public.sys_user_device_event USING btree (app_code, user_id, created_at DESC);

-- source: V1__init.sql
--
-- Name: idx_sys_user_identity_user_provider; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sys_user_identity_user_provider ON public.sys_user_identity USING btree (user_id, provider_code, updated_at DESC);

-- source: V1__init.sql
--
-- Name: uk_sys_app_store_notification_app_uuid; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_sys_app_store_notification_app_uuid ON public.sys_app_store_notification USING btree (app_code, notification_uuid);

-- source: V1__init.sql
--
-- Name: uk_sys_auth_provider_token_identity; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_sys_auth_provider_token_identity ON public.sys_auth_provider_token USING btree (app_code, provider_code, provider_subject);

-- source: V1__init.sql
--
-- Name: uk_sys_user_identity_app_provider_subject; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_sys_user_identity_app_provider_subject ON public.sys_user_identity USING btree (app_code, provider_code, provider_subject);

-- source: V1__init.sql
--
-- Name: uq_sys_sync_installation_app_user_installation; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_sys_sync_installation_app_user_installation ON public.sys_sync_installation USING btree (app_code, user_id, installation_id);

-- source: V1__init.sql
--
-- Name: sys_auth_provider_token sys_auth_provider_token_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_auth_provider_token
    ADD CONSTRAINT sys_auth_provider_token_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.sys_user(id);

-- source: V1__init.sql
--
-- Name: sys_auth_session sys_auth_session_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_auth_session
    ADD CONSTRAINT sys_auth_session_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.sys_user(id);

-- source: V1__init.sql
--
-- Name: sys_entitlement_snapshot sys_entitlement_snapshot_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_entitlement_snapshot
    ADD CONSTRAINT sys_entitlement_snapshot_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.sys_user(id);

-- source: V44__compensation_code_center.sql
-- 中文说明：补偿码表必须先于补偿相关外键创建，避免首版初始化执行到 FK 时表尚不存在。
CREATE TABLE IF NOT EXISTS public.sys_compensation_code (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    compensation_code varchar(64) NOT NULL,
    code_hash varchar(128) NOT NULL,
    benefit_type varchar(32) NOT NULL,
    plan_code varchar(64),
    entitlement_code varchar(64),
    service_type varchar(64),
    grant_count integer DEFAULT 1 NOT NULL,
    grant_valid_days integer,
    expires_at timestamp with time zone,
    max_uses integer DEFAULT 1 NOT NULL,
    used_count integer DEFAULT 0 NOT NULL,
    status varchar(32) DEFAULT 'unused' NOT NULL,
    used_by_user_id bigint,
    used_at timestamp with time zone,
    void_reason varchar(512),
    metadata_json jsonb,
    created_by_user_id bigint,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_compensation_code_app_code ON public.sys_compensation_code(app_code, compensation_code);
CREATE INDEX IF NOT EXISTS idx_sys_compensation_code_app_status_expiry ON public.sys_compensation_code(app_code, status, expires_at DESC);
CREATE INDEX IF NOT EXISTS idx_sys_compensation_code_app_benefit ON public.sys_compensation_code(app_code, benefit_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sys_compensation_code_app_used_by ON public.sys_compensation_code(app_code, used_by_user_id, used_at DESC);

CREATE TABLE IF NOT EXISTS public.sys_user_compensation_record (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    user_id bigint NOT NULL,
    compensation_code_id bigint NOT NULL,
    compensation_code varchar(64) NOT NULL,
    benefit_type varchar(32) NOT NULL,
    benefit_summary varchar(512) NOT NULL,
    plan_code varchar(64),
    entitlement_code varchar(64),
    service_type varchar(64),
    grant_count integer DEFAULT 1 NOT NULL,
    redeem_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    valid_until_at timestamp with time zone,
    status varchar(32) DEFAULT 'applied' NOT NULL,
    result_message varchar(512),
    before_json jsonb,
    after_json jsonb,
    metadata_json jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_user_compensation_record_app_code ON public.sys_user_compensation_record(app_code, compensation_code);
CREATE INDEX IF NOT EXISTS idx_sys_user_compensation_record_user_created ON public.sys_user_compensation_record(app_code, user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sys_user_compensation_record_code_created ON public.sys_user_compensation_record(app_code, compensation_code_id, created_at DESC);

-- source: V43__compensation_code_center.sql
--
-- Name: sys_compensation_code sys_compensation_code_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_compensation_code
    ADD CONSTRAINT sys_compensation_code_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.sys_user(id);

-- source: V43__compensation_code_center.sql
--
-- Name: sys_compensation_code sys_compensation_code_used_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_compensation_code
    ADD CONSTRAINT sys_compensation_code_used_by_user_id_fkey FOREIGN KEY (used_by_user_id) REFERENCES public.sys_user(id);

-- source: V43__compensation_code_center.sql
--
-- Name: sys_user_compensation_record sys_user_compensation_record_compensation_code_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_user_compensation_record
    ADD CONSTRAINT sys_user_compensation_record_compensation_code_id_fkey FOREIGN KEY (compensation_code_id) REFERENCES public.sys_compensation_code(id);

-- source: V43__compensation_code_center.sql
--
-- Name: sys_user_compensation_record sys_user_compensation_record_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_user_compensation_record
    ADD CONSTRAINT sys_user_compensation_record_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.sys_user(id);

-- source: V1__init.sql
--
-- Name: sys_purchase_transaction sys_purchase_transaction_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_purchase_transaction
    ADD CONSTRAINT sys_purchase_transaction_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.sys_user(id);

-- source: V1__init.sql
--
-- Name: sys_sync_audit_log sys_sync_audit_log_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_sync_audit_log
    ADD CONSTRAINT sys_sync_audit_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.sys_user(id);

-- source: V1__init.sql
--
-- Name: sys_sync_installation sys_sync_installation_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_sync_installation
    ADD CONSTRAINT sys_sync_installation_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.sys_user(id);

-- source: V1__init.sql
--
-- Name: sys_user_identity sys_user_identity_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sys_user_identity
    ADD CONSTRAINT sys_user_identity_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.sys_user(id);

-- source: V1__init.sql
--
--


-- =========================================================
-- Seed data
-- =========================================================

--
--


SET statement_timeout = 0;

-- source: V1__init.sql
SET lock_timeout = 0;

-- source: V1__init.sql
SET idle_in_transaction_session_timeout = 0;

-- source: V1__init.sql
SET client_encoding = 'UTF8';

-- source: V1__init.sql
SET standard_conforming_strings = on;

-- source: V1__init.sql
SET search_path = public;

-- source: V1__init.sql
SET check_function_bodies = false;

-- source: V1__init.sql
SET xmloption = content;

-- source: V1__init.sql
SET client_min_messages = warning;

-- source: V1__init.sql
SET row_security = off;

-- source: V1__init.sql
--
-- Data for Name: sys_user; Type: TABLE DATA; Schema: public; Owner: -
--


--
-- Data for Name: reading_child_profile; Type: TABLE DATA; Schema: public; Owner: -
--


--
-- Data for Name: reading_child_usage_daily; Type: TABLE DATA; Schema: public; Owner: -
--


--
-- Data for Name: reading_cloud_service_usage; Type: TABLE DATA; Schema: public; Owner: -
--


--
-- Data for Name: reading_daily_task_completion; Type: TABLE DATA; Schema: public; Owner: -
--


--
-- Data for Name: reading_feedback_ticket; Type: TABLE DATA; Schema: public; Owner: -
--


--
-- Data for Name: reading_ocr_audit; Type: TABLE DATA; Schema: public; Owner: -
--


--
-- Data for Name: reading_review_card; Type: TABLE DATA; Schema: public; Owner: -
--


--
-- Data for Name: reading_review_event; Type: TABLE DATA; Schema: public; Owner: -
--


--
-- Data for Name: reading_review_event_v2; Type: TABLE DATA; Schema: public; Owner: -
--


--
-- Data for Name: reading_usage_session; Type: TABLE DATA; Schema: public; Owner: -
--


--
-- Data for Name: reading_usage_session_v2; Type: TABLE DATA; Schema: public; Owner: -
--


--
-- Data for Name: reading_user_preference; Type: TABLE DATA; Schema: public; Owner: -
--


--
-- Data for Name: sys_app; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.sys_app (app_code, app_name, status, created_at, updated_at) VALUES ('paipai_readingcompanion', '拍拍伴读', 'active', '2026-04-24 10:48:45.582053+00', '2026-04-24 10:48:46.197828+00');

-- source: V1__init.sql

-- source: V1__init.sql
--
-- Data for Name: sys_app_store_notification; Type: TABLE DATA; Schema: public; Owner: -
--


--
-- Data for Name: sys_audit_log; Type: TABLE DATA; Schema: public; Owner: -
--


--
-- Data for Name: sys_auth_provider_token; Type: TABLE DATA; Schema: public; Owner: -
--


--
-- Data for Name: sys_auth_session; Type: TABLE DATA; Schema: public; Owner: -
--


--
-- Data for Name: sys_email_verification_ticket; Type: TABLE DATA; Schema: public; Owner: -
--


--
-- Data for Name: sys_entitlement_snapshot; Type: TABLE DATA; Schema: public; Owner: -
--


--
-- Data for Name: sys_purchase_transaction; Type: TABLE DATA; Schema: public; Owner: -
--


--
-- Data for Name: sys_remote_config; Type: TABLE DATA; Schema: public; Owner: -
--


-- source: V1__init.sql

-- source: V1__init.sql

-- source: V1__init.sql

-- source: V1__init.sql

-- source: V1__init.sql

-- source: V1__init.sql

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (17, 'paipai_readingcompanion', 'billing_entitlements', 'productMappings.com.paipai.readalong.family.monthly', '{"value": "family_access"}', 'active', '2026-04-24 10:48:45.587336+00', '2026-04-24 10:48:45.587336+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (16, 'paipai_readingcompanion', 'billing_entitlements', 'productMappings.com.paipai.readalong.family.multi_child.lifetime', '{"value": "family_multi_child"}', 'active', '2026-04-24 10:48:45.587336+00', '2026-04-24 10:48:45.587336+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (11, 'paipai_readingcompanion', 'billing_entitlements', 'productMappings.com.paipai.readalong.family.yearly', '{"value": "family_access"}', 'active', '2026-04-24 10:48:45.587336+00', '2026-04-24 10:48:45.587336+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (5, 'paipai_readingcompanion', 'billing_refresh_policy', 'candidateLimit', '{"value": 20}', 'active', '2026-04-24 10:48:45.587336+00', '2026-04-24 10:48:45.587336+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (32, 'paipai_readingcompanion', 'billing_refresh_policy', 'cooldownMinutes', '{"value": 5}', 'active', '2026-04-24 10:48:45.587336+00', '2026-04-24 10:48:45.587336+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (28, 'paipai_readingcompanion', 'bootstrap', 'default_locale', '{"value": "zh-Hans"}', 'active', '2026-04-24 10:48:45.587336+00', '2026-04-24 10:48:45.587336+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (26, 'paipai_readingcompanion', 'bootstrap', 'paywall_default_highlight', '{"value": "family_multi_child_lifetime"}', 'active', '2026-04-24 10:48:45.587336+00', '2026-04-24 10:48:45.587336+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (9, 'paipai_readingcompanion', 'bootstrap', 'supported_locales', '{"value": ["zh-Hans", "en", "ja", "ko", "es"]}', 'active', '2026-04-24 10:48:45.587336+00', '2026-04-24 10:48:45.587336+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (8, 'paipai_readingcompanion', 'cloud_provider', 'ocr.apiKeyEnvName', '{"value": "DASHSCOPE_API_KEY"}', 'active', '2026-04-24 10:48:45.587336+00', '2026-04-24 10:48:45.587336+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (21, 'paipai_readingcompanion', 'cloud_provider', 'ocr.endpoint', '{"value": "https://dashscope-intl.aliyuncs.com/compatible-mode/v1/chat/completions"}', 'active', '2026-04-24 10:48:45.587336+00', '2026-04-24 10:48:45.587336+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (23, 'paipai_readingcompanion', 'cloud_provider', 'ocr.headers', ('{"value": {"Content-Type": "application/json", "Authorization": "Bearer ' || '$' || '{API_KEY}"}}')::jsonb, 'active', '2026-04-24 10:48:45.587336+00', '2026-04-24 10:48:45.587336+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (20, 'paipai_readingcompanion', 'cloud_provider', 'ocr.maxPixels', '{"value": 8388608}', 'active', '2026-04-24 10:48:45.587336+00', '2026-04-24 10:48:45.587336+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (19, 'paipai_readingcompanion', 'cloud_provider', 'ocr.minPixels', '{"value": 3072}', 'active', '2026-04-24 10:48:45.587336+00', '2026-04-24 10:48:45.587336+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (29, 'paipai_readingcompanion', 'cloud_provider', 'ocr.model', '{"value": "qwen-vl-ocr-latest"}', 'active', '2026-04-24 10:48:45.587336+00', '2026-04-24 10:48:45.587336+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (33, 'paipai_readingcompanion', 'cloud_provider', 'ocr.prompt', '{"value": "Please output only the text content from the image without any additional descriptions or formatting."}', 'active', '2026-04-24 10:48:45.587336+00', '2026-04-24 10:48:45.587336+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (37, 'paipai_readingcompanion', 'cloud_provider', 'ocr.region', '{"value": "singapore"}', 'active', '2026-04-24 10:48:45.587336+00', '2026-04-24 10:48:45.587336+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (1, 'paipai_readingcompanion', 'cloud_provider', 'ocr.vendor', '{"value": "alibaba_bailian"}', 'active', '2026-04-24 10:48:45.587336+00', '2026-04-24 10:48:45.587336+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (36, 'paipai_readingcompanion', 'cloud_provider', 'tts.apiKeyEnvName', '{"value": "DASHSCOPE_API_KEY"}', 'active', '2026-04-24 10:48:45.587336+00', '2026-04-24 10:48:45.587336+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (13, 'paipai_readingcompanion', 'cloud_provider', 'tts.format', '{"value": "mp3"}', 'active', '2026-04-24 10:48:45.587336+00', '2026-04-24 10:48:45.587336+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (27, 'paipai_readingcompanion', 'cloud_provider', 'tts.headers', ('{"value": {"Authorization": "Bearer ' || '$' || '{API_KEY}"}}')::jsonb, 'active', '2026-04-24 10:48:45.587336+00', '2026-04-24 10:48:45.587336+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (24, 'paipai_readingcompanion', 'cloud_provider', 'tts.model', '{"value": "cosyvoice-v3-flash"}', 'active', '2026-04-24 10:48:45.587336+00', '2026-04-24 10:48:45.587336+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (7, 'paipai_readingcompanion', 'cloud_provider', 'tts.pitch', '{"value": 1.0}', 'active', '2026-04-24 10:48:45.587336+00', '2026-04-24 10:48:45.587336+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (31, 'paipai_readingcompanion', 'cloud_provider', 'tts.rate', '{"value": 1.0}', 'active', '2026-04-24 10:48:45.587336+00', '2026-04-24 10:48:45.587336+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (3, 'paipai_readingcompanion', 'cloud_provider', 'tts.region', '{"value": "singapore"}', 'active', '2026-04-24 10:48:45.587336+00', '2026-04-24 10:48:45.587336+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (14, 'paipai_readingcompanion', 'cloud_provider', 'tts.sampleRate', '{"value": 22050}', 'active', '2026-04-24 10:48:45.587336+00', '2026-04-24 10:48:45.587336+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (4, 'paipai_readingcompanion', 'cloud_provider', 'tts.vendor', '{"value": "alibaba_bailian"}', 'active', '2026-04-24 10:48:45.587336+00', '2026-04-24 10:48:45.587336+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (25, 'paipai_readingcompanion', 'cloud_provider', 'tts.voice', '{"value": "longanyang"}', 'active', '2026-04-24 10:48:45.587336+00', '2026-04-24 10:48:45.587336+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (18, 'paipai_readingcompanion', 'cloud_provider', 'tts.volume', '{"value": 50}', 'active', '2026-04-24 10:48:45.587336+00', '2026-04-24 10:48:45.587336+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (2, 'paipai_readingcompanion', 'cloud_provider', 'tts.wsUrl', '{"value": "wss://dashscope-intl.aliyuncs.com/api-ws/v1/inference"}', 'active', '2026-04-24 10:48:45.587336+00', '2026-04-24 10:48:45.587336+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (15, 'paipai_readingcompanion', 'features', 'cloud_sync_enabled', '{"value": false}', 'active', '2026-04-24 10:48:45.587336+00', '2026-04-24 10:48:45.587336+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (44, 'paipai_readingcompanion', 'reading_language_catalog', 'learning_tracks', '{"value": [{"code": "zh_to_en", "label": "中文家庭学英语"}, {"code": "en_to_zh", "label": "English families learn Chinese"}]}', 'active', '2026-04-24 10:48:45.807929+00', '2026-04-24 10:48:45.807929+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (45, 'paipai_readingcompanion', 'reading_language_catalog', 'supported_locales', '{"value": ["zh-Hans", "en", "ja", "ko", "es"]}', 'active', '2026-04-24 10:48:45.807929+00', '2026-04-24 10:48:45.807929+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (39, 'paipai_readingcompanion', 'reading_language_catalog', 'supported_source_languages', '{"value": ["en", "zh-Hans"]}', 'active', '2026-04-24 10:48:45.80329+00', '2026-04-24 10:48:45.80329+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (43, 'paipai_readingcompanion', 'reading_language_catalog', 'supported_target_languages', '{"value": ["zh-Hans", "en"]}', 'active', '2026-04-24 10:48:45.80329+00', '2026-04-24 10:48:45.80329+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (46, 'paipai_readingcompanion', 'reading_plan_catalog', 'free', '{"value": {"code": "free", "childLimit": 1, "displayName": "免费版", "premiumActive": false, "dailyPlanScope": "single_child", "historyEnabled": false, "localCardLimit": 20, "entitlementCode": "free", "cloudSyncEnabled": false, "dailyCaptureLimit": 3, "multiChildEnabled": false, "weeklyReportScope": "child", "advancedVoiceEnabled": false, "customReminderEnabled": false, "weeklyReportHistoryWeeks": 0}}', 'active', '2026-04-24 10:48:45.807929+00', '2026-04-24 10:48:45.807929+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (41, 'paipai_readingcompanion', 'release_ios', 'current_project_version', '{"value": "1"}', 'active', '2026-04-24 10:48:45.80329+00', '2026-04-24 10:48:45.80329+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (42, 'paipai_readingcompanion', 'release_ios', 'development_team', '{"value": "__FILL_ME__"}', 'active', '2026-04-24 10:48:45.80329+00', '2026-04-24 10:48:45.80329+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (40, 'paipai_readingcompanion', 'release_ios', 'marketing_version', '{"value": "1.0.0"}', 'active', '2026-04-24 10:48:45.80329+00', '2026-04-24 10:48:45.80329+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (38, 'paipai_readingcompanion', 'release_ios', 'paipai_api_base_url', '{"value": "https://api.paipai.app"}', 'active', '2026-04-24 10:48:45.80329+00', '2026-04-24 10:48:45.80329+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (47, 'paipai_readingcompanion', 'reading_plan_catalog', 'family_multi_child_lifetime', '{"value": {"code": "family_multi_child_lifetime", "badgeText": "一次开通", "highlight": true, "childLimit": 5, "displayName": "家庭多孩子终身版", "displayPrice": "¥68", "originalPrice": "¥98", "premiumActive": true, "dailyPlanScope": "per_child", "historyEnabled": true, "localCardLimit": 800, "entitlementCode": "family_multi_child", "cloudSyncEnabled": true, "appStoreProductId": "com.paipai.readalong.family.multi_child.lifetime", "dailyCaptureLimit": 50, "matchedProductIds": ["com.paipai.readalong.family.yearly", "com.paipai.readalong.family.monthly", "com.paipai.readalong.family.multi_child.lifetime"], "multiChildEnabled": true, "weeklyReportScope": "family", "advancedVoiceEnabled": true, "customReminderEnabled": false, "matchedEntitlementCodes": ["family_access", "family_multi_child"], "weeklyReportHistoryWeeks": 12}}', 'active', '2026-04-24 10:48:45.807929+00', '2026-04-24 10:48:46.249883+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (48, 'paipai_readingcompanion', 'release_ios', 'bundle_identifier', '{"value": "com.paipai.readalong.v2"}', 'active', '2026-04-24 10:48:46.28857+00', '2026-04-24 10:48:46.28857+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (51, 'paipai_readingcompanion', 'release_ios', 'first_release_positioning', '{"value": "首发版本仅承诺 iOS/iPadOS 18.0+；设备端翻译以 iOS 18 系统能力为准；iOS 17.x 不作为首发支持范围。"}', 'active', '2026-04-24 10:48:46.299468+00', '2026-04-24 10:48:46.299468+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (52, 'paipai_readingcompanion', 'release_ios', 'low_risk_review_notes', '{"value": "首发按本地 OCR、本地朗读、Apple 登录、App 内购买、账号删除、可选云 OCR/TTS 与云同步进行审核说明；不承诺未验证的 iOS 17.x 设备端翻译能力。"}', 'active', '2026-04-24 10:48:46.302258+00', '2026-04-24 10:48:46.302258+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (53, 'paipai_readingcompanion', 'release_ios', 'multi_app_expansion_note', '{"value": "统一后端以后续 app_code 为隔离边界；新增 App 应独立配置 app-definition、release_ios、billing_entitlements、cloud_provider、legal docs 与 PowerSync sync-rules。"}', 'active', '2026-04-24 10:48:46.305622+00', '2026-04-24 10:48:46.305622+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (49, 'paipai_readingcompanion', 'release_ios', 'minimum_ios_version', '{"value": "18.0"}', 'active', '2026-04-24 10:48:46.293368+00', '2026-04-24 10:48:46.308668+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (50, 'paipai_readingcompanion', 'release_ios', 'minimum_ipados_version', '{"value": "18.0"}', 'active', '2026-04-24 10:48:46.296355+00', '2026-04-24 10:48:46.314604+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (54, 'paipai_readingcompanion', 'reading_paywall_growth', 'default', '{"headline": "解锁家庭伴读节奏", "subtitle": "多孩子档案、更多拍读额度、云同步和周报历史，帮助家长长期看到孩子的进步。", "legalNotice": "权益以后端校验结果为准；价格与扣款以 Apple 确认弹窗为准。", "trialEnabled": false, "trustBullets": ["一次开通当前家庭版权益，具体扣款以 Apple 确认弹窗为准。", "学习内容默认优先保存在本机；云同步由家长主动开启。", "账号删除、法务文档和客服入口均在 App 内可访问。"], "defaultHighlight": "family_multi_child_lifetime"}', 'active', '2026-04-24 10:48:46.319188+00', '2026-04-24 10:48:46.319188+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (55, 'paipai_readingcompanion', 'reading_usage_policy', 'retentionDays', '{"value": 30}', 'active', '2026-04-24 10:48:46.332218+00', '2026-04-24 10:48:46.332218+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (56, 'paipai_readingcompanion', 'reading_usage_policy', 'recentSummaryDays', '{"value": 7}', 'active', '2026-04-24 10:48:46.335634+00', '2026-04-24 10:48:46.335634+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (57, 'paipai_readingcompanion', 'reading_usage_policy', 'dayBoundary', '{"value": "client_local"}', 'active', '2026-04-24 10:48:46.338934+00', '2026-04-24 10:48:46.338934+00');

-- source: V1__init.sql
INSERT INTO public.sys_remote_config (id, app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at) VALUES (58, 'paipai_readingcompanion', 'reading_usage_policy', 'maxSessionHours', '{"value": 24}', 'active', '2026-04-24 10:48:46.341315+00', '2026-04-24 10:48:46.341315+00');

-- source: V1__init.sql
--
-- Name: sys_app_store_notification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.sys_app_store_notification_id_seq', 1, false);

-- source: V1__init.sql
--
-- Name: sys_audit_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.sys_audit_log_id_seq', 1, false);

-- source: V1__init.sql
--
-- Name: sys_auth_provider_token_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.sys_auth_provider_token_id_seq', 1, false);

-- source: V1__init.sql
--
-- Name: sys_auth_session_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.sys_auth_session_id_seq', 1, false);

-- source: V1__init.sql
--
-- Name: sys_email_verification_ticket_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.sys_email_verification_ticket_id_seq', 1, false);

-- source: V1__init.sql
--
-- Name: sys_entitlement_snapshot_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.sys_entitlement_snapshot_id_seq', 1, false);

-- source: V1__init.sql
--
-- Name: sys_purchase_transaction_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.sys_purchase_transaction_id_seq', 1, false);

-- source: V1__init.sql
--
-- Name: sys_remote_config_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.sys_remote_config_id_seq', 58, true);

-- source: V1__init.sql
--
-- Name: sys_sync_audit_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.sys_sync_audit_log_id_seq', 1, false);

-- source: V1__init.sql
--
-- Name: sys_user_device_event_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.sys_user_device_event_id_seq', 1, false);

-- source: V1__init.sql
--
-- Name: sys_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.sys_user_id_seq', 1, false);

-- source: V1__init.sql
--
-- Name: sys_user_identity_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.sys_user_identity_id_seq', 1, false);

-- source: V1__init.sql
--
--

-- source: V18__paipai_weekly_report_v1_access.sql
-- paipai 周报第一版权益配置。
-- 目标：个人开发者低运维、低法律风险、App Store 首发稳定；周报权益以后端和数据库配置为准。
-- 注意：sys_remote_config 当前按 updated_at/id 倒序取同 key 第一条；这里先停用旧 key 再插入新配置，避免同 key active 过多。

UPDATE sys_remote_config
SET status = 'inactive', updated_at = now()
WHERE app_code = 'paipai_readingcompanion'
  AND namespace_code IN ('billing_entitlements', 'reading_plan_catalog', 'reading_weekly_report_access')
  AND config_key IN (
    'productMappings.com.paipai.readalong.family.monthly',
    'productMappings.com.paipai.readalong.family.yearly',
    'productMappings.com.paipai.readalong.family.multi_child.lifetime',
    'free',
    'standard_single_child',
    'family_multi_child_lifetime',
    'access_matrix_v1'
  );

-- source: V18__paipai_weekly_report_v1_access.sql
-- 月付/年付先作为“标准单孩子”权益；终身多孩子独立为家庭权益。
-- 这样可避免 family_access 被误判为多孩子家庭版，降低付费权益争议和审核风险。
INSERT INTO sys_remote_config (app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at)
VALUES
('paipai_readingcompanion', 'billing_entitlements', 'productMappings.com.paipai.readalong.family.monthly', '{"value":"family_access"}', 'active', now(), now()),
('paipai_readingcompanion', 'billing_entitlements', 'productMappings.com.paipai.readalong.family.yearly', '{"value":"family_access"}', 'active', now(), now()),
('paipai_readingcompanion', 'billing_entitlements', 'productMappings.com.paipai.readalong.family.multi_child.lifetime', '{"value":"family_multi_child"}', 'active', now(), now());

-- source: V18__paipai_weekly_report_v1_access.sql
-- 免费版：只看当前孩子基础周报；不显示高级预览；不支持历史和导出；支持页面分享。
INSERT INTO sys_remote_config (app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at)
VALUES (
  'paipai_readingcompanion',
  'reading_plan_catalog',
  'free',
  '{"value":{"code":"free","displayName":"免费版","entitlementCode":"free","premiumActive":false,"childLimit":1,"dailyCaptureLimit":3,"localCardLimit":20,"cloudSyncEnabled":false,"advancedVoiceEnabled":false,"multiChildEnabled":false,"dailyPlanScope":"single_child","weeklyReportScope":"child","weeklyReportTier":"free","weeklyReportHistoryWeeks":0,"historyEnabled":false,"offlineHistoryPreviewEnabled":false,"exportReportEnabled":false,"pageShareEnabled":true,"customReminderEnabled":false}}',
  'active', now(), now()
);

-- source: V18__paipai_weekly_report_v1_access.sql
-- 标准版：只支持 1 个孩子；完整单孩子周报；最近 4 周历史；后端不可用时可看本地已缓存历史预览；不支持导出。
INSERT INTO sys_remote_config (app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at)
VALUES (
  'paipai_readingcompanion',
  'reading_plan_catalog',
  'standard_single_child',
  '{"value":{"code":"standard_single_child","displayName":"标准版","entitlementCode":"family_access","matchedEntitlementCodes":["family_access"],"appStoreProductId":"com.paipai.readalong.family.monthly","matchedProductIds":["com.paipai.readalong.family.monthly","com.paipai.readalong.family.yearly"],"premiumActive":true,"highlight":true,"badgeText":"标准版","childLimit":1,"dailyCaptureLimit":20,"localCardLimit":300,"cloudSyncEnabled":true,"advancedVoiceEnabled":true,"multiChildEnabled":false,"dailyPlanScope":"single_child","weeklyReportScope":"child","weeklyReportTier":"standard","weeklyReportHistoryWeeks":4,"historyEnabled":true,"offlineHistoryPreviewEnabled":true,"exportReportEnabled":false,"pageShareEnabled":true,"customReminderEnabled":false}}',
  'active', now(), now()
);

-- source: V18__paipai_weekly_report_v1_access.sql
-- 家庭版：多孩子能力来自数据库 childLimit，默认 5；家庭总览 + 最近 12 周历史；不支持导出。
INSERT INTO sys_remote_config (app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at)
VALUES (
  'paipai_readingcompanion',
  'reading_plan_catalog',
  'family_multi_child_lifetime',
  '{"value":{"code":"family_multi_child_lifetime","displayName":"家庭多孩子终身版","entitlementCode":"family_multi_child","matchedEntitlementCodes":["family_multi_child"],"appStoreProductId":"com.paipai.readalong.family.multi_child.lifetime","matchedProductIds":["com.paipai.readalong.family.multi_child.lifetime"],"premiumActive":true,"highlight":false,"badgeText":"家庭版","childLimit":5,"dailyCaptureLimit":50,"localCardLimit":800,"cloudSyncEnabled":true,"advancedVoiceEnabled":true,"multiChildEnabled":true,"dailyPlanScope":"per_child","weeklyReportScope":"family","weeklyReportTier":"family","weeklyReportHistoryWeeks":12,"historyEnabled":true,"offlineHistoryPreviewEnabled":true,"exportReportEnabled":false,"pageShareEnabled":true,"customReminderEnabled":false}}',
  'active', now(), now()
);

-- source: V18__paipai_weekly_report_v1_access.sql
-- 周报模块访问矩阵：不返回 locked_preview；free 不预览高级模块；standard 不预览家庭模块。
-- 文案保持“家庭陪读参考”，避免学习诊断、排名、保证效果等高风险表达。
INSERT INTO sys_remote_config (app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at)
VALUES (
  'paipai_readingcompanion',
  'reading_weekly_report_access',
  'access_matrix_v1',
  '{"value":{"version":1,"defaultPlanCode":"free","previewMode":"disabled","historyEnabled":true,"exportReportEnabled":false,"pageShareEnabled":true,"offlineHistoryPreviewEnabled":true,"plans":{"free":{"tier":"free","historyWeeks":0,"modules":{"basic_stats":{"access":"full"},"safe_summary":{"access":"full"},"basic_suggestions":{"access":"full","maxItems":2},"single_child_detail":{"access":"hidden"},"review_focus":{"access":"hidden"},"family_overview":{"access":"hidden"},"child_summaries":{"access":"hidden"},"history_reports":{"access":"hidden"},"offline_history_preview":{"access":"hidden"},"export_report":{"access":"hidden"},"page_share":{"access":"full"}}},"standard_single_child":{"tier":"standard","historyWeeks":4,"modules":{"basic_stats":{"access":"full"},"safe_summary":{"access":"full"},"basic_suggestions":{"access":"full","maxItems":4},"single_child_detail":{"access":"full"},"review_focus":{"access":"full"},"family_overview":{"access":"hidden"},"child_summaries":{"access":"hidden"},"history_reports":{"access":"full","weeks":4},"offline_history_preview":{"access":"full"},"export_report":{"access":"hidden"},"page_share":{"access":"full"}}},"family_multi_child_lifetime":{"tier":"family","historyWeeks":12,"modules":{"basic_stats":{"access":"full"},"safe_summary":{"access":"full"},"basic_suggestions":{"access":"full","maxItems":5},"single_child_detail":{"access":"full"},"review_focus":{"access":"full"},"family_overview":{"access":"full"},"child_summaries":{"access":"full"},"history_reports":{"access":"full","weeks":12},"offline_history_preview":{"access":"full"},"export_report":{"access":"hidden"},"page_share":{"access":"full"}}}},"legal":{"defaultDisclaimer":"本报告仅用于家庭陪读参考，不用于学业评价、排名、诊断、医疗、心理或任何高风险判断。","avoidClaims":true,"avoidRanking":true}}}',
  'active', now(), now()
);


-- source: V32__release_ios_product_id_alignment.sql
-- 多 App release-gate 商品 ID 对齐配置。
-- 中文说明：统一后端可以复用 App Store 验签和权益投影能力，但每个 App 的商品 ID 必须按 appCode 隔离。
-- release_ios.product_ids 用于上线门禁比对，防止拍拍伴读的 billing productMappings / App Store Connect 商品配置偏离。

UPDATE public.sys_remote_config
SET status = 'inactive', updated_at = now()
WHERE namespace_code = 'release_ios'
  AND config_key = 'product_ids'
  AND app_code = 'paipai_readingcompanion';

-- source: V32__release_ios_product_id_alignment.sql
INSERT INTO public.sys_remote_config (app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at)
VALUES
('paipai_readingcompanion', 'release_ios', 'product_ids', '{"value":["com.paipai.readalong.family.monthly","com.paipai.readalong.family.multi_child.lifetime","com.paipai.readalong.family.yearly"]}', 'active', now(), now());


-- source: V34__multi_app_release_update_policy.sql
-- 多 App 通用 App Store 更新提示配置补齐。
-- 中文说明：
-- 1. 该 namespace 只承载普通版本提示与 App Store 跳转配置，客户端不得硬编码下载地址。
-- 2. appStoreUrl / appStoreId 需要在 App Store Connect 生成真实 App Apple ID 后由生产配置覆盖；
--    未配置真实 URL 时，客户端只展示当前/最新版本，不展示可点击跳转入口。
-- 3. 各 App 使用相同 namespace，但按 app_code 隔离，避免统一后端下跳转到其他 App 的商店页。

UPDATE public.sys_remote_config
SET status = 'inactive', updated_at = now()
WHERE app_code = 'paipai_readingcompanion'
  AND namespace_code = 'app_release_policy';

-- source: V34__multi_app_release_update_policy.sql
INSERT INTO public.sys_remote_config (app_code, namespace_code, config_key, config_value_json, status, created_at, updated_at)
VALUES
('paipai_readingcompanion', 'app_release_policy', 'ios', '{"value":{"version":1,"appName":"拍拍伴读","platform":"ios","latestVersion":"1.0.0","latestBuild":"1","minimumSupportedVersion":"1.0.0","severity":"recommended","blocking":false,"appStoreId":"","appStoreUrl":"","downloadUrl":"","storeUrl":"","updateUrl":"","title":"发现新版本","message":"拍拍伴读有新版本可用。你可以前往 App Store 查看并决定是否更新。","ctaText":"前往 App Store","releaseNotes":["优化陪读体验与稳定性"],"opsNote":"生产环境必须填入本 App 的真实 App Store URL 或 appStoreId；客户端只消费该配置，不在前端硬编码下载地址。"}}', 'active', now(), now());

-- source: V35__sys_entitlement_center_mode3.sql
-- 统一后台式权益中心（模式三：老用户权益保护版）。
-- 中文说明：权益配置按 app_code 隔离，当前仅保留拍拍伴读需要的策略。
-- 设计目标：
-- 1) 免费权益按当前后台配置动态调整；
-- 2) 付费权益在有效期内保留购买时快照，后台降配不能影响已付款承诺；
-- 3) 新增/提升权益自动给有效期内老用户补齐；
-- 4) 人工赠送和用户级覆盖不要写 sys_entitlement_snapshot，避免被 App Store 刷新覆盖。

CREATE TABLE IF NOT EXISTS public.sys_membership_plan (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    plan_code varchar(64) NOT NULL,
    display_name varchar(128) NOT NULL,
    description varchar(512),
    plan_level integer DEFAULT 0 NOT NULL,
    entitlement_code varchar(64),
    status varchar(32) DEFAULT 'active' NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    metadata_json jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V35__sys_entitlement_center_mode3.sql
CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_membership_plan_app_plan ON public.sys_membership_plan(app_code, plan_code);

-- source: V35__sys_entitlement_center_mode3.sql
CREATE INDEX IF NOT EXISTS idx_sys_membership_plan_app_status ON public.sys_membership_plan(app_code, status);

-- source: V35__sys_entitlement_center_mode3.sql
CREATE TABLE IF NOT EXISTS public.sys_entitlement_feature (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    feature_code varchar(96) NOT NULL,
    feature_name varchar(128) NOT NULL,
    feature_type varchar(32) DEFAULT 'boolean' NOT NULL,
    description varchar(512),
    default_enabled boolean DEFAULT false NOT NULL,
    backend_enforced boolean DEFAULT false NOT NULL,
    frontend_visible boolean DEFAULT true NOT NULL,
    status varchar(32) DEFAULT 'active' NOT NULL,
    metadata_json jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V35__sys_entitlement_center_mode3.sql
CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_entitlement_feature_app_feature ON public.sys_entitlement_feature(app_code, feature_code);

-- source: V35__sys_entitlement_center_mode3.sql
CREATE INDEX IF NOT EXISTS idx_sys_entitlement_feature_app_status ON public.sys_entitlement_feature(app_code, status);

-- source: V35__sys_entitlement_center_mode3.sql
CREATE TABLE IF NOT EXISTS public.sys_plan_feature_rule (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    plan_code varchar(64) NOT NULL,
    feature_code varchar(96) NOT NULL,
    enabled boolean DEFAULT false NOT NULL,
    access_level varchar(32) DEFAULT 'none' NOT NULL,
    limit_value integer,
    limit_unit varchar(32),
    scope_code varchar(64),
    priority integer DEFAULT 0 NOT NULL,
    effective_start_at timestamp with time zone,
    effective_end_at timestamp with time zone,
    status varchar(32) DEFAULT 'active' NOT NULL,
    rule_json jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V35__sys_entitlement_center_mode3.sql
CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_plan_feature_rule_app_plan_feature ON public.sys_plan_feature_rule(app_code, plan_code, feature_code);

-- source: V35__sys_entitlement_center_mode3.sql
CREATE INDEX IF NOT EXISTS idx_sys_plan_feature_rule_app_plan ON public.sys_plan_feature_rule(app_code, plan_code, status);

-- source: V35__sys_entitlement_center_mode3.sql
CREATE INDEX IF NOT EXISTS idx_sys_plan_feature_rule_app_feature ON public.sys_plan_feature_rule(app_code, feature_code, status);

-- source: V35__sys_entitlement_center_mode3.sql
CREATE TABLE IF NOT EXISTS public.sys_product_entitlement_mapping (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    store_code varchar(32) DEFAULT 'appstore' NOT NULL,
    product_id varchar(128) NOT NULL,
    plan_code varchar(64),
    entitlement_code varchar(64) NOT NULL,
    product_type varchar(32) DEFAULT 'subscription' NOT NULL,
    status varchar(32) DEFAULT 'active' NOT NULL,
    metadata_json jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V35__sys_entitlement_center_mode3.sql
CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_product_entitlement_mapping_app_store_product ON public.sys_product_entitlement_mapping(app_code, store_code, product_id);

-- source: V35__sys_entitlement_center_mode3.sql
CREATE INDEX IF NOT EXISTS idx_sys_product_entitlement_mapping_app_entitlement ON public.sys_product_entitlement_mapping(app_code, entitlement_code, status);

-- source: V35__sys_entitlement_center_mode3.sql
CREATE TABLE IF NOT EXISTS public.sys_user_plan_snapshot (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    user_id bigint NOT NULL,
    plan_code varchar(64) NOT NULL,
    entitlement_code varchar(64),
    policy_version varchar(64) NOT NULL,
    source_type varchar(32) NOT NULL,
    source_ref varchar(128),
    status varchar(32) DEFAULT 'active' NOT NULL,
    starts_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expires_at timestamp with time zone,
    feature_snapshot_json jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V35__sys_entitlement_center_mode3.sql
CREATE INDEX IF NOT EXISTS idx_sys_user_plan_snapshot_user ON public.sys_user_plan_snapshot(app_code, user_id, status);

-- source: V35__sys_entitlement_center_mode3.sql
CREATE INDEX IF NOT EXISTS idx_sys_user_plan_snapshot_entitlement ON public.sys_user_plan_snapshot(app_code, entitlement_code, status);

-- source: V35__sys_entitlement_center_mode3.sql
CREATE INDEX IF NOT EXISTS idx_sys_user_plan_snapshot_plan ON public.sys_user_plan_snapshot(app_code, plan_code, status);

-- source: V35__sys_entitlement_center_mode3.sql
CREATE TABLE IF NOT EXISTS public.sys_user_entitlement_grant (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    user_id bigint NOT NULL,
    grant_code varchar(96) NOT NULL,
    plan_code varchar(64),
    entitlement_code varchar(64),
    source_type varchar(32) DEFAULT 'manual' NOT NULL,
    source_ref varchar(128),
    status varchar(32) DEFAULT 'active' NOT NULL,
    starts_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expires_at timestamp with time zone,
    reason varchar(512),
    operator_user_id bigint,
    metadata_json jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V35__sys_entitlement_center_mode3.sql
CREATE INDEX IF NOT EXISTS idx_sys_user_entitlement_grant_user ON public.sys_user_entitlement_grant(app_code, user_id, status);

-- source: V35__sys_entitlement_center_mode3.sql
CREATE INDEX IF NOT EXISTS idx_sys_user_entitlement_grant_entitlement ON public.sys_user_entitlement_grant(app_code, entitlement_code, status);

-- source: V35__sys_entitlement_center_mode3.sql
CREATE TABLE IF NOT EXISTS public.sys_user_feature_override (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    user_id bigint NOT NULL,
    feature_code varchar(96) NOT NULL,
    enabled boolean,
    access_level varchar(32),
    limit_value integer,
    limit_unit varchar(32),
    scope_code varchar(64),
    status varchar(32) DEFAULT 'active' NOT NULL,
    starts_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expires_at timestamp with time zone,
    reason varchar(512),
    operator_user_id bigint,
    metadata_json jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V35__sys_entitlement_center_mode3.sql
CREATE INDEX IF NOT EXISTS idx_sys_user_feature_override_user ON public.sys_user_feature_override(app_code, user_id, status);

-- source: V35__sys_entitlement_center_mode3.sql
CREATE INDEX IF NOT EXISTS idx_sys_user_feature_override_feature ON public.sys_user_feature_override(app_code, feature_code, status);

-- source: V35__sys_entitlement_center_mode3.sql
CREATE TABLE IF NOT EXISTS public.sys_entitlement_policy_audit_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    operator_user_id bigint,
    operator_name varchar(128),
    action_type varchar(64) NOT NULL,
    target_type varchar(64) NOT NULL,
    target_key varchar(256) NOT NULL,
    before_json jsonb,
    after_json jsonb,
    request_id varchar(128),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V35__sys_entitlement_center_mode3.sql
CREATE INDEX IF NOT EXISTS idx_sys_entitlement_policy_audit_app_created ON public.sys_entitlement_policy_audit_log(app_code, created_at DESC);

-- source: V43__compensation_code_center.sql
CREATE TABLE IF NOT EXISTS public.sys_compensation_code (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    compensation_code varchar(64) NOT NULL,
    code_hash varchar(128) NOT NULL,
    benefit_type varchar(32) NOT NULL,
    plan_code varchar(64),
    entitlement_code varchar(64),
    service_type varchar(64),
    grant_count integer DEFAULT 1 NOT NULL,
    grant_valid_days integer,
    expires_at timestamp with time zone,
    max_uses integer DEFAULT 1 NOT NULL,
    used_count integer DEFAULT 0 NOT NULL,
    status varchar(32) DEFAULT 'unused' NOT NULL,
    used_by_user_id bigint,
    used_at timestamp with time zone,
    void_reason varchar(512),
    metadata_json jsonb,
    created_by_user_id bigint,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V43__compensation_code_center.sql
CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_compensation_code_app_code ON public.sys_compensation_code(app_code, compensation_code);

-- source: V43__compensation_code_center.sql
CREATE INDEX IF NOT EXISTS idx_sys_compensation_code_app_status_expiry ON public.sys_compensation_code(app_code, status, expires_at DESC);

-- source: V43__compensation_code_center.sql
CREATE INDEX IF NOT EXISTS idx_sys_compensation_code_app_benefit ON public.sys_compensation_code(app_code, benefit_type, created_at DESC);

-- source: V43__compensation_code_center.sql
CREATE INDEX IF NOT EXISTS idx_sys_compensation_code_app_used_by ON public.sys_compensation_code(app_code, used_by_user_id, used_at DESC);

-- source: V43__compensation_code_center.sql
CREATE TABLE IF NOT EXISTS public.sys_user_compensation_record (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    user_id bigint NOT NULL,
    compensation_code_id bigint NOT NULL,
    compensation_code varchar(64) NOT NULL,
    benefit_type varchar(32) NOT NULL,
    benefit_summary varchar(512) NOT NULL,
    plan_code varchar(64),
    entitlement_code varchar(64),
    service_type varchar(64),
    grant_count integer DEFAULT 1 NOT NULL,
    redeem_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    valid_until_at timestamp with time zone,
    status varchar(32) DEFAULT 'applied' NOT NULL,
    result_message varchar(512),
    before_json jsonb,
    after_json jsonb,
    metadata_json jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- source: V43__compensation_code_center.sql
CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_user_compensation_record_app_code ON public.sys_user_compensation_record(app_code, compensation_code);

-- source: V43__compensation_code_center.sql
CREATE INDEX IF NOT EXISTS idx_sys_user_compensation_record_user_created ON public.sys_user_compensation_record(app_code, user_id, created_at DESC);

-- source: V43__compensation_code_center.sql
CREATE INDEX IF NOT EXISTS idx_sys_user_compensation_record_code_created ON public.sys_user_compensation_record(app_code, compensation_code_id, created_at DESC);

-- source: V35__sys_entitlement_center_mode3.sql
-- 会员等级：plan_code 是 App 内语义；entitlement_code 是统一计费内核投影出的可校验码。
INSERT INTO public.sys_membership_plan(app_code, plan_code, display_name, description, plan_level, entitlement_code, status, sort_order, metadata_json, created_at, updated_at)
VALUES
('paipai_readingcompanion','free','免费版','拍拍伴读免费基础权益',0,'free','active',0,'{}',now(),now()),
('paipai_readingcompanion','standard_single_child','标准版','单孩子订阅权益；有效期内购买快照保护历史承诺',10,'family_access','active',10,'{"badgeText":"标准版","mode3":"purchase_snapshot_protection"}',now(),now()),
('paipai_readingcompanion','family_multi_child_lifetime','家庭多孩子终身版','家庭多孩子终身权益',20,'family_multi_child','active',20,'{"badgeText":"家庭版","mode3":"purchase_snapshot_protection"}',now(),now())
ON CONFLICT (app_code, plan_code) DO UPDATE SET display_name=excluded.display_name, description=excluded.description, plan_level=excluded.plan_level, entitlement_code=excluded.entitlement_code, status=excluded.status, sort_order=excluded.sort_order, metadata_json=excluded.metadata_json, updated_at=now();

-- source: V35__sys_entitlement_center_mode3.sql
INSERT INTO public.sys_entitlement_feature(app_code, feature_code, feature_name, feature_type, default_enabled, backend_enforced, frontend_visible, status, metadata_json, created_at, updated_at)
VALUES
('paipai_readingcompanion','child_profile','孩子档案','quota',true,true,true,'active','{}',now(),now()),
('paipai_readingcompanion','daily_capture','每日拍读额度','quota',true,true,true,'active','{}',now(),now()),
('paipai_readingcompanion','local_card','本地句卡','quota',true,true,true,'active','{}',now(),now()),
('paipai_readingcompanion','cloud_sync','云同步','boolean',false,true,true,'active','{}',now(),now()),
('paipai_readingcompanion','advanced_voice','高级语音','boolean',false,true,true,'active','{}',now(),now()),
('paipai_readingcompanion','multi_child','多孩子','boolean',false,true,true,'active','{}',now(),now()),
('paipai_readingcompanion','weekly_report','周报模块','module',true,true,true,'active','{}',now(),now()),
('paipai_readingcompanion','weekly_report_history','历史周报','duration',false,true,true,'active','{}',now(),now()),
('paipai_readingcompanion','custom_reminder','自定义提醒','boolean',false,true,true,'active','{}',now(),now())
ON CONFLICT (app_code, feature_code) DO UPDATE SET feature_name=excluded.feature_name, feature_type=excluded.feature_type, default_enabled=excluded.default_enabled, backend_enforced=excluded.backend_enforced, frontend_visible=excluded.frontend_visible, status=excluded.status, metadata_json=excluded.metadata_json, updated_at=now();

-- source: V35__sys_entitlement_center_mode3.sql
INSERT INTO public.sys_plan_feature_rule(app_code, plan_code, feature_code, enabled, access_level, limit_value, limit_unit, scope_code, priority, status, rule_json, created_at, updated_at)
VALUES
-- Paipai free
('paipai_readingcompanion','free','child_profile',true,'limited',1,'count','account',10,'active','{}',now(),now()),
('paipai_readingcompanion','free','daily_capture',true,'limited',3,'day','single_child',20,'active','{}',now(),now()),
('paipai_readingcompanion','free','local_card',true,'limited',20,'count','account',30,'active','{}',now(),now()),
('paipai_readingcompanion','free','cloud_sync',false,'none',null,null,'account',40,'active','{}',now(),now()),
('paipai_readingcompanion','free','advanced_voice',false,'none',null,null,'account',50,'active','{}',now(),now()),
('paipai_readingcompanion','free','multi_child',false,'none',null,null,'account',60,'active','{}',now(),now()),
('paipai_readingcompanion','free','weekly_report',true,'limited',null,null,'child',70,'active','{}',now(),now()),
('paipai_readingcompanion','free','weekly_report_history',false,'none',0,'week_count','child',80,'active','{}',now(),now()),
('paipai_readingcompanion','free','custom_reminder',false,'none',null,null,'account',90,'active','{}',now(),now()),
-- Paipai standard
('paipai_readingcompanion','standard_single_child','child_profile',true,'limited',1,'count','account',10,'active','{}',now(),now()),
('paipai_readingcompanion','standard_single_child','daily_capture',true,'limited',20,'day','single_child',20,'active','{}',now(),now()),
('paipai_readingcompanion','standard_single_child','local_card',true,'limited',300,'count','account',30,'active','{}',now(),now()),
('paipai_readingcompanion','standard_single_child','cloud_sync',true,'full',null,null,'account',40,'active','{}',now(),now()),
('paipai_readingcompanion','standard_single_child','advanced_voice',true,'full',null,null,'account',50,'active','{}',now(),now()),
('paipai_readingcompanion','standard_single_child','multi_child',false,'none',null,null,'account',60,'active','{}',now(),now()),
('paipai_readingcompanion','standard_single_child','weekly_report',true,'full',null,null,'child',70,'active','{}',now(),now()),
('paipai_readingcompanion','standard_single_child','weekly_report_history',true,'full',4,'week_count','child',80,'active','{}',now(),now()),
('paipai_readingcompanion','standard_single_child','custom_reminder',false,'none',null,null,'account',90,'active','{}',now(),now()),
-- Paipai family lifetime
('paipai_readingcompanion','family_multi_child_lifetime','child_profile',true,'limited',5,'count','family',10,'active','{}',now(),now()),
('paipai_readingcompanion','family_multi_child_lifetime','daily_capture',true,'limited',50,'day','per_child',20,'active','{}',now(),now()),
('paipai_readingcompanion','family_multi_child_lifetime','local_card',true,'limited',800,'count','account',30,'active','{}',now(),now()),
('paipai_readingcompanion','family_multi_child_lifetime','cloud_sync',true,'full',null,null,'account',40,'active','{}',now(),now()),
('paipai_readingcompanion','family_multi_child_lifetime','advanced_voice',true,'full',null,null,'account',50,'active','{}',now(),now()),
('paipai_readingcompanion','family_multi_child_lifetime','multi_child',true,'full',null,null,'family',60,'active','{}',now(),now()),
('paipai_readingcompanion','family_multi_child_lifetime','weekly_report',true,'full',null,null,'family',70,'active','{}',now(),now()),
('paipai_readingcompanion','family_multi_child_lifetime','weekly_report_history',true,'full',12,'week_count','family',80,'active','{}',now(),now()),
('paipai_readingcompanion','family_multi_child_lifetime','custom_reminder',false,'none',null,null,'account',90,'active','{}',now(),now())
ON CONFLICT (app_code, plan_code, feature_code) DO UPDATE SET enabled=excluded.enabled, access_level=excluded.access_level, limit_value=excluded.limit_value, limit_unit=excluded.limit_unit, scope_code=excluded.scope_code, priority=excluded.priority, status=excluded.status, rule_json=excluded.rule_json, updated_at=now();

-- source: V35__sys_entitlement_center_mode3.sql
INSERT INTO public.sys_product_entitlement_mapping(app_code, store_code, product_id, plan_code, entitlement_code, product_type, status, metadata_json, created_at, updated_at)
VALUES
('paipai_readingcompanion','appstore','com.paipai.readalong.family.monthly','standard_single_child','family_access','subscription','active','{}',now(),now()),
('paipai_readingcompanion','appstore','com.paipai.readalong.family.yearly','standard_single_child','family_access','subscription','active','{}',now(),now()),
('paipai_readingcompanion','appstore','com.paipai.readalong.family.multi_child.lifetime','family_multi_child_lifetime','family_multi_child','non_consumable','active','{}',now(),now())
ON CONFLICT (app_code, store_code, product_id) DO UPDATE SET plan_code=excluded.plan_code, entitlement_code=excluded.entitlement_code, product_type=excluded.product_type, status=excluded.status, metadata_json=excluded.metadata_json, updated_at=now();

-- source: V35__sys_entitlement_center_mode3.sql
-- 老用户补购买时快照：只补仍 active 且未过期的付费权益；过期记录不参与权益保护。
INSERT INTO public.sys_user_plan_snapshot(app_code, user_id, plan_code, entitlement_code, policy_version, source_type, source_ref, status, starts_at, expires_at, feature_snapshot_json, created_at, updated_at)
SELECT
    s.app_code,
    s.user_id,
    p.plan_code,
    s.entitlement_code,
    s.app_code || ':' || p.plan_code || ':mode3_backfill_20260428',
    'legacy_backfill',
    'sys_entitlement_snapshot:' || s.id,
    'active',
    COALESCE(s.created_at, now()),
    s.expires_at,
    jsonb_build_object(
        'version', s.app_code || ':' || p.plan_code || ':mode3_backfill_20260428',
        'planCode', p.plan_code,
        'entitlementCode', s.entitlement_code,
        'features', COALESCE((
            SELECT jsonb_object_agg(r.feature_code, jsonb_build_object(
                'enabled', r.enabled,
                'accessLevel', r.access_level,
                'limitValue', r.limit_value,
                'limitUnit', r.limit_unit,
                'scopeCode', r.scope_code,
                'source', 'legacy_backfill_current_rule'
            ))
            FROM public.sys_plan_feature_rule r
            WHERE r.app_code = p.app_code AND r.plan_code = p.plan_code AND r.status = 'active'
        ), '{}'::jsonb)
    ),
    now(),
    now()
FROM public.sys_entitlement_snapshot s
JOIN public.sys_membership_plan p
  ON p.app_code = s.app_code
 AND p.entitlement_code = s.entitlement_code
 AND p.status = 'active'
WHERE s.status = 'active'
  AND COALESCE(s.entitlement_code, '') <> 'free'
  AND (s.expires_at IS NULL OR s.expires_at > now())
  AND NOT EXISTS (
      SELECT 1 FROM public.sys_user_plan_snapshot existing
      WHERE existing.app_code = s.app_code
        AND existing.user_id = s.user_id
        AND existing.source_ref = 'sys_entitlement_snapshot:' || s.id
  );

