CREATE TABLE IF NOT EXISTS public.reading_daily_quota_config (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code character varying(64) DEFAULT 'paipai_readingcompanion'::character varying NOT NULL,
    plan_code character varying(64) NOT NULL,
    feature_code character varying(64) NOT NULL,
    daily_limit integer NOT NULL,
    status character varying(32) DEFAULT 'active'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_reading_daily_quota_config_plan_feature
    ON public.reading_daily_quota_config(app_code, plan_code, feature_code);

CREATE INDEX IF NOT EXISTS idx_reading_daily_quota_config_status
    ON public.reading_daily_quota_config(app_code, status);

DELETE FROM public.reading_daily_quota_config
WHERE app_code = 'paipai_readingcompanion';

INSERT INTO public.reading_daily_quota_config (app_code, plan_code, feature_code, daily_limit, status)
VALUES
    ('paipai_readingcompanion', 'free', 'capture', 5, 'active'),
    ('paipai_readingcompanion', 'free', 'speech', 10, 'active'),
    ('paipai_readingcompanion', 'free', 'cloud_ocr', 0, 'active'),
    ('paipai_readingcompanion', 'free', 'cloud_tts', 0, 'active'),
    ('paipai_readingcompanion', 'standard_single_child', 'capture', 50, 'active'),
    ('paipai_readingcompanion', 'standard_single_child', 'speech', 100, 'active'),
    ('paipai_readingcompanion', 'standard_single_child', 'cloud_ocr', 0, 'active'),
    ('paipai_readingcompanion', 'standard_single_child', 'cloud_tts', 0, 'active'),
    ('paipai_readingcompanion', 'family_multi_child_lifetime', 'capture', 50, 'active'),
    ('paipai_readingcompanion', 'family_multi_child_lifetime', 'speech', 100, 'active'),
    ('paipai_readingcompanion', 'family_multi_child_lifetime', 'cloud_ocr', 0, 'active'),
    ('paipai_readingcompanion', 'family_multi_child_lifetime', 'cloud_tts', 0, 'active')
ON CONFLICT (app_code, plan_code, feature_code) DO UPDATE SET
    daily_limit = EXCLUDED.daily_limit,
    status = EXCLUDED.status,
    updated_at = CURRENT_TIMESTAMP;
