CREATE TABLE IF NOT EXISTS public.reading_cloud_service_credit_grant (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code character varying(64) DEFAULT 'paipai_readingcompanion'::character varying NOT NULL,
    user_id bigint NOT NULL,
    service_type character varying(64) NOT NULL,
    grant_type character varying(32) NOT NULL,
    total_count integer NOT NULL,
    used_count integer DEFAULT 0 NOT NULL,
    source_type character varying(64) NOT NULL,
    source_ref character varying(128),
    product_code character varying(128),
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_reading_credit_grant_count CHECK (total_count > 0 AND used_count >= 0 AND used_count <= total_count)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_reading_credit_grant_source_ref
    ON public.reading_cloud_service_credit_grant(app_code, user_id, service_type, source_type, source_ref)
    WHERE source_ref IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_reading_credit_grant_user_service_active
    ON public.reading_cloud_service_credit_grant(app_code, user_id, service_type, expires_at, grant_type);
