CREATE TABLE IF NOT EXISTS public.sys_compensation_code (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    compensation_code varchar(64) NOT NULL,
    code_hash varchar(128) NOT NULL,
    benefit_type varchar(32) NOT NULL,
    plan_code varchar(64),
    entitlement_code varchar(64),
    service_type varchar(64),
    grant_count integer DEFAULT 1 NOT NULL,
    grant_valid_days integer,
    expires_at timestamp with time zone,
    max_uses integer DEFAULT 1 NOT NULL,
    used_count integer DEFAULT 0 NOT NULL,
    status varchar(32) DEFAULT 'unused' NOT NULL,
    used_by_user_id bigint,
    used_at timestamp with time zone,
    void_reason varchar(512),
    metadata_json jsonb,
    created_by_user_id bigint,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_compensation_code_app_code
    ON public.sys_compensation_code(app_code, compensation_code);
CREATE INDEX IF NOT EXISTS idx_sys_compensation_code_app_status_expiry
    ON public.sys_compensation_code(app_code, status, expires_at DESC);
CREATE INDEX IF NOT EXISTS idx_sys_compensation_code_app_benefit
    ON public.sys_compensation_code(app_code, benefit_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sys_compensation_code_app_used_by
    ON public.sys_compensation_code(app_code, used_by_user_id, used_at DESC);

CREATE TABLE IF NOT EXISTS public.sys_user_compensation_record (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL,
    user_id bigint NOT NULL,
    compensation_code_id bigint NOT NULL,
    compensation_code varchar(64) NOT NULL,
    benefit_type varchar(32) NOT NULL,
    benefit_summary varchar(512) NOT NULL,
    plan_code varchar(64),
    entitlement_code varchar(64),
    service_type varchar(64),
    grant_count integer DEFAULT 1 NOT NULL,
    redeem_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    valid_until_at timestamp with time zone,
    status varchar(32) DEFAULT 'applied' NOT NULL,
    result_message varchar(512),
    before_json jsonb,
    after_json jsonb,
    metadata_json jsonb,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_user_compensation_record_app_code
    ON public.sys_user_compensation_record(app_code, compensation_code);
CREATE INDEX IF NOT EXISTS idx_sys_user_compensation_record_user_created
    ON public.sys_user_compensation_record(app_code, user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sys_user_compensation_record_code_created
    ON public.sys_user_compensation_record(app_code, compensation_code_id, created_at DESC);

ALTER TABLE ONLY public.sys_compensation_code
    ADD CONSTRAINT sys_compensation_code_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.sys_user(id);

ALTER TABLE ONLY public.sys_compensation_code
    ADD CONSTRAINT sys_compensation_code_used_by_user_id_fkey FOREIGN KEY (used_by_user_id) REFERENCES public.sys_user(id);

ALTER TABLE ONLY public.sys_user_compensation_record
    ADD CONSTRAINT sys_user_compensation_record_compensation_code_id_fkey FOREIGN KEY (compensation_code_id) REFERENCES public.sys_compensation_code(id);

ALTER TABLE ONLY public.sys_user_compensation_record
    ADD CONSTRAINT sys_user_compensation_record_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.sys_user(id);
