-- 拍拍伴读隐私请求、账号删除和购买最小保留表。
-- 中文说明：这些表保存删除流程、去标识化购买凭证和删除任务状态，不保存儿童正文、图片或音频。

CREATE TABLE IF NOT EXISTS public.reading_privacy_request (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code character varying(64) NOT NULL,
    request_type character varying(64) NOT NULL,
    request_status character varying(64) NOT NULL DEFAULT 'requested',
    request_scope character varying(128) NOT NULL DEFAULT 'all',
    deadline_at timestamp with time zone,
    completed_at timestamp with time zone,
    reason_code character varying(128),
    privacy_case_id character varying(128),
    parent_user_id bigint,
    retention_policy_code character varying(64),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_reading_privacy_request_parent_status
    ON public.reading_privacy_request(app_code, parent_user_id, request_type, request_status, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uk_reading_privacy_request_case
    ON public.reading_privacy_request(app_code, privacy_case_id)
    WHERE privacy_case_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.reading_privacy_purchase_retention (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code character varying(64) NOT NULL,
    privacy_case_id character varying(128) NOT NULL,
    deleted_user_hash character varying(128),
    transaction_id_hash character varying(128) NOT NULL,
    original_transaction_id_hash character varying(128),
    product_id character varying(256) NOT NULL,
    retention_reason character varying(128) NOT NULL,
    retention_expires_at timestamp with time zone NOT NULL,
    deidentified_at timestamp with time zone,
    purged_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_reading_purchase_retention_transaction
    ON public.reading_privacy_purchase_retention(app_code, transaction_id_hash);
CREATE INDEX IF NOT EXISTS idx_reading_purchase_retention_case
    ON public.reading_privacy_purchase_retention(app_code, privacy_case_id, retention_expires_at);
CREATE INDEX IF NOT EXISTS idx_reading_purchase_retention_purge
    ON public.reading_privacy_purchase_retention(app_code, purged_at, retention_expires_at);

CREATE TABLE IF NOT EXISTS public.reading_account_deletion_job (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code character varying(64) NOT NULL,
    privacy_case_id character varying(128) NOT NULL,
    job_status character varying(64) NOT NULL DEFAULT 'queued',
    scheduled_at timestamp with time zone,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    last_error_code character varying(128),
    last_error_message character varying(1024),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_reading_account_deletion_job_case
    ON public.reading_account_deletion_job(app_code, privacy_case_id);
CREATE INDEX IF NOT EXISTS idx_reading_account_deletion_job_status
    ON public.reading_account_deletion_job(app_code, job_status, scheduled_at);

CREATE TABLE IF NOT EXISTS public.reading_deleted_user_tombstone (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code character varying(64) NOT NULL,
    privacy_case_id character varying(128) NOT NULL,
    deleted_user_hash character varying(128) NOT NULL,
    deleted_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    retention_expires_at timestamp with time zone,
    purge_status character varying(64) DEFAULT 'pending' NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_reading_deleted_user_tombstone_case
    ON public.reading_deleted_user_tombstone(app_code, privacy_case_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_reading_deleted_user_tombstone_hash
    ON public.reading_deleted_user_tombstone(app_code, deleted_user_hash);
CREATE INDEX IF NOT EXISTS idx_reading_deleted_user_tombstone_purge
    ON public.reading_deleted_user_tombstone(app_code, purge_status, retention_expires_at);
