-- 拍拍伴读匿名权益 token、钱包、reservation、ledger 与本地快照。
-- 中文说明：云端权益按 token 维度记账；本地离线快照只保存签名和有效期，不保存儿童正文。

CREATE TABLE IF NOT EXISTS public.reading_entitlement_token (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code character varying(64) NOT NULL,
    parent_user_id bigint,
    token_hash character varying(128) NOT NULL,
    token_status character varying(64) NOT NULL DEFAULT 'active',
    consent_scope character varying(128),
    jurisdiction_code character varying(16),
    issued_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expires_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_reading_entitlement_token_hash
    ON public.reading_entitlement_token(app_code, token_hash);
CREATE INDEX IF NOT EXISTS idx_reading_entitlement_token_parent
    ON public.reading_entitlement_token(app_code, parent_user_id, token_status);

CREATE TABLE IF NOT EXISTS public.reading_entitlement_wallet (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code character varying(64) NOT NULL,
    entitlement_token_id bigint NOT NULL,
    service_type character varying(64) NOT NULL,
    remaining_count integer NOT NULL DEFAULT 0,
    reserved_count integer NOT NULL DEFAULT 0,
    used_count integer NOT NULL DEFAULT 0,
    expires_at timestamp with time zone,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_reading_entitlement_wallet_token_service
    ON public.reading_entitlement_wallet(app_code, entitlement_token_id, service_type);
CREATE INDEX IF NOT EXISTS idx_reading_entitlement_wallet_expiry
    ON public.reading_entitlement_wallet(app_code, service_type, expires_at);

CREATE TABLE IF NOT EXISTS public.reading_entitlement_reservation (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code character varying(64) NOT NULL,
    entitlement_token_id bigint NOT NULL,
    service_type character varying(64) NOT NULL,
    reservation_key character varying(128) NOT NULL,
    idempotency_key character varying(128),
    status character varying(64) NOT NULL DEFAULT 'reserved',
    requested_count integer NOT NULL DEFAULT 1,
    reserved_count integer NOT NULL DEFAULT 1,
    used_count integer NOT NULL DEFAULT 0,
    expires_at timestamp with time zone,
    committed_at timestamp with time zone,
    released_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_reading_entitlement_reservation_key
    ON public.reading_entitlement_reservation(app_code, reservation_key);
CREATE UNIQUE INDEX IF NOT EXISTS uk_reading_entitlement_reservation_idempotency
    ON public.reading_entitlement_reservation(app_code, entitlement_token_id, service_type, idempotency_key)
    WHERE idempotency_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_reading_entitlement_reservation_status_expiry
    ON public.reading_entitlement_reservation(app_code, service_type, status, expires_at);

CREATE TABLE IF NOT EXISTS public.reading_entitlement_ledger (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code character varying(64) NOT NULL,
    entitlement_token_id bigint NOT NULL,
    service_type character varying(64) NOT NULL,
    ledger_action character varying(64) NOT NULL,
    delta_count integer NOT NULL,
    before_remaining integer,
    after_remaining integer,
    source_type character varying(64),
    source_ref character varying(128),
    idempotency_key character varying(128),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_reading_entitlement_ledger_token_created
    ON public.reading_entitlement_ledger(app_code, entitlement_token_id, service_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_reading_entitlement_ledger_idempotency
    ON public.reading_entitlement_ledger(app_code, idempotency_key)
    WHERE idempotency_key IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.reading_entitlement_snapshot (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code character varying(64) NOT NULL,
    entitlement_token_id bigint,
    snapshot_type character varying(64) NOT NULL,
    service_limits_json jsonb NOT NULL,
    policy_version character varying(64) NOT NULL,
    issued_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    signature_base64 text NOT NULL,
    purchase_ref_hash character varying(128),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_reading_entitlement_snapshot_token_expiry
    ON public.reading_entitlement_snapshot(app_code, entitlement_token_id, snapshot_type, expires_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uk_reading_entitlement_snapshot_purchase
    ON public.reading_entitlement_snapshot(app_code, purchase_ref_hash, snapshot_type)
    WHERE purchase_ref_hash IS NOT NULL;
