-- 拍拍伴读家长同意、地区策略、供应商台账、隐私审计和安全事件表。
-- 中文说明：这些表只保存合规证明和低敏审计字段，不保存儿童图片、正文、录音或可形成画像的自由 payload。

CREATE TABLE IF NOT EXISTS public.reading_parent_consent (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code character varying(64) NOT NULL,
    parent_user_id bigint NOT NULL,
    consent_version character varying(64) NOT NULL,
    consent_scope character varying(128) NOT NULL,
    jurisdiction_code character varying(16) NOT NULL,
    step_up_method character varying(64) NOT NULL,
    consent_status character varying(64) NOT NULL DEFAULT 'active',
    direct_notice_version character varying(64),
    withdrawn_at timestamp with time zone,
    retention_policy_code character varying(64) NOT NULL DEFAULT 'parent_consent_legal_record',
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_reading_parent_consent_parent_scope
    ON public.reading_parent_consent(app_code, parent_user_id, consent_scope, consent_status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_reading_parent_consent_retention
    ON public.reading_parent_consent(app_code, retention_policy_code, withdrawn_at);

CREATE TABLE IF NOT EXISTS public.reading_jurisdiction_policy (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code character varying(64) NOT NULL,
    jurisdiction_code character varying(16) NOT NULL,
    min_digital_consent_age integer NOT NULL DEFAULT 16,
    policy_version character varying(64) NOT NULL,
    policy_status character varying(64) NOT NULL DEFAULT 'active',
    requires_parent_consent boolean DEFAULT TRUE NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_reading_jurisdiction_policy_active
    ON public.reading_jurisdiction_policy(app_code, jurisdiction_code, policy_version);
CREATE INDEX IF NOT EXISTS idx_reading_jurisdiction_policy_status
    ON public.reading_jurisdiction_policy(app_code, jurisdiction_code, policy_status);

CREATE TABLE IF NOT EXISTS public.reading_privacy_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code character varying(64) NOT NULL,
    parent_user_id bigint,
    privacy_case_id character varying(128),
    event_type character varying(128) NOT NULL,
    event_result character varying(64) NOT NULL,
    consent_scope character varying(128),
    request_id character varying(128),
    provider_code character varying(128),
    latency_ms integer,
    retention_policy_code character varying(64) NOT NULL DEFAULT 'privacy_audit_180d',
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_reading_privacy_event_parent_created
    ON public.reading_privacy_event(app_code, parent_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_reading_privacy_event_case
    ON public.reading_privacy_event(app_code, privacy_case_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_reading_privacy_event_retention
    ON public.reading_privacy_event(app_code, retention_policy_code, created_at);

CREATE TABLE IF NOT EXISTS public.reading_vendor_registry (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code character varying(64) NOT NULL,
    vendor_code character varying(128) NOT NULL,
    vendor_name character varying(256) NOT NULL,
    data_categories character varying(512) NOT NULL,
    processing_purpose character varying(512) NOT NULL,
    processing_region character varying(128),
    dpa_url character varying(1024),
    subprocessors_url character varying(1024),
    retention_summary character varying(512),
    training_use_status character varying(64) NOT NULL DEFAULT 'prohibited',
    vendor_status character varying(64) NOT NULL DEFAULT 'active',
    reviewed_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_reading_vendor_registry_code
    ON public.reading_vendor_registry(app_code, vendor_code);
CREATE INDEX IF NOT EXISTS idx_reading_vendor_registry_status
    ON public.reading_vendor_registry(app_code, vendor_status, reviewed_at);

CREATE TABLE IF NOT EXISTS public.reading_security_incident (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code character varying(64) NOT NULL,
    incident_key character varying(128) NOT NULL,
    severity character varying(64) NOT NULL,
    incident_status character varying(64) NOT NULL DEFAULT 'triage',
    discovered_at timestamp with time zone NOT NULL,
    contained_at timestamp with time zone,
    regulator_notification_due_at timestamp with time zone,
    regulator_notified_at timestamp with time zone,
    parent_notified_at timestamp with time zone,
    summary character varying(2048),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_reading_security_incident_key
    ON public.reading_security_incident(app_code, incident_key);
CREATE INDEX IF NOT EXISTS idx_reading_security_incident_status
    ON public.reading_security_incident(app_code, incident_status, severity, discovered_at DESC);

INSERT INTO public.reading_jurisdiction_policy (
    app_code, jurisdiction_code, min_digital_consent_age, policy_version, policy_status, requires_parent_consent
) VALUES
    ('paipai_readingcompanion', 'EU', 16, 'coppa-gdprk-2026-05', 'active', TRUE),
    ('paipai_readingcompanion', 'US', 13, 'coppa-gdprk-2026-05', 'active', TRUE),
    ('paipai_readingcompanion', 'DEFAULT', 16, 'coppa-gdprk-2026-05', 'active', TRUE)
ON CONFLICT DO NOTHING;
